// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

// Package pdftext reads the text a PDF already carries, so a model that cannot
// be handed a PDF can still be handed what one says.
//
// It sits beside imagenorm and does the same kind of job: untrusted bytes in, a
// safe in-memory representation out, nothing written and nothing executed.
//
// What it is NOT is an OCR engine. A PDF generated by an ordering system carries
// its text as text; a PDF that is a photograph of paper carries no text at all,
// and this package says so rather than guessing. The difference matters to the
// caller, because a document whose text was READ can have a quote checked
// against it and a document whose text was INVENTED cannot.
//
// # Why the parser runs in a sandbox
//
// These bytes arrive from an upload, so the file is hostile. The engine is
// pdfium — the PDF implementation in Chrome, and continuously fuzzed as such —
// compiled to WebAssembly and run under wazero, the runtime this tree already
// carries for licensecheck.
//
// The sandbox is the point, not an implementation detail. A pure-Go parser has
// the host's whole heap to spend, and the one this package used first would
// spend it: a 133-byte file whose cross-reference table named a large object
// number allocated 610 MB and reported success, and a 224-byte file whose page
// tree listed itself as its own child looped with no exit. Both are refused
// here in about a millisecond, and a bomb that did get past the parser would
// exhaust the module's memory rather than the process's.
//
// Unlike licensecheck, which builds a wazero runtime per verdict, the module is
// compiled ONCE and pooled: it is 5 MB and costs about a second to compile,
// against about two milliseconds to read a document.
package pdftext

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"sync"
	"time"
	"unicode/utf8"

	pdfium "github.com/klippa-app/go-pdfium"
	"github.com/klippa-app/go-pdfium/requests"
	"github.com/klippa-app/go-pdfium/webassembly"
	"golang.org/x/text/unicode/norm"
)

// ErrNoTextLayer is a PDF this package opened and found no text in — almost
// always a scan, where every page is one image.
//
// A distinct answer from a file that could not be opened, and the caller shows
// a different thing for each: a scan is a real document somebody can re-send in
// another form, while an unreadable file is broken.
var ErrNoTextLayer = errors.New("pdftext: this PDF carries no text layer")

// ErrUnreadable is a file the engine would not open as a PDF: not a PDF at all,
// truncated, encrypted, or malformed past the point of reading.
var ErrUnreadable = errors.New("pdftext: this file could not be read as a PDF")

// instanceWait bounds how long one reading waits for a free engine instance.
//
// It is a QUEUE bound, not a parse bound: reading a document takes single-digit
// milliseconds, so waiting this long means the pool is saturated by other
// readings, and the honest answer then is to fail this one and let the job
// retry rather than pile up behind it.
const instanceWait = 30 * time.Second

// Reader reads PDFs through one pooled engine. Safe for concurrent use.
//
// Build one per process and keep it: the pool holds the compiled module, and
// building a second would compile those 5 MB again.
type Reader struct {
	start sync.Once
	pool  pdfium.Pool
	err   error
}

// New returns a Reader whose engine is compiled on the FIRST document rather
// than now.
//
// Lazily, because the cost is real and most processes never pay it: a second of
// startup and the module's memory would otherwise be spent by every role that
// wires a document lane, including the ones that go on to read no PDFs at all.
func New() *Reader { return &Reader{} }

// started compiles and pools the module once, and answers the same way every
// time after that — including with the same failure, which is what stops a
// broken build from re-compiling 5 MB on every document.
//
// It reports only the error. The pool stays a field and is read as one, because
// handing it back out of here would give state this type already owns a second
// name to drift under.
func (r *Reader) started() error {
	r.start.Do(func() {
		// One instance per pool member, and the pool is what bounds concurrency:
		// each live instance holds its own module memory, so an unbounded pool
		// would turn a burst of uploads into a burst of address space.
		r.pool, r.err = webassembly.Init(webassembly.Config{MinIdle: 1, MaxIdle: 1, MaxTotal: 4})
		if r.err != nil {
			r.err = fmt.Errorf("pdftext: starting the PDF engine: %w", r.err)
		}
	})
	return r.err
}

// Close releases the compiled module and every pooled instance. A Reader that
// was never used closes cleanly, because there is nothing to release.
func (r *Reader) Close() error {
	if r.pool == nil {
		return nil
	}
	return r.pool.Close()
}

// Read returns the text a PDF states, at most maxChars+1 runes of it.
//
// The one rune past the caller's bound is deliberate and mirrors how the
// document lane already reads bytes: it is what separates "exactly at the limit"
// from "truncated to the limit", and without it a document of exactly maxChars
// and one of a million both arrive full-length and look identical.
//
// The answer is NFKC-normalised. A PDF's text is what a FONT draws, and a
// ligature is one rune standing for two letters — a reader sees "retrofit"
// where a byte comparison sees something else. The downstream grounding check
// is a plain substring match, so without this a model that quoted what the page
// shows would have its whole reading refused for quoting the document
// correctly.
func (r *Reader) Read(ctx context.Context, raw []byte, maxChars int) (string, error) {
	if maxChars <= 0 {
		return "", fmt.Errorf("pdftext: maxChars must be positive, got %d", maxChars)
	}
	text, err := r.readPages(ctx, raw, maxChars)
	if err != nil {
		return "", err
	}
	// Trimmed and normalised BEFORE the bound is applied. A page's text opens
	// with the whitespace that positioned its first line, and a ligature is one
	// rune that folds to two — budgeting either before they settle hands the
	// caller a different number of characters than it asked for.
	text = norm.NFKC.String(strings.TrimSpace(text))
	if text == "" {
		return "", ErrNoTextLayer
	}
	return truncateRunes(text, maxChars+1), nil
}

// readPages opens the document and walks it until the caller's budget is met.
//
// The engine validates the file before a page is reachable, so a document that
// opens is one whose structure pdfium accepted — which is what makes the page
// count below a fact about the file rather than a number the file chose.
func (r *Reader) readPages(ctx context.Context, raw []byte, maxChars int) (string, error) {
	if err := r.started(); err != nil {
		return "", err
	}
	instance, err := r.pool.GetInstance(instanceWait)
	if err != nil {
		return "", fmt.Errorf("pdftext: no engine instance free: %w", err)
	}
	//craft:ignore swallowed-errors returning the instance to the pool cannot change the reading already in hand
	defer func() { _ = instance.Close() }()

	doc, err := instance.OpenDocument(&requests.OpenDocument{File: &raw})
	if err != nil {
		// Everything the engine refuses arrives here — wrong magic, a broken
		// xref, a password. One sentinel for all of them: the caller shows a rep
		// "this could not be opened", and which internal reason it was is not
		// something they can act on.
		return "", fmt.Errorf("%w: %w", ErrUnreadable, err)
	}
	//craft:ignore swallowed-errors the document's own bytes are already read; a close failure cannot change them
	defer func() {
		_, _ = instance.FPDF_CloseDocument(&requests.FPDF_CloseDocument{Document: doc.Document})
	}()

	count, err := instance.FPDF_GetPageCount(&requests.FPDF_GetPageCount{Document: doc.Document})
	if err != nil {
		return "", fmt.Errorf("%w: %w", ErrUnreadable, err)
	}

	var out strings.Builder
	held := 0
	for page := range count.PageCount {
		// Checked per page rather than once: this is the caller's own deadline,
		// and a long document is exactly the case where it expires mid-read.
		if err := ctx.Err(); err != nil {
			return "", fmt.Errorf("%w: the reading did not finish in time", ErrUnreadable)
		}
		text, err := instance.GetPageText(&requests.GetPageText{
			Page: requests.Page{ByIndex: &requests.PageByIndex{Document: doc.Document, Index: page}},
		})
		if err != nil {
			return "", fmt.Errorf("%w: %w", ErrUnreadable, err)
		}
		out.WriteString(text.Text)
		// Stopped as soon as the budget is MET, so a thousand-page contract
		// costs the pages it took to fill the budget and not the other 990.
		// Counted incrementally rather than over the accumulated string, which
		// would re-walk everything read so far on every page.
		held += utf8.RuneCountInString(text.Text)
		if held > maxChars {
			break
		}
	}
	return out.String(), nil
}

// truncateRunes cuts a string to at most limit runes, never mid-rune.
func truncateRunes(s string, limit int) string {
	if utf8.RuneCountInString(s) <= limit {
		return s
	}
	count := 0
	for i := range s {
		if count == limit {
			return s[:i]
		}
		count++
	}
	return s
}
