// Code generated by compose/aicert/decisioncertcmd from internal/compose/aicert/records. DO NOT EDIT.
// Regenerate with `make gen`. A row exists for every decision record that is certified
// and whose scenario stamps are the ones this build computes; a stale record has none.

package ai

var decisionCertified = map[DecisionCertKey]DecisionCert{
	// records/site_triage/decision_triage_jev_compatible_typesafe_jev-1.13_cloud_frontier.json
	{Task: "site_triage", Site: "triage", Provider: "jev_compatible", Model: "typesafe/jev-1.13"}: {PromptVersion: "pcb8f06d8051b9da26e24b30ce2407cc7", CorpusVersion: "v1"},
}
