// Code generated by compose/aicert/decisioncertcmd from internal/compose/aicert/records. DO NOT EDIT.
// Regenerate with `make gen`. A row exists for every decision record that is certified
// and whose scenario stamps are the ones this build computes; a stale record has none.

package ai

var decisionCertified = map[DecisionCertKey]DecisionCert{}
