// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package main

import (
	"bytes"
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/margince/margince/backend/tools/internal/oasnode"
)

const header = "# Code generated by tools/gen-agentcontract from api/crm.yaml. DO NOT EDIT.\n"

// componentRef names one entry under components: its kind (schemas,
// responses, ...) and its name.
type componentRef struct{ kind, name string }

// agentContract returns the agent-facing contract, its operation index, and
// how many operations both carry. tables are the storage table names, which
// mark a description as a developer note.
func agentContract(src []byte, tables []string) ([]byte, []byte, int, error) {
	var doc yaml.Node
	if err := yaml.Unmarshal(src, &doc); err != nil {
		return nil, nil, 0, fmt.Errorf("parsing source: %w", err)
	}
	root := oasnode.Root(&doc)
	flatten(root)

	paths, _ := oasnode.Lookup(root, "paths")
	ops, tags, schemes := keepAgentOperations(root, paths)
	if len(ops) == 0 {
		return nil, nil, 0, fmt.Errorf("no operation is open to agents, so the walk no longer reaches the operations")
	}
	addSchemeNames(schemes, root)
	text := newProse(tables)
	text.sanitize(root, false)
	for _, op := range ops {
		text.describeOperation(op)
	}
	stripExtensions(root)

	components, _ := oasnode.Lookup(root, "components")
	kept, err := reachableComponents(components, oasnode.Refs(paths), schemes)
	if err != nil {
		return nil, nil, 0, err
	}
	pruneComponents(components, kept)
	pruneTags(root, tags)
	deleteKey(root, "servers")

	var out bytes.Buffer
	out.WriteString(header)
	enc := yaml.NewEncoder(&out)
	enc.SetIndent(2)
	if err := enc.Encode(root); err != nil {
		return nil, nil, 0, fmt.Errorf("marshaling the agent contract: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, nil, 0, fmt.Errorf("marshaling the agent contract: %w", err)
	}
	return out.Bytes(), renderIndex(root, ops), len(ops), nil
}

// flatten replaces every alias with a copy of the node it names, and drops
// anchors and comments. The source reuses anchor names, and an alias kept
// while its anchor sat in a dropped operation would point at nothing.
func flatten(n *yaml.Node) {
	if n.Kind == yaml.AliasNode {
		*n = *deepCopy(n.Alias)
	}
	n.Anchor = ""
	n.HeadComment, n.LineComment, n.FootComment = "", "", ""
	for _, child := range n.Content {
		flatten(child)
	}
}

func deepCopy(n *yaml.Node) *yaml.Node {
	clone := *n
	clone.Content = make([]*yaml.Node, len(n.Content))
	for i, child := range n.Content {
		clone.Content[i] = deepCopy(child)
	}
	return &clone
}

// stripExtensions removes every x-* key at every depth.
func stripExtensions(n *yaml.Node) {
	if n.Kind == yaml.MappingNode {
		kept := n.Content[:0]
		for i := 0; i+1 < len(n.Content); i += 2 {
			if strings.HasPrefix(n.Content[i].Value, "x-") {
				continue
			}
			kept = append(kept, n.Content[i], n.Content[i+1])
		}
		n.Content = kept
	}
	for _, child := range n.Content {
		stripExtensions(child)
	}
}

// reachableComponents follows refs from the kept paths to every component
// they need, transitively. A ref it cannot resolve is an error: emitted, it
// would point an agent at a definition the file does not have.
func reachableComponents(components *yaml.Node, seeds []string, schemes map[string]bool) (map[componentRef]bool, error) {
	kept := map[componentRef]bool{}
	for name := range schemes {
		ref := componentRef{"securitySchemes", name}
		if _, ok := component(components, ref); !ok {
			return nil, fmt.Errorf("an operation names security scheme %q, which components.securitySchemes does not declare", name)
		}
		kept[ref] = true
	}
	queue := seeds
	for len(queue) > 0 {
		raw := queue[0]
		queue = queue[1:]
		local, ok := strings.CutPrefix(raw, "#/components/")
		kind, name, split := strings.Cut(local, "/")
		if !ok || !split {
			return nil, fmt.Errorf("$ref %q does not point into this document's components", raw)
		}
		ref := componentRef{kind, name}
		if kept[ref] {
			continue
		}
		node, found := component(components, ref)
		if !found {
			return nil, fmt.Errorf("$ref %q names a component the contract does not declare", raw)
		}
		kept[ref] = true
		queue = append(queue, oasnode.Refs(node)...)
	}
	return kept, nil
}

func component(components *yaml.Node, ref componentRef) (*yaml.Node, bool) {
	kind, ok := oasnode.Lookup(components, ref.kind)
	if !ok {
		return nil, false
	}
	return oasnode.Lookup(kind, ref.name)
}

// pruneComponents keeps only the kept entries, in source order, and drops a
// kind left empty.
func pruneComponents(components *yaml.Node, kept map[componentRef]bool) {
	if components == nil {
		return
	}
	keptKinds := components.Content[:0]
	for i := 0; i+1 < len(components.Content); i += 2 {
		kind, entries := components.Content[i], components.Content[i+1]
		keptEntries := entries.Content[:0]
		for j := 0; j+1 < len(entries.Content); j += 2 {
			if kept[componentRef{kind.Value, entries.Content[j].Value}] {
				keptEntries = append(keptEntries, entries.Content[j], entries.Content[j+1])
			}
		}
		entries.Content = keptEntries
		if len(keptEntries) > 0 {
			keptKinds = append(keptKinds, kind, entries)
		}
	}
	components.Content = keptKinds
}

// pruneTags keeps the top-level tag entries a kept operation uses.
func pruneTags(root *yaml.Node, used map[string]bool) {
	tags, ok := oasnode.Lookup(root, "tags")
	if !ok {
		return
	}
	kept := tags.Content[:0]
	for _, tag := range tags.Content {
		if used[oasnode.Scalar(tag, "name")] {
			kept = append(kept, tag)
		}
	}
	tags.Content = kept
}

func deleteKey(node *yaml.Node, key string) {
	for i := 0; i+1 < len(node.Content); i += 2 {
		if node.Content[i].Value == key {
			node.Content = append(node.Content[:i], node.Content[i+2:]...)
			return
		}
	}
}
