// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package main

import (
	"fmt"
	"math"
	"sort"
	"strconv"
	"strings"
)

// The plain-language page answers the daily-use record for a reader who will
// never run the bench: questions for headings, seconds for milliseconds, a
// colour for a verdict. The technical facts stay inside its details block.

const issueURL = "https://github.com/margince/margince/issues/"

// momentKind says how a flow's rows become one answer on the page.
type momentKind int

const (
	// screen: the worst gated row decides both the colour and the time.
	screen momentKind = iota
	// journey: the gated halves decide the colour, the ungated end-to-end row the time.
	journey
	// firstLoad: one ungated try after a restart, told as a sentence.
	firstLoad
)

type moment struct {
	flow, label string
	kind        momentKind
}

type question struct {
	heading string
	moments []moment
}

// questions maps each flow the bench records to the question it answers. A
// flow missing here still reaches the page, under "What else did we measure?".
var questions = []question{
	{"How fast does my morning start?", []moment{
		{"app_shell", "Opening the app", screen},
		{"worklist", "The Worklist", screen},
		{"home", "Home", screen},
		{"worklist_first_load", "The Worklist", firstLoad},
		{"search_first_load", "Search", firstLoad},
	}},
	{"How quickly do I find a customer?", []moment{
		{"palette_search", "Typing a name in the search box", screen},
		{"palette_search_prefix", "Typing the first few letters", screen},
		{"results_search", "The full search results", screen},
		{"search_to_company", "Search, then open the company", journey},
	}},
	{"How quickly do I find a deal?", []moment{
		{"search_to_deal", "Search, then open the deal", journey},
	}},
	{"How fast do lists and records open?", []moment{
		{"lists", "A list of 50 records", screen},
		{"record_open", "Opening a record", screen},
		{"contact_360", "A contact's whole story", screen},
	}},
	{"How fast is the analytics screen?", []moment{
		{"analytics", "The analytics screen", screen},
	}},
}

// teamHeading is the morning-load question. Its rows belong to the whole team
// rather than one seat, so it gets its own table shape.
const teamHeading = "What happens when the whole team starts at 9:00?"

const plainIntro = `# How fast is Margince every day?

<!-- GENERATED by ` + "`make perfdoc`" + ` from the bench-daily record; do not edit by hand. -->

How long the screens a sales rep and a sales manager open every day take to answer,
measured on a test company the size of a mid-market customer. Each answer comes from
many tries, and the time shown is one that nearly every try beat.

| Colour | What it means |
|---|---|
| 🟢 Fast | Within the time we promise. |
| 🟡 Slower than we promise | Over the promise, and we are working on it: the issue is linked. |
| 🔴 Too slow | Over the promise with no fix under way yet, or some tries failed. |
| ⚪ Not measured | The screen had nothing to show yet, or the run cannot prove it. |

`

// renderPlain builds benchmark.md from the daily record alone.
func renderPlain(records map[string]record) string {
	var b strings.Builder
	b.WriteString(plainIntro)
	r, ok := records[dailyTarget]
	if !ok {
		b.WriteString("Nobody has measured this yet. Run `make bench-daily` to fill this page.\n\n")
		renderPlainDetails(&b, nil)
		return strings.TrimRight(b.String(), "\n") + "\n"
	}
	if r.Corpus != nil && r.Corpus.Scale != 1 {
		fmt.Fprintf(&b, "**This run is a trial.** It used a test company %s the published size, so no colour here is a promise.\n\n", scaleWords(r.Corpus.Scale))
	}
	renderPlainDetails(&b, &r)
	rows := groupByFlow(r)
	for _, q := range questions {
		renderQuestion(&b, q, rows)
	}
	renderTeam(&b, rows)
	renderLeftovers(&b, rows)
	return strings.TrimRight(b.String(), "\n") + "\n"
}

// flowRows holds one flow's rows by seat, in record order.
type flowRows map[string][]measurement

func flowOf(m measurement) string {
	if m.Flow != "" {
		return m.Flow
	}
	return m.Name
}

func groupByFlow(r record) map[string]flowRows {
	out := map[string]flowRows{}
	for _, m := range r.Budgets {
		f := flowOf(m)
		if out[f] == nil {
			out[f] = flowRows{}
		}
		out[f][m.Seat] = append(out[f][m.Seat], m)
	}
	return out
}

// scaleWords says a development scale the way a reader compares sizes.
func scaleWords(scale float64) string {
	return strconv.FormatFloat(scale, 'f', -1, 64) + " times"
}

// renderQuestion prints one heading with a rep and manager table, then the
// first-open sentences. A question the record has no rows for says so.
func renderQuestion(b *strings.Builder, q question, rows map[string]flowRows) {
	fmt.Fprintf(b, "## %s\n\n", q.heading)
	var table, after []string
	for _, mo := range q.moments {
		seats, ok := rows[mo.flow]
		if !ok {
			continue
		}
		delete(rows, mo.flow)
		if mo.kind == firstLoad {
			after = append(after, firstLoadLines(mo, seats)...)
			continue
		}
		rep, manager := answerFor(mo.kind, seats["rep"]), answerFor(mo.kind, seats["manager"])
		table = append(table, fmt.Sprintf("| %s | %s | %s | %s |", mo.label, rep.cell(), manager.cell(), worstOf(rep, manager).words()))
	}
	if len(table) == 0 && len(after) == 0 {
		b.WriteString("Not measured in the last run.\n\n")
		return
	}
	if len(table) > 0 {
		b.WriteString("| Moment | Rep | Manager | In plain words |\n|---|---|---|---|\n")
		b.WriteString(strings.Join(table, "\n") + "\n\n")
	}
	if len(after) > 0 {
		b.WriteString("The first open after a restart is slower, because nothing is warmed up yet:\n\n")
		b.WriteString(strings.Join(after, "\n") + "\n\n")
	}
}

func firstLoadLines(mo moment, seats flowRows) []string {
	var lines []string
	for _, seat := range sortedSeats(seats) {
		for _, m := range seats[seat] {
			lines = append(lines, fmt.Sprintf("- %s for a %s, first open after a restart: %s.",
				mo.label, seat, lowerFirst(spokenTime(m.P95Ms))))
		}
	}
	return lines
}

// renderTeam answers the morning-load question, whose rows carry no seat.
func renderTeam(b *strings.Builder, rows map[string]flowRows) {
	fmt.Fprintf(b, "## %s\n\n", teamHeading)
	seats, ok := rows["morning_load"]
	if !ok {
		b.WriteString("Not measured in the last run.\n\n")
		return
	}
	delete(rows, "morning_load")
	b.WriteString("Every rep and manager opens the app, the Worklist, Home and a few records at the same moment.\n\n")
	b.WriteString("| Moment | Whole team | In plain words |\n|---|---|---|\n")
	for _, seat := range sortedSeats(seats) {
		a := answerFor(screen, seats[seat])
		fmt.Fprintf(b, "| A small request while everyone starts | %s | %s |\n", a.cell(), a.words())
	}
	b.WriteString("\n")
}

// renderLeftovers prints flows no question claims, so a new flow shows up
// here instead of disappearing from the page.
func renderLeftovers(b *strings.Builder, rows map[string]flowRows) {
	if len(rows) == 0 {
		return
	}
	b.WriteString("## What else did we measure?\n\n")
	b.WriteString("| Moment | Rep | Manager | In plain words |\n|---|---|---|---|\n")
	for _, flow := range sortedKeys(rows) {
		rep, manager := answerFor(screen, rows[flow]["rep"]), answerFor(screen, rows[flow]["manager"])
		fmt.Fprintf(b, "| `%s` | %s | %s | %s |\n", flow, rep.cell(), manager.cell(), worstOf(rep, manager).words())
	}
	b.WriteString("\n")
}

// answer is one seat's result for one moment.
type answer struct {
	measured bool
	sev      severity
	ms       float64
	issue    int
}

// answerFor folds a seat's rows for one moment into one answer: the worst
// gated row decides, and a journey shows its end-to-end time instead.
func answerFor(kind momentKind, rows []measurement) answer {
	var worst measurement
	var seen bool
	var total float64
	for _, m := range rows {
		if judge(m).sev == sevUngated {
			if m.Verdict == storedNotGated && m.P95Ms > total {
				total = m.P95Ms
			}
			continue
		}
		if !seen || worse(m, worst) {
			worst, seen = m, true
		}
	}
	if !seen {
		return answer{}
	}
	a := answer{measured: true, sev: judge(worst).sev, ms: worst.P95Ms, issue: worst.KnownIssue}
	if kind == journey && total > 0 {
		a.ms = total
	}
	return a
}

func worstOf(a, b answer) answer {
	if !a.measured || (b.measured && b.sev > a.sev) {
		return b
	}
	return a
}

func (a answer) cell() string {
	if !a.measured {
		return "⚪ Not measured"
	}
	return colour(a.sev) + " " + spokenTime(a.ms)
}

func (a answer) words() string {
	if !a.measured {
		return "Not measured yet."
	}
	switch a.sev {
	case sevWithin:
		return "Fast."
	case sevInconclusive:
		return "Fast on the small trial company, which proves nothing yet."
	case sevOverListed:
		return fmt.Sprintf("Slower than we promise: we are working on it ([#%d](%s%d)).", a.issue, issueURL, a.issue)
	case sevFailed:
		return "Too slow: some tries failed."
	}
	return "Too slow, and nobody is working on it yet."
}

func colour(s severity) string {
	switch s {
	case sevWithin:
		return "🟢"
	case sevOverListed:
		return "🟡"
	case sevOver, sevFailed:
		return "🔴"
	}
	return "⚪"
}

// spokenTime rounds a time the way it is said aloud: two bands under a
// second, then seconds to one decimal, then whole seconds from ten on.
func spokenTime(ms float64) string {
	switch {
	case ms < 250:
		return "Under a quarter of a second"
	case ms < 1000:
		return "Under a second"
	}
	seconds := math.Round(ms/100) / 10
	if seconds >= 10 {
		seconds = math.Round(seconds)
	}
	if seconds == 1 {
		return "About 1 second"
	}
	return fmt.Sprintf("About %s seconds", strings.TrimSuffix(fmt.Sprintf("%.1f", seconds), ".0"))
}

// thousands groups digits in threes, as the page's readers write a count.
func thousands(n int) string {
	digits := strconv.Itoa(n)
	for i := len(digits) - 3; i > 0; i -= 3 {
		digits = digits[:i] + "," + digits[i:]
	}
	return digits
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func sortedSeats(seats flowRows) []string { return sortedKeys(seats) }

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// renderPlainDetails holds what a technical reader needs to trust the page:
// the target, the test company, the machine, the date and the rounding rule.
func renderPlainDetails(b *strings.Builder, r *record) {
	b.WriteString("<details>\n<summary>How this page is made</summary>\n\n")
	b.WriteString("Generated by `make perfdoc` from the `bench-daily` record under `docs/reference/perfbench/`,\n")
	b.WriteString("which `make bench-daily` writes; do not edit by hand.\n")
	if r != nil && r.Corpus != nil {
		c := r.Corpus
		fmt.Fprintf(b, "The test company has %s contacts at %s companies, %s deals, %s leads,\n%s projects and %s activities, owned by %d reps under %d managers.\n",
			thousands(c.Contacts), thousands(c.Companies), thousands(c.Deals), thousands(c.Leads),
			thousands(c.Projects), thousands(c.Activities), c.Reps, c.Managers)
	}
	b.WriteString("\n")
	if r != nil {
		m := r.Machine
		fmt.Fprintf(b, "Measured on %s on %s (%d cores, %s), Postgres %s.\n",
			r.MeasuredOn, orUnknown(m.CPU), m.Cores, memory(m.MemoryGiB), orUnknown(m.Postgres))
		b.WriteString("Each time is the p95 of its rows: 95 in every 100 tries were faster.\n\n")
	}
	b.WriteString("Rounding: under 250 ms reads \"under a quarter of a second\", under 1 s \"under a second\",\n")
	b.WriteString("then seconds to one decimal, and whole seconds from 10 s on. The colour is the bench's own verdict\n")
	b.WriteString("against the budget, and a moment takes the worst of its rows.\n\n")
	b.WriteString("Every number, per seat and against its budget id: [performance-budgets.md](performance-budgets.md).\n")
	b.WriteString("How a case is chosen and added: [design-a-bench-case.md](../how-to/design-a-bench-case.md).\n\n")
	b.WriteString("</details>\n\n")
}
