// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package main

import (
	"fmt"
	"sort"
	"strings"
)

const pageHeader = `<!-- GENERATED by ` + "`make perfdoc`" + ` from the benchmark records; do not edit by hand. -->

# Performance budgets and what was measured

Every performance budget this product publishes, and the last measurement taken
for it. Rendered by ` + "`backend/tools/gen-perfdoc`" + ` from the records under
` + "`docs/reference/perfbench/`" + `, which the benchmark targets write as they run.
[benchmark.md](benchmark.md) answers the same numbers in plain words.

No merge check reads these numbers: a latency differs on every run, so each row
records the machine and date it was measured on, and a budget nobody has
measured is listed as not measured. The budgets are the published claim; a
record is evidence about one machine on one day.

Re-measure with ` + "`make bench-perf`" + `, ` + "`make bench-record`" + `,
` + "`make bench-capture`" + `, ` + "`make bench-daily`" + ` (each needs ` + "`make db-up`" + `) or
` + "`make bench-mobile`" + `. Each writes its own record and re-renders this page.
The weekly scheduled job runs ` + "`make bench-perf-check`" + ` and
` + "`make bench-mobile-check`" + `, which measure without recording, so nothing
here changes until somebody measures by hand.

`

// render builds the whole page: the claim table first, because a reader comes
// for "does it hold", then the per-seat rows, then the machines, because the
// answer means nothing without them.
func render(records map[string]record) string {
	var b strings.Builder
	b.WriteString(pageHeader)
	renderTable(&b, records)
	renderGaps(&b)
	renderDaily(&b, records)
	renderMachines(&b, records)
	return b.String()
}

// renderTable prints one row per PUBLISHED budget, measured or not.
func renderTable(b *strings.Builder, records map[string]record) {
	b.WriteString("## The budgets\n\n")
	b.WriteString("| ID | Operation | Published budget | Measured p95 | Verdict | Measured on |\n")
	b.WriteString("|---|---|---|---|---|---|\n")
	for _, budget := range published {
		measured, found := findMeasurement(records, budget)
		if !found {
			fmt.Fprintf(b, "| `%s` | %s | %s |  | **not measured** |  |\n",
				budget.id, budget.operation, budget.budget)
			continue
		}
		fmt.Fprintf(b, "| `%s` | %s | %s | %s | %s | %s |\n",
			budget.id, budget.operation, budget.budget,
			p95Cell(measured.value), verdict(measured.value), measured.on)
	}
	b.WriteString("\n")
}

// found is one located measurement plus the day its record was written.
type found struct {
	value measurement
	on    string
}

// findMeasurement picks, across every record that measures a budget, the row
// a reader most needs: the worst verdict, then the slowest p95. PERF-1 is
// several opens on two targets, and the fastest of them answers nothing. A
// target whose record has no row for the budget adds nothing, so a record that
// stopped covering it cannot keep an old row alive.
//
// Rows that gate nothing (no data, not gated) are skipped, and printed only
// when they are all a budget has.
func findMeasurement(records map[string]record, budget publishedBudget) (found, bool) {
	var best, ungated found
	var seen, seenUngated bool
	for _, target := range budget.measuredBy {
		r, ok := records[target]
		if !ok {
			continue
		}
		for _, m := range r.Budgets {
			switch {
			case m.ID != budget.id:
			case judge(m).sev == sevUngated:
				if !seenUngated {
					ungated, seenUngated = found{value: m, on: r.MeasuredOn}, true
				}
			case !seen || worse(m, best.value):
				best, seen = found{value: m, on: r.MeasuredOn}, true
			}
		}
	}
	if seen {
		return best, true
	}
	return ungated, seenUngated
}

// p95Cell leaves a row with no data blank: a zero would read as instant, and
// a few samples under the floor would read as a p95 the run never claimed.
func p95Cell(m measurement) string {
	if m.Verdict == storedNoData || m.Samples == 0 && m.Verdict != "" {
		return ""
	}
	return millis(m.P95Ms)
}

// millis formats a duration the way a reader compares two of them: whole
// milliseconds once a number is big enough that the decimals are noise.
func millis(ms float64) string {
	if ms >= 100 {
		return fmt.Sprintf("%.0f ms", ms)
	}
	return fmt.Sprintf("%.1f ms", ms)
}

// renderGaps names the budgets nothing measures, and says why each is absent.
// Kept as prose under the table rather than folded into it: "not measured" is a
// verdict, and the reason it is unmeasured is a different kind of fact.
func renderGaps(b *strings.Builder) {
	var gaps []string
	for _, budget := range published {
		if len(budget.measuredBy) == 0 {
			gaps = append(gaps, fmt.Sprintf("`%s` (%s)", budget.id, budget.operation))
		}
	}
	if len(gaps) == 0 {
		return
	}
	b.WriteString("### Still unmeasured\n\n")
	fmt.Fprintf(b, "No harness covers %s. They are listed above as `not measured` rather than\n",
		strings.Join(gaps, ", "))
	b.WriteString("omitted, because a budget missing from this page reads as one that holds.\n\n")
}

// renderDaily lists every daily-use row per seat. The budgets table shows one
// row per budget; this answers which screen, for whom, and why it was judged so.
func renderDaily(b *strings.Builder, records map[string]record) {
	b.WriteString("## Daily use (`make bench-daily`)\n\n")
	r, ok := records[dailyTarget]
	if !ok {
		b.WriteString("Not measured yet: `make bench-daily` fills this section.\n\n")
		return
	}
	b.WriteString("The screens a rep and a manager open every day, timed over HTTP as the screen calls them.\n")
	b.WriteString("A row with no data had nothing to time, and its note says why; a row not gated is reported without a budget.\n\n")
	b.WriteString("| measurement | seat | p50 | p95 | budget | samples | verdict | notes |\n")
	b.WriteString("|---|---|---|---|---|---|---|---|\n")
	for _, m := range r.Budgets {
		p50 := millis(m.P50Ms)
		if p95Cell(m) == "" {
			p50 = ""
		}
		fmt.Fprintf(b, "| `%s` | %s | %s | %s | %s | %d | %s | %s |\n",
			m.Name, m.Seat, p50, p95Cell(m), millis(m.BudgetMs), m.Samples, verdict(m), dailyNotes(m))
	}
	b.WriteString("\n")
}

// dailyNotes carries the row's note and the counts a verdict alone does not show.
func dailyNotes(m measurement) string {
	var notes []string
	if m.Note != "" {
		notes = append(notes, m.Note)
	}
	if m.Status5xx > 0 {
		notes = append(notes, fmt.Sprintf("%d server errors", m.Status5xx))
	}
	if m.Status422 > 0 {
		notes = append(notes, fmt.Sprintf("%d refused as too broad (422)", m.Status422))
	}
	if m.Acquires > 0 {
		notes = append(notes, fmt.Sprintf("pool wait %s in all, %s at most, over %d acquires on a pool of %d",
			millis(m.PoolWaitMs), millis(m.PoolWaitMaxMs), m.Acquires, m.PoolSize))
	}
	return strings.Join(notes, "; ")
}

// renderMachines prints the hardware behind each record. One block per target,
// because the three targets are separate runs and can honestly have been taken
// on different machines on different days.
func renderMachines(b *strings.Builder, records map[string]record) {
	if len(records) == 0 {
		b.WriteString("## Machines\n\nNothing has been measured in this checkout.\n")
		return
	}
	b.WriteString("## Machines\n\n")
	b.WriteString("A latency is only true of the machine that produced it.\n\n")
	targets := make([]string, 0, len(records))
	for target := range records {
		targets = append(targets, target)
	}
	sort.Strings(targets)
	for _, target := range targets {
		renderMachine(b, records[target])
	}
}

func renderMachine(b *strings.Builder, r record) {
	fmt.Fprintf(b, "### `make %s` · measured %s\n\n", r.Target, r.MeasuredOn)
	b.WriteString("| | |\n|---|---|\n")
	m := r.Machine
	fmt.Fprintf(b, "| os / arch | %s / %s |\n", m.OS, m.Arch)
	fmt.Fprintf(b, "| cpu | %s (%d cores) |\n", orUnknown(m.CPU), m.Cores)
	fmt.Fprintf(b, "| memory | %s |\n", memory(m.MemoryGiB))
	fmt.Fprintf(b, "| toolchain | %s |\n", orUnknown(m.Toolchain))
	if m.Postgres != "" {
		fmt.Fprintf(b, "| postgres | %s |\n", m.Postgres)
	}
	if m.Network != "" {
		fmt.Fprintf(b, "| network | %s |\n", m.Network)
	}
	if m.Viewport != "" {
		fmt.Fprintf(b, "| viewport | %s |\n", m.Viewport)
	}
	b.WriteString("\n")
	if r.Target == dailyTarget {
		b.WriteString("Its rows are listed per seat under [Daily use](#daily-use-make-bench-daily).\n\n")
		return
	}
	renderSamples(b, r)
}

// renderSamples prints every row the record carries, not only the one the table
// above chose. The table answers "does the budget hold"; this answers "what
// exactly was run", which is the question a surprising number invites.
func renderSamples(b *strings.Builder, r record) {
	b.WriteString("| measurement | p50 | p95 | p99 | budget | samples |\n")
	b.WriteString("|---|---|---|---|---|---|\n")
	for _, m := range r.Budgets {
		fmt.Fprintf(b, "| `%s` | %s | %s | %s | %s | %d |\n",
			m.Name, millis(m.P50Ms), millis(m.P95Ms), millis(m.P99Ms),
			millis(m.BudgetMs), m.Samples)
	}
	b.WriteString("\n")
}

// orUnknown renders a fact this process could not read. An empty cell would
// read as "nothing to say"; a machine always has a CPU.
func orUnknown(value string) string {
	if strings.TrimSpace(value) == "" {
		return "unknown"
	}
	return value
}

func memory(gib int) string {
	if gib <= 0 {
		return "unknown"
	}
	return fmt.Sprintf("%d GiB", gib)
}
