// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package main

import (
	"fmt"
	"sort"
	"strings"
)

const pageHeader = `<!-- GENERATED by ` + "`make bench-record`" + ` / ` + "`bench-capture`" + ` / ` + "`bench-mobile`" + `; do not edit by hand. -->

# Performance budgets and what was measured

Every performance budget this product publishes, and the last measurement taken
for it. Rendered by ` + "`backend/tools/gen-perfdoc`" + ` from the records under
` + "`docs/reference/perfbench/`" + `, which the benchmark targets write as they run.

CI does not check these numbers: a latency differs on every run, so each row
records the machine and date it was measured on, and a budget nobody has
measured is listed as not measured. The budgets are the published claim; a
record is evidence about one machine on one day.

Re-measure with ` + "`make bench-record`" + `, ` + "`make bench-capture`" + ` or
` + "`make bench-mobile`" + ` (each needs ` + "`make db-up`" + ` except the last). None of
them runs in CI, so nothing here changes until somebody measures.

`

// render builds the whole page: the claim table first, because a reader comes
// for "does it hold", then the machines, because the answer means nothing
// without them.
func render(records map[string]record) string {
	var b strings.Builder
	b.WriteString(pageHeader)
	renderTable(&b, records)
	renderGaps(&b)
	renderMachines(&b, records)
	return b.String()
}

// renderTable prints one row per PUBLISHED budget, measured or not.
func renderTable(b *strings.Builder, records map[string]record) {
	b.WriteString("## The budgets\n\n")
	b.WriteString("| ID | Operation | Published budget | Measured p95 | Verdict | Measured on |\n")
	b.WriteString("|---|---|---|---|---|---|\n")
	for _, budget := range published {
		measured, found := findMeasurement(records, budget)
		if !found {
			fmt.Fprintf(b, "| `%s` | %s | %s |  | **not measured** |  |\n",
				budget.id, budget.operation, budget.budget)
			continue
		}
		fmt.Fprintf(b, "| `%s` | %s | %s | %s | %s | %s |\n",
			budget.id, budget.operation, budget.budget,
			millis(measured.value.P95Ms), verdict(measured.value), measured.on)
	}
	b.WriteString("\n")
}

// found is one located measurement plus the day its record was written.
type found struct {
	value measurement
	on    string
}

// findMeasurement locates a published budget's row in whichever record measures
// it. A budget whose target has a record but no row for it counts as unmeasured
// — a record that stopped covering a budget must not keep the old row alive.
func findMeasurement(records map[string]record, budget publishedBudget) (found, bool) {
	if budget.measuredBy == "" {
		return found{}, false
	}
	r, ok := records[budget.measuredBy]
	if !ok {
		return found{}, false
	}
	// The worst row wins when one budget id covers several measurements: PERF-1
	// is three separate opens, and a page reporting the fastest of them would
	// answer a question nobody asked.
	var worst measurement
	var seen bool
	for _, m := range r.Budgets {
		if m.ID != budget.id {
			continue
		}
		if !seen || m.P95Ms > worst.P95Ms {
			worst, seen = m, true
		}
	}
	if !seen {
		return found{}, false
	}
	return found{value: worst, on: r.MeasuredOn}, true
}

// verdict says whether the measurement held, in words rather than a symbol so
// the column survives being pasted into a procurement answer.
//
// `>=`, not `>`: every published budget is a STRICT bound — "< 100 ms",
// "< 300 ms" — so a p95 landing exactly on the number does not satisfy it.
// search.BenchReport.Gate() and the mobile spec's toBeLessThan read the same
// bound the same way; a page that disagreed with the gate about a run would be
// worse than no page.
//
// A caveat suppresses a PASS and never a BREACH, which is deliberate and is the
// asymmetry to understand before changing it. A caveat says the run did not meet
// the condition the budget binds under — today, only that PERF-7 was measured on
// a tier below mid-market. That tier is strictly SMALLER in every seeded
// dimension, and measured slower at mid-market than at SMB (9.9 ms vs 8.9 ms),
// so a breach on the small one is real evidence about the large one, while a
// pass on it proves nothing. Reporting "inconclusive" over a blown budget would
// hide the single number a reader most needs. If a future caveat ever describes
// a condition HARDER than the real one, that asymmetry stops holding and this
// has to be revisited rather than extended.
func verdict(m measurement) string {
	if m.P95Ms >= m.BudgetMs {
		if m.Caveat != "" {
			return fmt.Sprintf("**OVER BUDGET**: %s", m.Caveat)
		}
		return "**OVER BUDGET**"
	}
	if m.Caveat != "" {
		return fmt.Sprintf("inconclusive: %s", m.Caveat)
	}
	return "within budget"
}

// millis formats a duration the way a reader compares two of them: whole
// milliseconds once a number is big enough that the decimals are noise.
func millis(ms float64) string {
	if ms >= 100 {
		return fmt.Sprintf("%.0f ms", ms)
	}
	return fmt.Sprintf("%.1f ms", ms)
}

// renderGaps names the budgets nothing measures, and says why each is absent.
// Kept as prose under the table rather than folded into it: "not measured" is a
// verdict, and the reason it is unmeasured is a different kind of fact.
func renderGaps(b *strings.Builder) {
	var gaps []string
	for _, budget := range published {
		if budget.measuredBy == "" {
			gaps = append(gaps, fmt.Sprintf("`%s` (%s)", budget.id, budget.operation))
		}
	}
	if len(gaps) == 0 {
		return
	}
	b.WriteString("### Still unmeasured\n\n")
	fmt.Fprintf(b, "No harness covers %s. They are listed above as `not measured` rather than\n",
		strings.Join(gaps, ", "))
	b.WriteString("omitted, because a budget missing from this page reads as one that holds.\n\n")
}

// renderMachines prints the hardware behind each record. One block per target,
// because the three targets are separate runs and can honestly have been taken
// on different machines on different days.
func renderMachines(b *strings.Builder, records map[string]record) {
	if len(records) == 0 {
		b.WriteString("## Machines\n\nNothing has been measured in this checkout.\n")
		return
	}
	b.WriteString("## Machines\n\n")
	b.WriteString("A latency is only true of the machine that produced it.\n\n")
	targets := make([]string, 0, len(records))
	for target := range records {
		targets = append(targets, target)
	}
	sort.Strings(targets)
	for _, target := range targets {
		renderMachine(b, records[target])
	}
}

func renderMachine(b *strings.Builder, r record) {
	fmt.Fprintf(b, "### `make %s` · measured %s\n\n", r.Target, r.MeasuredOn)
	b.WriteString("| | |\n|---|---|\n")
	m := r.Machine
	fmt.Fprintf(b, "| os / arch | %s / %s |\n", m.OS, m.Arch)
	fmt.Fprintf(b, "| cpu | %s (%d cores) |\n", orUnknown(m.CPU), m.Cores)
	fmt.Fprintf(b, "| memory | %s |\n", memory(m.MemoryGiB))
	fmt.Fprintf(b, "| toolchain | %s |\n", orUnknown(m.Toolchain))
	if m.Postgres != "" {
		fmt.Fprintf(b, "| postgres | %s |\n", m.Postgres)
	}
	if m.Network != "" {
		fmt.Fprintf(b, "| network | %s |\n", m.Network)
	}
	if m.Viewport != "" {
		fmt.Fprintf(b, "| viewport | %s |\n", m.Viewport)
	}
	b.WriteString("\n")
	renderSamples(b, r)
}

// renderSamples prints every row the record carries, not only the one the table
// above chose. The table answers "does the budget hold"; this answers "what
// exactly was run", which is the question a surprising number invites.
func renderSamples(b *strings.Builder, r record) {
	b.WriteString("| measurement | p50 | p95 | p99 | budget | samples |\n")
	b.WriteString("|---|---|---|---|---|---|\n")
	for _, m := range r.Budgets {
		fmt.Fprintf(b, "| `%s` | %s | %s | %s | %s | %d |\n",
			m.Name, millis(m.P50Ms), millis(m.P95Ms), millis(m.P99Ms),
			millis(m.BudgetMs), m.Samples)
	}
	b.WriteString("\n")
}

// orUnknown renders a fact this process could not read. An empty cell would
// read as "nothing to say"; a machine always has a CPU.
func orUnknown(value string) string {
	if strings.TrimSpace(value) == "" {
		return "unknown"
	}
	return value
}

func memory(gib int) string {
	if gib <= 0 {
		return "unknown"
	}
	return fmt.Sprintf("%d GiB", gib)
}
