import { chromium } from "@playwright/test";
const OUT = "/tmp/claude-503/-Users-lars-develop-margince-poc-v1/76cc88ba-85c6-456d-b015-cf5d614c448d/scratchpad";
const ID = "01a0424b-0841-7304-9b04-f73ca156b3b2";
const b = await chromium.launch();
const p = await b.newContext({ viewport: { width: 1400, height: 1100 } }).then((c) => c.newPage());
await p.goto("http://localhost:8081", { waitUntil: "networkidle" });
await p.getByRole("textbox", { name: /email/i }).fill("admin@demo.test");
await p.locator("input[type=password]").fill("demo-password-123");
await p.getByRole("button", { name: /^sign in$/i }).click();
await p.waitForTimeout(2500);
await p.goto(`http://localhost:8081/#/contacts/${ID}/research`);
await p.reload({ waitUntil: "networkidle" });
await p.waitForTimeout(3000);
const txt = await p.locator("body").innerText();
console.log("@@@" + (txt.match(/Surfe[\s\S]{0,380}/)?.[0] ?? "NO SECTION"));
await p.screenshot({ path: `${OUT}/receipt2.png`, fullPage: true });
await b.close();
