// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package main

// The egress table: which tasks can send message text off this machine, and
// which cannot.
//
// Generated from the same contract the binary compiles, because the alternative
// is a hand-written page that says what somebody believed when they wrote it. A
// data-protection answer that disagrees with the routing table is worse than no
// page at all — the reader acts on it, and it is wrong in the direction of
// claiming more privacy than the product delivers.
//
// What makes a task local-only is its LADDER: a ladder naming only local rungs
// cannot reach a hosted provider whatever an operator binds. `no_payload` is a
// different promise — the prompt is not retained in ai_call_payload — and the
// table reports both, because a task can send text off the machine without
// storing it, and store it without sending it anywhere.

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
)

// localTiers are the rungs that run on the installation's own hardware. A
// ladder built only from these cannot leave the machine.
var localTiers = map[string]bool{"local_small": true, "local_large": true}

// emitEgressDoc renders the egress table for docs/reference/ai-egress.md.
func emitEgressDoc(c contract) []byte {
	names := make([]string, 0, len(c.Tasks))
	for name := range c.Tasks {
		names = append(names, name)
	}
	sort.Strings(names)

	var b bytes.Buffer
	b.WriteString(`<!-- Generated by tools/gen-aitasks. Do not edit by hand: run make gen. -->

# What leaves this machine

Every AI task this product declares, and whether the text it reads can reach a
provider outside the installation. Generated from ` + "`backend/api/ai-tasks.yaml`" + `,
so it says what the routing table does rather than what somebody believed when
they last wrote this page down.

Two different promises, and a task can make either without the other:

- **Stays local** — the task's ladder names only rungs that run on this
  installation's own hardware, so no binding an operator chooses can send its
  text to a hosted provider.
- **Prompt not retained** — the task declares ` + "`no_payload`" + `, so its prompt is
  never written to ` + "`ai_call_payload`" + ` whatever the deployment's capture posture
  says.

A task that is neither sends its text to whichever provider the operator bound
for its ladder's rungs, and may retain the prompt for debugging. That is the
ordinary case and is not a defect: it is the deployment's choice, stated here so
it can be answered for.

| Task | Ladder | Stays local | Prompt not retained | Status |
| --- | --- | --- | --- | --- |
`)
	for _, name := range names {
		def := c.Tasks[name]
		b.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s | %s |\n",
			name,
			ladderCell(def.Ladder),
			yesNo(staysLocal(def.Ladder)),
			yesNo(def.NoPayload),
			def.Status))
	}
	b.WriteString(`
## Reading this against a data-protection question

"Does our mail leave the building?" is answered by the **Stays local** column
for the tasks that read mail: ` + "`capture_classify`" + `, ` + "`capture_counterparty_verdict`" + `
and ` + "`capture_confidentiality_verdict`" + `. The last two decide whether a sender or a
thread is private, so sending their text away to ask would be the question
answering itself the wrong way round.

"Is a copy kept?" is the **Prompt not retained** column, and it is about this
installation's own database rather than about the provider. What a bound
provider retains is between the operator and that provider; the egress column
is what says whether there is a provider involved at all.
`)
	return b.Bytes()
}

// staysLocal reports whether every rung of a ladder runs on this machine.
//
// EVERY rung, not the first: a ladder falls through to its later rungs when an
// earlier one is unavailable or out of budget, so one hosted rung anywhere in
// it means the text can leave.
func staysLocal(ladder []string) bool {
	if len(ladder) == 0 {
		return false
	}
	for _, tier := range ladder {
		if !localTiers[tier] {
			return false
		}
	}
	return true
}

func ladderCell(ladder []string) string {
	if len(ladder) == 0 {
		return "—"
	}
	quoted := make([]string, len(ladder))
	for i, tier := range ladder {
		quoted[i] = "`" + tier + "`"
	}
	return strings.Join(quoted, " → ")
}

func yesNo(v bool) string {
	if v {
		return "yes"
	}
	return "no"
}
