// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package main

// The egress table: which tasks can send message text off this machine, and
// which cannot.
//
// Generated from the same contract the binary compiles, because the alternative
// is a hand-written page that says what somebody believed when they wrote it. A
// data-protection answer that disagrees with the routing table is worse than no
// page at all — the reader acts on it, and it is wrong in the direction of
// claiming more privacy than the product delivers.
//
// What makes a task local-only is its `local_only` declaration: the router
// drops every hosted rung from such a task's ladder under every profile. A
// ladder naming only local rungs is a weaker fact, because those rungs are size
// classes an operator may bind to a hosted provider. `no_payload` is a
// different promise again — the prompt is not retained in ai_call_payload — and
// the table reports each, because a task can send text off the machine without
// storing it, and store it without sending it anywhere.

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/margince/margince/backend/internal/platform/outbound"
)

// localTiers are the rungs meant to run on the installation's own hardware.
// A ladder built only from these stays put only where a binding cannot move
// them: under sovereign, or for a task that declares local_only.
var localTiers = map[string]bool{"local_small": true, "local_large": true}

// emitEgressDoc renders the egress table for docs/reference/ai-egress.md.
func emitEgressDoc(c contract) []byte {
	names := make([]string, 0, len(c.Tasks))
	for name := range c.Tasks {
		names = append(names, name)
	}
	sort.Strings(names)

	var b bytes.Buffer
	b.WriteString(egressIntro)
	for _, name := range names {
		def := c.Tasks[name]
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s | %s | %s |\n",
			name,
			ladderCell(def.Ladder),
			yesNo(staysLocal(def.Ladder)),
			yesNo(def.NoPayload),
			yesNo(def.LocalOnly),
			decisionCell(def),
			def.Status)
	}
	b.WriteString(egressReading)
	emitDisclosures(&b)
	return b.Bytes()
}

// decisionCell says which decision model a task's text can reach. A bound
// decisions lane serves every task that declares a decision form, wherever the
// lane's provider runs, except that a local-only task takes only a local
// decision provider.
func decisionCell(def taskDef) string {
	switch {
	case !def.Decision:
		return "—"
	case def.LocalOnly:
		return "only a local decision model"
	default:
		return "the bound decision model"
	}
}

// egressIntro is the page up to and including the table header.
const egressIntro = `<!-- Generated by tools/gen-aitasks. Do not edit by hand: run make gen. -->

# What leaves this machine

Every AI task this product declares, and whether the text it reads can reach a
provider outside the installation. Generated from ` + "`" + `backend/api/ai-tasks.yaml` + "`" + `,
so it says what the routing table does rather than what somebody believed when
they last wrote this page down.

Three different promises, and a task can make any of them without the others:

- **Local-only (enforced)** — the task declares ` + "`" + `local_only` + "`" + `, so its prompt is
  served only by a provider running on this installation, under every AI
  profile. At call time every rung bound to a hosted provider is dropped from
  the task's ladder, and a task left with no local rung is refused rather than
  sent out. This is the column that answers "can this text leave".
- **Local-only ladder** — the task's ladder names only rungs (` + "`" + `local_small` + "`" + `,
  ` + "`" + `local_large` + "`" + `) meant to run on this installation's own hardware. That is a
  fact about the LADDER'S NAMES, not a guarantee that text stays put: those
  rungs are size classes, and an operator's binding can point either at a
  hosted provider. Under ` + "`" + `sovereign` + "`" + ` validation refuses a cloud binding for
  either tier outright; under every other profile (` + "`" + `eu_hosted` + "`" + `,
  ` + "`" + `cloud_frontier` + "`" + `) only a task that ALSO declares ` + "`" + `local_only` + "`" + ` stays put.
  Read ` + "`" + `GET /v1/ai/routing` + "`" + ` for what a given deployment actually bound, and
  ` + "`" + `GET /v1/ai/profile` + "`" + ` for which rule applies to it.
- **Prompt not retained** — the task declares ` + "`" + `no_payload` + "`" + `, so its prompt is
  never written to ` + "`" + `ai_call_payload` + "`" + ` whatever the deployment's capture posture
  says.

The **Decision model** column is where else a task's text can go. A task that
declares a decision form may be answered first by the deployment's decision
model — the ` + "`" + `decisions:` + "`" + ` lane of the routing config, bound like the embeddings
lane — once that model is certified for the task's site. The lane's provider may
be a cloud one, so for an ordinary decision task the text reaches wherever the
lane is bound, even when the task's own ladder is bound locally. A task that
also declares ` + "`" + `local_only` + "`" + ` is asked only by a local decision provider; bound to
a cloud one, the lane skips it and the ladder answers. A "—" task is never sent
to a decision model. Under ` + "`" + `sovereign` + "`" + ` the lane must be a local provider on an
endpoint the installation controls, and under ` + "`" + `eu_hosted` + "`" + ` it may not reach
OpenRouter, whose decisions endpoint cannot be pinned to an EU host.

A task that is none of these sends its text to whichever provider the operator
bound for its ladder's rungs, and may retain the prompt for debugging. That is
the ordinary case and is not a defect: it is the deployment's choice, stated
here so it can be answered for.

| Task | Ladder | Local-only ladder | Prompt not retained | Local-only (enforced) | Decision model | Status |
| --- | --- | --- | --- | --- | --- | --- |
`

// egressReading follows the table: how to read it against a data-protection
// question.
const egressReading = `
## Reading this against a data-protection question

"Does our mail leave the building?" is answered for the tasks that read mail —
` + "`" + `capture_classify` + "`" + `, ` + "`" + `capture_counterparty_verdict` + "`" + ` and
` + "`" + `capture_confidentiality_verdict` + "`" + ` — by the **Local-only (enforced)** column.
The last two decide whether a sender or a thread is private, so sending their
text away to ask would be the question answering itself the wrong way round,
and both declare ` + "`" + `local_only` + "`" + `: their prompt reaches no hosted provider under
any profile, and no hosted decision model either.

The **Local-only ladder** column on its own does NOT answer the question — it
names the ladder's tiers, not what a deployment does with them. For a task
that does not declare ` + "`" + `local_only` + "`" + `, the AI profile decides: under ` + "`" + `sovereign` + "`" + `
a local-only ladder is enforced (validation refuses a cloud binding for it
outright); under ` + "`" + `eu_hosted` + "`" + ` or ` + "`" + `cloud_frontier` + "`" + ` an admin's own binding can
point ` + "`" + `local_small` + "`" + ` or ` + "`" + `local_large` + "`" + ` at a hosted provider, and the task then
leaves the machine. Read ` + "`" + `GET /v1/ai/profile` + "`" + ` for which rule applies to the
deployment in question, and ` + "`" + `GET /v1/ai/routing` + "`" + ` for what it actually bound —
never this page alone.

"Is a copy kept?" is the **Prompt not retained** column, and it is about this
installation's own database rather than about the provider. What a bound
provider retains is between the operator and that provider; the egress columns
are what say whether there is a provider involved at all.
`

// emitDisclosures writes the non-AI half: every other server this installation
// can be configured to call, and what it can send there.
//
// From platform/outbound rather than from a list kept here, because an outbound
// identity exists precisely when a call goes out under it — so the enumeration
// this page needs is the one the product already maintains to name itself.
// backend/gates/outbounddisclosures_test.go fails an identity with no entry,
// which is what stops this half going stale the way the page as a whole did:
// generated from the routing table alone, it answered for model providers and
// silently for nothing else, while being cited as the complete answer.
func emitDisclosures(b *bytes.Buffer) {
	all := outbound.Disclosures()
	sort.Slice(all, func(i, j int) bool { return all[i].Endpoint < all[j].Endpoint })

	b.WriteString(`
## Everything else this installation can call

The table above is the AI routing table and answers for model and embedding
providers. It is not the whole answer: a deployment can also be configured to
send a contact's name to a search index, a postal address to a geocoder, and a
URL to whatever host it names.

Those calls are listed here, one row per identity this product advertises when
it makes them. **Personal** says whether the request can carry personal data, so
a processing record can be written from the rows marked yes.

| Receives | Personal data | What it can see | How to prevent it |
|---|---|---|---|
`)
	for _, d := range all {
		category := d.Category
		if category == "" {
			category = "—"
		}
		control := d.Control
		if control == "" {
			control = "—"
		}
		fmt.Fprintf(b, "| %s | %s | %s | %s |\n", d.Endpoint, yesNo(d.Personal), category, control)
	}
	b.WriteString(`
A row here is what the installation CAN do, not what it does: most of these are
inert until an administrator supplies a credential or turns a setting on, and
the last column says which. Web search is the one worth naming twice — it sends
a contact's name to a third party, and it is off until somebody sets a key.
`)
}

// staysLocal reports whether every rung of a ladder runs on this machine.
//
// EVERY rung, not the first: a ladder falls through to its later rungs when an
// earlier one is unavailable or out of budget, so one hosted rung anywhere in
// it means the text can leave.
func staysLocal(ladder []string) bool {
	if len(ladder) == 0 {
		return false
	}
	for _, tier := range ladder {
		if !localTiers[tier] {
			return false
		}
	}
	return true
}

func ladderCell(ladder []string) string {
	if len(ladder) == 0 {
		return "—"
	}
	quoted := make([]string, len(ladder))
	for i, tier := range ladder {
		quoted[i] = "`" + tier + "`"
	}
	return strings.Join(quoted, " → ")
}

func yesNo(v bool) string {
	if v {
		return "yes"
	}
	return "no"
}
