// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package main

// The egress table: which tasks can send message text off this machine, and
// which cannot.
//
// Generated from the same contract the binary compiles, because the alternative
// is a hand-written page that says what somebody believed when they wrote it. A
// data-protection answer that disagrees with the routing table is worse than no
// page at all — the reader acts on it, and it is wrong in the direction of
// claiming more privacy than the product delivers.
//
// What makes a task local-only is its LADDER: a ladder naming only local rungs
// cannot reach a hosted provider whatever an operator binds. `no_payload` is a
// different promise — the prompt is not retained in ai_call_payload — and the
// table reports both, because a task can send text off the machine without
// storing it, and store it without sending it anywhere.

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
)

// localTiers are the rungs that run on the installation's own hardware. A
// ladder built only from these cannot leave the machine.
var localTiers = map[string]bool{"local_small": true, "local_large": true}

// emitEgressDoc renders the egress table for docs/reference/ai-egress.md.
func emitEgressDoc(c contract) []byte {
	names := make([]string, 0, len(c.Tasks))
	for name := range c.Tasks {
		names = append(names, name)
	}
	sort.Strings(names)

	var b bytes.Buffer
	b.WriteString(`<!-- Generated by tools/gen-aitasks. Do not edit by hand: run make gen. -->

# What leaves this machine

Every AI task this product declares, and whether the text it reads can reach a
provider outside the installation. Generated from ` + "`backend/api/ai-tasks.yaml`" + `,
so it says what the routing table does rather than what somebody believed when
they last wrote this page down.

Two different promises, and a task can make either without the other:

- **Local-only ladder** — the task's ladder names only rungs (` + "`local_small`" + `,
  ` + "`local_large`" + `) meant to run on this installation's own hardware. That is a
  fact about the LADDER'S NAMES, not a guarantee that text stays put: whether
  it is enforced depends on the deployment's AI profile. Under ` + "`sovereign`" + `
  it is enforced — validation refuses a cloud binding for either tier
  outright, so no cloud client for one is ever constructed. Under every OTHER
  profile (` + "`eu_hosted`" + `, ` + "`cloud_frontier`" + `) it is unenforced: an operator's
  own binding can point ` + "`local_small`" + ` or ` + "`local_large`" + ` at a hosted
  provider, and a task with a local-only ladder then leaves the machine
  anyway. Read ` + "`GET /v1/ai/routing`" + ` for what a given deployment actually
  bound, and ` + "`GET /v1/ai/profile`" + ` for which of the two rules applies to it.
- **Prompt not retained** — the task declares ` + "`no_payload`" + `, so its prompt is
  never written to ` + "`ai_call_payload`" + ` whatever the deployment's capture posture
  says.

A task that is neither sends its text to whichever provider the operator bound
for its ladder's rungs, and may retain the prompt for debugging. That is the
ordinary case and is not a defect: it is the deployment's choice, stated here so
it can be answered for.

| Task | Ladder | Local-only ladder | Prompt not retained | Status |
| --- | --- | --- | --- | --- |
`)
	for _, name := range names {
		def := c.Tasks[name]
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s |\n",
			name,
			ladderCell(def.Ladder),
			yesNo(staysLocal(def.Ladder)),
			yesNo(def.NoPayload),
			def.Status)
	}
	b.WriteString(`
## Reading this against a data-protection question

"Does our mail leave the building?" needs TWO facts, not one, for the tasks
that read mail: ` + "`capture_classify`" + `, ` + "`capture_counterparty_verdict`" + ` and
` + "`capture_confidentiality_verdict`" + `. The last two decide whether a sender or a
thread is private, so sending their text away to ask would be the question
answering itself the wrong way round.

The **Local-only ladder** column is the first fact and, on its own, does NOT
answer the question — it names the ladder's tiers, not what a deployment does
with them. The second fact is the AI profile: under ` + "`sovereign`" + `, a local-only
ladder is enforced (validation refuses a cloud binding for it outright) and
the column's "yes" is a real guarantee. Under ` + "`eu_hosted`" + ` or
` + "`cloud_frontier`" + `, it is not — an admin's own binding can point ` + "`local_small`" + `
or ` + "`local_large`" + ` at a hosted provider, and a "yes" task then leaves the
machine anyway. Read ` + "`GET /v1/ai/profile`" + ` for which rule applies to the
deployment in question, and ` + "`GET /v1/ai/routing`" + ` for what it actually bound
— never this page alone.

"Is a copy kept?" is the **Prompt not retained** column, and it is about this
installation's own database rather than about the provider. What a bound
provider retains is between the operator and that provider; the egress column
is what says whether there is a provider involved at all.
`)
	return b.Bytes()
}

// staysLocal reports whether every rung of a ladder runs on this machine.
//
// EVERY rung, not the first: a ladder falls through to its later rungs when an
// earlier one is unavailable or out of budget, so one hosted rung anywhere in
// it means the text can leave.
func staysLocal(ladder []string) bool {
	if len(ladder) == 0 {
		return false
	}
	for _, tier := range ladder {
		if !localTiers[tier] {
			return false
		}
	}
	return true
}

func ladderCell(ladder []string) string {
	if len(ladder) == 0 {
		return "—"
	}
	quoted := make([]string, len(ladder))
	for i, tier := range ladder {
		quoted[i] = "`" + tier + "`"
	}
	return strings.Join(quoted, " → ")
}

func yesNo(v bool) string {
	if v {
		return "yes"
	}
	return "no"
}
