// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package main

// The outage table: what each task does while a provider it needs is down,
// out of credit or refusing its key.
//
// Generated from the contract for the reason the egress table is: what a task
// does in an outage follows from its declared execution mode and budget
// posture, and a hand-kept list says what somebody believed the day they wrote
// it. The mechanism behind every row is docs/explanation/ai-provider-health.md.

import (
	"bytes"
	"fmt"
)

// emitOutageDoc renders docs/reference/ai-provider-outages.md.
func emitOutageDoc(c contract) []byte {
	var b bytes.Buffer
	b.WriteString(outageIntro)
	for _, name := range c.sortedTaskNames() {
		def := c.Tasks[name]
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s | %s |\n",
			name,
			def.DisplayName,
			def.ExecutionMode,
			ladderCell(def.Ladder),
			outageCell(def),
			decisionOutageCell(def))
	}
	fmt.Fprintf(&b, "| embeddings (`%s` lane) | Search and retrieval | embedding | `%s` | %s | — |\n",
		c.Embed.Tier, c.Embed.Tier, embedOutage)
	b.WriteString(outageReading)
	return b.Bytes()
}

// outageCell is what happens once EVERY rung's provider refuses calls. It keys
// on the execution mode, which validate.go holds to exactly one budget
// posture. A planned task makes no calls, so it has no outage to describe.
func outageCell(def taskDef) string {
	switch {
	case def.Status == statusPlanned:
		return "not in use yet"
	case def.ExecutionMode == "background":
		return "waits for the provider's next check; the attempt is not spent"
	default:
		return "fails at once with a 503 naming the cause"
	}
}

func decisionOutageCell(def taskDef) string {
	if !def.Decision {
		return "—"
	}
	return "a failed decision call hands the task to its ladder"
}

const embedOutage = "refused untraced; search reindex retries on its own schedule"

// outageIntro is the page up to and including the table header.
const outageIntro = `<!-- Generated by tools/gen-aitasks. Do not edit by hand: run make gen. -->

# What each AI task does while its provider is down

Generated from ` + "`" + `backend/api/ai-tasks.yaml` + "`" + `. A provider is **blocked** while it
is ` + "`" + `down` + "`" + `, ` + "`" + `out_of_credit` + "`" + ` or ` + "`" + `unauthorized` + "`" + `; ` + "`" + `degraded` + "`" + ` still takes calls and blocks
nothing. How a provider gets each status, and how it clears, is
[ai-provider-health.md](../explanation/ai-provider-health.md).

Three rules decide every row:

- **A blocked rung is skipped with no call.** A task whose ladder has another
  rung on a provider that still answers is served by that rung, so one
  provider's outage costs it nothing but the model it would have used.
- **A fully blocked ladder** is what the outage column describes. A background
  task then returns a deferral to the carrier that owns its work. The item
  waits until the provider's next check and its attempt is refunded, so an
  outage never parks mail as unsure or burns an enrichment's retries. An
  interactive task fails fast with ` + "`" + `provider_unavailable` + "`" + `,
  ` + "`" + `provider_out_of_credit` + "`" + ` or ` + "`" + `provider_unauthorized` + "`" + `, telling the user to
  contact their administrator.
- **A decision model** is tried first and never waited on. If its call fails,
  the task's own ladder answers.

Each process blocks a provider on what its own calls saw: the API and the
worker each learn an outage from their own failures. The status they share is
for display, so Settings → System health lists a provider either one found
blocked.

Settings → AI models shows it per row. The dot before a task's name turns red
when every model on its ladder is blocked. It also turns red while the task
waits on the allowance or has no model bound. The task's name opens what it
does in this state.

| Task | Name | Mode | Ladder | Every rung blocked | Decision model |
| --- | --- | --- | --- | --- | --- |
`

const outageReading = `
## After the outage

Work that waited resumes by itself at the provider's next check; raising the AI
allowance does not hasten it, because the allowance was never what stopped it.
Work that spent its attempts before the provider was marked blocked (the
calls that tripped it) is reopened by hand:
[recover-after-a-provider-outage.md](../how-to/recover-after-a-provider-outage.md).
`
