// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

// The ratified cross-store writes, held apart from the walker that consults
// them: this file is the hand-maintained artifact and tableownership_test.go is
// the mechanism, and the two change for different reasons. It declares no test,
// so it is data rather than a ninth gate shape.

package backendarch

import "github.com/gradionhq/margince/backend/internal/shared/gatekit"

// crossStoreWrites are the ratified writes outside the writer's own tables,
// keyed "module-dir:table". Every entry carries its rationale inline so the
// gate is self-contained on a clean checkout.
var crossStoreWrites = gatekit.Waive(map[string]string{
	// people's merge/promotion relink rows across aggregates inside their
	// single transaction — the primary aggregate owns the single-tx
	// cross-aggregate write, because a merge that could half-commit its
	// relinks would corrupt referential history.
	"internal/modules/people:deal:merge_organization.go:absorbOrgReferences":                  "merge/promote relink deal FK rows in the single transaction",
	"internal/modules/people:project:merge_organization.go:absorbOrgReferences":               "org merge re-anchors the merged-away company's projects onto the survivor in the same transaction (PROJ-LIFE-4) — the anchor is NOT NULL ... ON DELETE RESTRICT, so a project cannot stay behind, and leaving it turns the survivor's deals un-editable against the deal_project_same_org trigger",
	"internal/modules/people:activity_link:ensure.go:linkActivityToPerson":                    "merge/promote relink timeline links in the single transaction",
	"internal/modules/people:activity_link:leadmerge.go:carryLeadActivitiesToLead":            "merge/promote relink timeline links in the single transaction",
	"internal/modules/people:activity_link:merge.go:relinkLinkRows":                           "merge/promote relink timeline links in the single transaction",
	"internal/modules/people:activity_link:promote.go:carryLeadActivities":                    "merge/promote relink timeline links in the single transaction",
	"internal/modules/people:attachment:merge_organization.go:absorbOrgReferences":            "org merge carries the document library's account pointer onto the survivor in the same transaction — organization_id is a denormalized READ path nothing else maintains, so a file left on the dissolved company is filed under a record that no longer exists and reads to a user as the contract having vanished",
	"internal/modules/people:activity_participant:participant.go:namePersonAmongParticipants": "capture records the counterparty by ADDRESS because no person exists yet — the creation gate runs after that transaction commits, and for a suppressed sender never runs at all. linkActivityToPerson is the one chokepoint every ensure path reaches AND the one that has already settled the person against a merge, so naming that party is the same write, on the same row, in the same transaction as the link",
	"internal/modules/people:list_member:organizationarchive.go:ArchiveOrganization":          "merge relinks list memberships (and archive purges them) in the single transaction",
	"internal/modules/people:list_member:personarchive.go:archivePersonRows":                  "merge relinks list memberships (and archive purges them) in the single transaction",
	"internal/modules/people:taggable:organizationarchive.go:ArchiveOrganization":             "merge relinks tag rows (and archive purges them) in the single transaction",
	"internal/modules/people:taggable:personarchive.go:archivePersonRows":                     "merge relinks tag rows (and archive purges them) in the single transaction",
	"internal/modules/people:person_consent:consentcarry.go:dropCollidingConsent":             "merge carries the survivor's consent state in the single transaction",
	"internal/modules/people:person_consent:consentcarry.go:flipCarriedWithdrawals":           "merge carries the survivor's consent state in the single transaction",
	"internal/modules/people:person_consent:consentcarry.go:repointCarriedConsent":            "merge carries the survivor's consent state in the single transaction",
	"internal/modules/people:consent_event:consentcarry.go:carryConsent":                      "merge re-points the append-only consent proof log in the single transaction",
	"internal/modules/people:consent_event:consentcarry.go:flipCarriedWithdrawals":            "merge re-points the append-only consent proof log in the single transaction",
	// The outbound-send reconcile folds the provider's own captured echo of a
	// message this workspace sent into the send's own row. That fold is one
	// indivisible act — links copied, review moved, key released, row archived
	// — run in one best-effort transaction the delivery store may roll back
	// whole. The queued counterparty review is part of it: a human verdict the
	// survivor does not re-queue, which must not be left asking about a message
	// the workspace can no longer see.
	"internal/modules/activities:capture_pending_counterparty:messageidentity.go:repointEchoReviews": "the message-identity absorb re-points the archived echo's queued counterparty dispositions onto the surviving send, in the same transaction as the rest of the fold — a sibling call would have to write on this very transaction anyway, so routing it through capture would buy a hop and no isolation, while splitting the fold across two owners would let half of it survive a rollback",
	// capture is the ONE connector.Sink (interfaces.md §1): one transaction
	// per inbound record writes raw original + normalized domain row, so a
	// crash can never keep evidence without the record or vice versa.
	"internal/modules/capture:activity:sink.go:upsertActivity":                              "the connector sink materializes the normalized activity in the same transaction as its raw_capture original",
	"internal/modules/capture:activity:sinkaudience.go:limitLinkLessAudience":               "the connector sink materializes the normalized activity in the same transaction as its raw_capture original",
	"internal/modules/capture:activity:sinkproject.go:linkActivityToProject":                "the connector sink materializes the normalized activity in the same transaction as its raw_capture original",
	"internal/modules/capture:activity_link:sink.go:linkActivity":                           "the connector sink links the materialized activity in the same ingest transaction",
	"internal/modules/capture:activity_link:sinkproject.go:linkActivityToProject":           "the connector sink links the materialized activity in the same ingest transaction",
	"internal/modules/capture:activity_participant:participant.go:StampFurtherParticipants": "the connector principal is the ONLY place the mailbox owner is known (capture_connection is per-user-per-provider); by the time any other module sees the activity its captured_by reads connector:gmail and the human behind it is unrecoverable, so the participant rows commit in the same ingest transaction as the activity they describe",
	"internal/modules/capture:activity_participant:participant.go:insertParticipant":        "the connector principal is the ONLY place the mailbox owner is known (capture_connection is per-user-per-provider); by the time any other module sees the activity its captured_by reads connector:gmail and the human behind it is unrecoverable, so the participant rows commit in the same ingest transaction as the activity they describe",
	"internal/modules/capture:lead:sinklead.go:upsertLead":                                  "the connector sink materializes inbound leads in the same transaction as their raw_capture original",
	// deals' archive purges the archived deal's collection memberships in
	// the same transaction — a dangling list/tag row would resurrect the
	// deal in segment queries.
	"internal/modules/deals:list_member:dealarchive.go:ArchiveDeal":  "archiving a deal removes its list memberships in the archive transaction",
	"internal/modules/deals:taggable:dealarchive.go:ArchiveDeal":     "archiving a deal removes its tag rows in the archive transaction",
	"internal/modules/deals:relationship:dealarchive.go:ArchiveDeal": "archiving a deal archives its stakeholder relationships in the archive transaction — a live relationship to an archived deal would leak it into row-scope walks",
	// The project's archive carries the same three, for the same reasons: the
	// edges are attributes of the grouping being archived, and each must go in
	// the SAME transaction or a reader sees a live edge to a record that no
	// longer exists.
	"internal/modules/projects:list_member:project.go:ArchiveProject":  "archiving a project removes its list memberships in the archive transaction",
	"internal/modules/projects:taggable:project.go:ArchiveProject":     "archiving a project removes its tag rows in the archive transaction",
	"internal/modules/projects:relationship:project.go:ArchiveProject": "archiving a project archives its stakeholder relationships in the archive transaction — a live relationship to an archived project would leak it into row-scope walks",
	// privacy is the module whose JOB is crossing stores: a data-subject
	// obligation (erasure Art. 17, retention ADR-0011) must reach every
	// table holding the subject in ONE transaction per record — the
	// sanctioned single-transaction exception; routing each purge
	// through the owning module's API would trade the atomicity that IS
	// the guarantee for boundary hygiene.
	"internal/modules/privacy:person:erasure.go:anonymizeSubjectRows":                                   "erasure/retention anonymize the person row in place in the single erasure transaction (Art. 17)",
	"internal/modules/privacy:person:retentionactions.go:anonymizePersonRecord":                         "erasure/retention anonymize the person row in place in the single erasure transaction (Art. 17)",
	"internal/modules/privacy:deal_room_participant:erasuredealroom.go:anonymizeDealRoomSeats":          "erasure anonymizes the subject's Deal Room seat in place — the one named outside person stored without a person row — in the single erasure transaction",
	"internal/modules/privacy:deal_room_session:erasuredealroom.go:purgeDealRoomSeatTraces":             "erasure deletes the erased subject's live room credentials in the same transaction: access they did not consent to keep must not outlive the request",
	"internal/modules/privacy:deal_room_engagement:erasuredealroom.go:purgeDealRoomSeatTraces":          "erasure deletes the erased subject's room activity trail (when they signed in, what they took) in the same transaction",
	"internal/modules/privacy:person_email:erasure.go:deleteSubjectIdentifierRows":                      "erasure deletes the subject's email channel rows in the single erasure transaction",
	"internal/modules/privacy:person_email:retentionactions.go:anonymizePersonRecord":                   "erasure deletes the subject's email channel rows in the single erasure transaction",
	"internal/modules/privacy:preference_token:erasure_consent.go:deleteConsentCapabilities":            "erasure deletes the subject's preference-center token in the single erasure transaction — it is a live capability over their consent record on a session-less edge, and anonymize-in-place means 0048's ON DELETE CASCADE never fires, so an erased subject would keep accruing consent rows through the capability the erasure certifies destroyed",
	"internal/modules/privacy:consent_doi_token:erasure_consent.go:deleteConsentCapabilities":           "erasure deletes the subject's double-opt-in token in the same transaction and for the same reason as the preference-center token beside it — a bearer secret in their mailbox whose only function is to authorise a grant, which anonymize-in-place would otherwise leave live for its full 72 hours after the erasure certified the data destroyed",
	"internal/modules/privacy:consent_doi_token:retentionactions.go:anonymizePersonRecord":              "erasure deletes the subject's double-opt-in token in the same transaction and for the same reason as the preference-center token beside it — a bearer secret in their mailbox whose only function is to authorise a grant, which anonymize-in-place would otherwise leave live for its full 72 hours after the erasure certified the data destroyed",
	"internal/modules/privacy:activity_participant:erasure_graph.go:<package-level>":                    "erasure nulls the subject's person and address arms on the interaction participants in the single erasure transaction — the address arm exists precisely for a party who never became a record, so it survives the person_email purge and would keep the erased address readable and re-matchable; the ROW is kept where other participants remain, because the other people in that conversation are not the subject",
	"internal/modules/privacy:activity_participant:retention_graph.go:scrubPersonGraphTraces":           "erasure nulls the subject's person and address arms on the interaction participants in the single erasure transaction — the address arm exists precisely for a party who never became a record, so it survives the person_email purge and would keep the erased address readable and re-matchable; the ROW is kept where other participants remain, because the other people in that conversation are not the subject",
	"internal/modules/identity:linkedin_connection:users.go:revokeBorrowedAuthority":                    "deactivation deletes the departing user's imported LinkedIn network in the single deactivation transaction — it is their private address book of third parties whose only tie to this installation was that person's employment, so it cannot outlive the employment; doing it here keeps it atomic with the session and passport revocation rather than leaving a window in which the account is gone and the address book is not",
	"internal/modules/privacy:linkedin_connection:erasure_graph.go:deleteSubjectLinkedInGhosts":         "erasure deletes the subject's LinkedIn ghosts in the single erasure transaction — a ghost holds the subject's name, employer and address, imported from a colleague's export without the subject ever being asked, and it is invisible to every person-keyed clause because a ghost is not a person row",
	"internal/modules/privacy:linkedin_connection:retention_graph.go:scrubPersonGraphTraces":            "erasure deletes the subject's LinkedIn ghosts in the single erasure transaction — a ghost holds the subject's name, employer and address, imported from a colleague's export without the subject ever being asked, and it is invisible to every person-keyed clause because a ghost is not a person row",
	"internal/modules/privacy:graph_interaction_edge:erasure_graph.go:deleteSubjectInteractionEdges":    "erasure drops the subject's interaction edges in the single erasure transaction rather than leaving it to the cg:graph-edge consumer — an Art. 17 obligation discharged by an event is one that fails silently when the bus is behind, and the projection holds who corresponded with the subject, how often and how recently",
	"internal/modules/privacy:graph_interaction_edge:retention_graph.go:scrubPersonGraphTraces":         "erasure drops the subject's interaction edges in the single erasure transaction rather than leaving it to the cg:graph-edge consumer — an Art. 17 obligation discharged by an event is one that fails silently when the bus is behind, and the projection holds who corresponded with the subject, how often and how recently",
	"internal/modules/privacy:capture_pending_counterparty:erasure.go:deleteSubjectIdentifierRows":      "erasure drops the capture dispositions keyed on the subject's own address in the single erasure transaction — left behind, they would keep the erased address readable and still answering the capture gates",
	"internal/modules/privacy:capture_pending_counterparty:retentionactions.go:anonymizePersonRecord":   "erasure drops the capture dispositions keyed on the subject's own address in the single erasure transaction — left behind, they would keep the erased address readable and still answering the capture gates",
	"internal/modules/privacy:person_social:erasure.go:deleteSubjectIdentifierRows":                     "erasure and retention delete the subject's social-handle rows in the same anonymization transaction",
	"internal/modules/privacy:person_social:retentionactions.go:anonymizePersonRecord":                  "erasure and retention delete the subject's social-handle rows in the same anonymization transaction",
	"internal/modules/privacy:voice_learning_signal:retentionai.go:eraseVoiceSignalContent":             "the nightly retention sweep erases over-age draft plaintext in place; the counters row survives (voice_draftread.go stamps the per-row deadline)",
	"internal/modules/privacy:person_phone:erasure.go:deleteSubjectIdentifierRows":                      "erasure deletes the subject's phone channel rows in the single erasure transaction",
	"internal/modules/privacy:person_phone:retentionactions.go:anonymizePersonRecord":                   "erasure deletes the subject's phone channel rows in the single erasure transaction",
	"internal/modules/privacy:person_channel_identity:erasure_channels.go:eraseChannelIdentities":       "erasure and the retention anonymizer delete the subject's channel-identity rows in the single erasure/per-record transaction — the identity is the key an inbound message would re-bind them by, so it has to go in the same commit that hashes it onto the suppression list",
	"internal/modules/privacy:person_channel_identity:retentionactions.go:anonymizePersonRecord":        "erasure and the retention anonymizer delete the subject's channel-identity rows in the single erasure/per-record transaction — the identity is the key an inbound message would re-bind them by, so it has to go in the same commit that hashes it onto the suppression list",
	"internal/modules/privacy:lead:erasure.go:anonymizeLeadTwins":                                       "erasure/retention anonymize the subject's segregated lead rows in the same transaction",
	"internal/modules/privacy:lead:retentionactions.go:anonymizeLead":                                   "erasure/retention anonymize the subject's segregated lead rows in the same transaction",
	"internal/modules/privacy:lead_score_history:erasure.go:anonymizeLeadTwins":                         "the score's explanation is about the subject: its factors embed the ids of activities they took part in, inside JSON no field-level scrub reaches, and the lead is ANONYMIZED rather than deleted so nothing cascades",
	"internal/modules/privacy:lead_score_history:retentionactions.go:anonymizeLead":                     "the score's explanation is about the subject: its factors embed the ids of activities they took part in, inside JSON no field-level scrub reaches, and the lead is ANONYMIZED rather than deleted so nothing cascades",
	"internal/modules/privacy:lead_manual_signal:erasure.go:anonymizeLeadTwins":                         "a manual scoring signal is a colleague's written judgement about the subject, carrying their name — it cannot outlive the record it judges, and the anonymize fires no cascade",
	"internal/modules/privacy:lead_manual_signal:retentionactions.go:anonymizeLead":                     "a manual scoring signal is a colleague's written judgement about the subject, carrying their name — it cannot outlive the record it judges, and the anonymize fires no cascade",
	"internal/modules/privacy:activity:erasure_restrict.go:restrictShieldedTimeline":                    "retention archives/erases over-age timeline rows, and Art. 17 erasure redacts subject-only activity subject/body — or, for a Handelsbrief inside its statutory window, restricts the row and redacts its identifiers — in the single erasure/per-record transaction; the expiry sweep completes the suspended erasure when the window closes",
	"internal/modules/privacy:activity:erasure_restrict.go:stampLegacyHandelsbriefe":                    "retention archives/erases over-age timeline rows, and Art. 17 erasure redacts subject-only activity subject/body — or, for a Handelsbrief inside its statutory window, restricts the row and redacts its identifiers — in the single erasure/per-record transaction; the expiry sweep completes the suspended erasure when the window closes",
	"internal/modules/privacy:activity:erasuretimeline.go:redactSubjectTimeline":                        "retention archives/erases over-age timeline rows, and Art. 17 erasure redacts subject-only activity subject/body — or, for a Handelsbrief inside its statutory window, restricts the row and redacts its identifiers — in the single erasure/per-record transaction; the expiry sweep completes the suspended erasure when the window closes",
	"internal/modules/privacy:activity:restrictionoverride.go:PinToFloor":                               "retention archives/erases over-age timeline rows, and Art. 17 erasure redacts subject-only activity subject/body — or, for a Handelsbrief inside its statutory window, restricts the row and redacts its identifiers — in the single erasure/per-record transaction; the expiry sweep completes the suspended erasure when the window closes",
	"internal/modules/privacy:activity:retentionactions.go:archiveActivity":                             "retention archives/erases over-age timeline rows, and Art. 17 erasure redacts subject-only activity subject/body — or, for a Handelsbrief inside its statutory window, restricts the row and redacts its identifiers — in the single erasure/per-record transaction; the expiry sweep completes the suspended erasure when the window closes",
	"internal/modules/privacy:activity:retentionactions.go:eraseActivityContent":                        "retention archives/erases over-age timeline rows, and Art. 17 erasure redacts subject-only activity subject/body — or, for a Handelsbrief inside its statutory window, restricts the row and redacts its identifiers — in the single erasure/per-record transaction; the expiry sweep completes the suspended erasure when the window closes",
	"internal/modules/privacy:activity:retentionrestricted.go:liftAndEraseHeldRecord":                   "retention archives/erases over-age timeline rows, and Art. 17 erasure redacts subject-only activity subject/body — or, for a Handelsbrief inside its statutory window, restricts the row and redacts its identifiers — in the single erasure/per-record transaction; the expiry sweep completes the suspended erasure when the window closes",
	"internal/modules/privacy:activity_retention_evidence:erasure_restrict.go:stampLegacyHandelsbriefe": "Art. 17 erasure stamps a Handelsbrief captured before the stamp writer existed, and writes the evidence its restriction rests on, in the single erasure transaction — the guard refuses a restriction with no evidence behind it, and for a pre-stamp row the deal links the erasure reads are the only evidence there is",
	"internal/modules/privacy:activity_retention_evidence:restrictionoverride.go:recordPinEvidence":     "Art. 17 erasure stamps a Handelsbrief captured before the stamp writer existed, and writes the evidence its restriction rests on, in the single erasure transaction — the guard refuses a restriction with no evidence behind it, and for a pre-stamp row the deal links the erasure reads are the only evidence there is",
	"internal/modules/privacy:attachment:erasure_attachments.go:eraseAttachments":                       "Art. 17 erasure deletes attachments hung off the subject or a subject-only activity in the single erasure transaction",
	"internal/modules/privacy:deal:retentionactions.go:archiveDeal":                                     "retention archives over-age lost deals per its audited per-record transaction",
	"internal/modules/privacy:embedding:erasure.go:purgePersonDerivedRows":                              "erasure/retention purge the subject's vectors — a similarity probe must not reconstruct erased text",
	"internal/modules/privacy:embedding:erasure.go:purgeRedactedActivityTraces":                         "erasure/retention purge the subject's vectors — a similarity probe must not reconstruct erased text",
	"internal/modules/privacy:embedding:erasure_restrict.go:holdShieldedTimeline":                       "erasure/retention purge the subject's vectors — a similarity probe must not reconstruct erased text",
	"internal/modules/privacy:embedding:erasuretimeline.go:<package-level>":                             "erasure/retention purge the subject's vectors — a similarity probe must not reconstruct erased text",
	"internal/modules/privacy:embedding:restrictionoverride.go:pinnedRecordLeavesDerivedCopies":         "erasure/retention purge the subject's vectors — a similarity probe must not reconstruct erased text",
	"internal/modules/privacy:embedding:retentionactions.go:anonymizeLead":                              "erasure/retention purge the subject's vectors — a similarity probe must not reconstruct erased text",
	"internal/modules/privacy:embedding:retentionactions.go:anonymizePersonRecord":                      "erasure/retention purge the subject's vectors — a similarity probe must not reconstruct erased text",
	"internal/modules/privacy:embedding:retentionactions.go:eraseActivityContent":                       "erasure/retention purge the subject's vectors — a similarity probe must not reconstruct erased text",
	"internal/modules/privacy:embedding:retentionrestricted.go:purgeHeldRecordTraces":                   "erasure/retention purge the subject's vectors — a similarity probe must not reconstruct erased text",
	"internal/modules/activities:embedding:capturenoise.go:RedactCapturedNoiseTx":                       "the ADR-0072 noise redaction drops the vectors built from the mail it just nulled, in the same transaction — an embedding of redacted text is that text in another shape, and leaving it would let a similarity probe reconstruct what the workspace decided not to retain. Same obligation as the privacy waiver above, at the other place content is destroyed; the embed lane cannot do it itself because it never observes an archived row",
	"internal/modules/privacy:capture_trace:erasuretimeline.go:purgeDerivedTraces":                      "erasure deletes the subject's rows from the 24-hour capture trace in the single erasure transaction, beside raw_capture and ai_call_payload above. The trace's sweep bounds exposure to a day; it does not ANSWER a request made inside that day, and an erasure honoured everywhere except one diagnostic table is not honoured. Only the payload columns can name anybody, and only when the deployment enabled capture.trace_payloads — on the default posture this statement matches nothing, which is the correct amount of work for a table holding no identifiers. Exact equality rather than the ILIKE its neighbours use, because this column is written normalized and indexed",
	"internal/modules/privacy:raw_capture:erasure_channels.go:purgeChannelRawCapture":                   "erasure purges raw provider payloads carrying the subject's identifiers in the single erasure transaction",
	"internal/modules/privacy:raw_capture:erasuretimeline.go:purgeDerivedTraces":                        "erasure purges raw provider payloads carrying the subject's identifiers in the single erasure transaction",
	"internal/modules/privacy:person_profile_field:erasure.go:purgePersonDerivedRows":                   "Art. 17 and the retention sweep delete the subject's enrichment sidecar inside the single erasure transaction, beside field_provenance and ai_feedback: anonymize-in-place leaves the person row standing, so nothing cascades here, and the row holds the subject's title and employer with the verbatim sentence naming them",
	"internal/modules/privacy:person_profile_field:retentionactions.go:anonymizePersonRecord":           "Art. 17 and the retention sweep delete the subject's enrichment sidecar inside the single erasure transaction, beside field_provenance and ai_feedback: anonymize-in-place leaves the person row standing, so nothing cascades here, and the row holds the subject's title and employer with the verbatim sentence naming them",
	"internal/modules/privacy:person_provider_claim:erasure_provider.go:purgeProviderPurchases":         "Art. 17 and the retention sweep delete what a licensed data provider asserted about the subject, inside the single erasure transaction and for the same reason person_profile_field is here: anonymize-in-place leaves the person row standing, so nothing cascades, and a claim IS the purchased value — a bought email and employer would otherwise sit on the page beside an \"Erased Subject\" name. Deleted rather than nulled, because a claim nulled in place is a row asserting something about a person nobody may now assert anything about",
	"internal/modules/privacy:person_provider_claim:retentionactions.go:anonymizePersonRecord":          "Art. 17 and the retention sweep delete what a licensed data provider asserted about the subject, inside the single erasure transaction and for the same reason person_profile_field is here: anonymize-in-place leaves the person row standing, so nothing cascades, and a claim IS the purchased value — a bought email and employer would otherwise sit on the page beside an \"Erased Subject\" name. Deleted rather than nulled, because a claim nulled in place is a row asserting something about a person nobody may now assert anything about",
	"internal/modules/privacy:provider_run:erasure_provider.go:purgeProviderPurchases":                  "the same two paths scrub the runs that bought that data, using storekit.ScrubProviderRunColumns — the SAME six-column clause integrations' own delete-data action uses, shared precisely because the two drifted once and the erasure cleaned less than the settings toggle did. It is a scrub and not a delete on purpose: the row stops naming anybody while the spend it records survives, because what the installation paid is an accounting fact about the installation once it names no one (PI-AC-8), and that is what keeps a spend history stable across an erasure",
	"internal/modules/privacy:provider_run:retentionactions.go:anonymizePersonRecord":                   "the same two paths scrub the runs that bought that data, using storekit.ScrubProviderRunColumns — the SAME six-column clause integrations' own delete-data action uses, shared precisely because the two drifted once and the erasure cleaned less than the settings toggle did. It is a scrub and not a delete on purpose: the row stops naming anybody while the spend it records survives, because what the installation paid is an accounting fact about the installation once it names no one (PI-AC-8), and that is what keeps a spend history stable across an erasure",
	"internal/modules/people:provider_run:mergerelink.go:relinkProviderPurchases":                       "the person merge relinks the merged-away record's runs onto the survivor, and must decide the collision between two live runs where the unique index admits only one. It happens inside the merge transaction because that is the only place both person ids and both sides' run states are known at once; integrations cannot see a merge and people cannot hand the decision over mid-transaction. The write touches person_id, state and input_fingerprint only — never a reservation, never a credit — and the rule it enforces is integrations' own: a run past `queued` may have been paid for, so it is re-fingerprinted out of the live-run index rather than cancelled, the same idiom markSkipped uses",
	"internal/modules/privacy:ai_feedback:erasure.go:anonymizeLeadTwins":                                "Art. 17 deletes the subject's correction ledger inside the single erasure transaction, exactly as it does field_provenance beside it: the ledger holds a human-typed value ABOUT the subject, and a claim nobody may now assert anything about has nothing left to suppress",
	"internal/modules/privacy:ai_feedback:erasure.go:purgePersonDerivedRows":                            "Art. 17 deletes the subject's correction ledger inside the single erasure transaction, exactly as it does field_provenance beside it: the ledger holds a human-typed value ABOUT the subject, and a claim nobody may now assert anything about has nothing left to suppress",
	"internal/modules/privacy:ai_feedback:retentionactions.go:anonymizePersonRecord":                    "Art. 17 deletes the subject's correction ledger inside the single erasure transaction, exactly as it does field_provenance beside it: the ledger holds a human-typed value ABOUT the subject, and a claim nobody may now assert anything about has nothing left to suppress",
	"internal/modules/privacy:ai_call_payload:erasuretimeline.go:purgeDerivedTraces":                    "erasure purges captured AI payloads mentioning the subject's identifiers, and retention ages every payload out at 365d — the special-category-adjacent content, deleted in the single erasure/per-record transaction while the ai_call metadata row survives",
	"internal/modules/privacy:ai_call_payload:retentionactions.go:erasePayload":                         "erasure purges captured AI payloads mentioning the subject's identifiers, and retention ages every payload out at 365d — the special-category-adjacent content, deleted in the single erasure/per-record transaction while the ai_call metadata row survives",
	"internal/modules/privacy:ai_call:retentionai.go:eraseEmbedCall":                                    "retention erases embedding-kind ai_call trace rows past their fixed 90-day cap (spec §4) in the single erasure/per-record transaction — a fixed operational cap, not an admin-editable retention_policy row",
	"internal/modules/consent:retention_policy:retention.go:SeedDefaultRetentionTx":                     "bootstrap plants the DM-SEED-1..6 defaults inside the workspace-creation transaction, beside the consent purposes it ships with, so a new installation is compliant before it serves a request. Boot-time only and one row per scope — the table's store, its RBAC gate and every runtime write live in privacy, which owns it",
	"internal/modules/privacy:field_provenance:erasure.go:anonymizeLeadTwins":                           "Art. 17 erasure deletes the subject's field-origin metadata in the single erasure transaction — provenance must not outlive the fields it annotates",
	"internal/modules/privacy:field_provenance:erasure.go:purgePersonDerivedRows":                       "Art. 17 erasure deletes the subject's field-origin metadata in the single erasure transaction — provenance must not outlive the fields it annotates",
	"internal/modules/privacy:field_provenance:erasuretimeline.go:redactSubjectTimeline":                "Art. 17 erasure deletes the subject's field-origin metadata in the single erasure transaction — provenance must not outlive the fields it annotates",
	"internal/modules/privacy:field_provenance:retentionactions.go:anonymizePersonRecord":               "Art. 17 erasure deletes the subject's field-origin metadata in the single erasure transaction — provenance must not outlive the fields it annotates",
	"internal/modules/privacy:field_provenance:retentionrestricted.go:purgeHeldRecordTraces":            "Art. 17 erasure deletes the subject's field-origin metadata in the single erasure transaction — provenance must not outlive the fields it annotates",
	"internal/modules/privacy:scheduled_send:scheduledsends.go:redactScheduledSends":                    "a message the rep chose to send later holds the subject's address, subject line and body BEFORE any activity exists, so the activity-keyed scrubs cannot reach it — Art. 17 empties the payload and cancels a pending one in the same transaction as the rest of the cascade, because a scheduled send that survived it would arrive the morning after the erasure certified the data destroyed",
	"internal/modules/privacy:approval:erasure_approvals.go:redactApprovalsCitingActivities":            "a staged approval holds a whole composed message — for a held draft (#707) an addressee, a subject line and a body — BEFORE any scheduled row or activity exists, so neither the activity-keyed scrubs nor the scheduled-send one can reach it. Art. 17 empties the proposal and EXPIRES a pending card in the same transaction as the rest of the cascade: a blanked card left decidable is one a colleague can still approve, which would run its effect with nobody named in it",
	"internal/modules/privacy:approval:erasure_approvals.go:redactStagedApprovals":                      "a staged approval holds a whole composed message — for a held draft (#707) an addressee, a subject line and a body — BEFORE any scheduled row or activity exists, so neither the activity-keyed scrubs nor the scheduled-send one can reach it. Art. 17 empties the proposal and EXPIRES a pending card in the same transaction as the rest of the cascade: a blanked card left decidable is one a colleague can still approve, which would run its effect with nobody named in it",
	"internal/modules/privacy:transcript_read:transcriptreadings.go:purgeTranscriptReadings":            "a reading of a transcript is a record OF a body — how many lines it addressed, which proposals came out of them — so it cannot outlive that body, and both destructive engines delete it in the SAME transaction that nulls the body. Its own schema means it to go by cascade (core 0245), but neither engine ever DELETES an activity: Art. 17 redacts the row in place and retention nulls its content, both because a timeline row is other people's record too, so that cascade has never once fired. Routing it through activities would leave the transcript committed as a tombstone while a reading still answered questions about how long it was",
	"internal/modules/privacy:workflow_run:erasure_approvals.go:redactStagedApprovals":                  "an automation run records what it planned and what it produced, which for a drafted email is the message itself — the greeting by name, the body. It is history rather than a record anybody addresses, so nothing is withdrawn here; the columns are emptied in the same transaction, because a run that outlived the erasure would keep a copy of the message the subject asked us to destroy",
	"internal/modules/privacy:workflow_run:erasure_approvals.go:redactWorkflowRuns":                     "an automation run records what it planned and what it produced, which for a drafted email is the message itself — the greeting by name, the body. It is history rather than a record anybody addresses, so nothing is withdrawn here; the columns are emptied in the same transaction, because a run that outlived the erasure would keep a copy of the message the subject asked us to destroy",
	"internal/modules/privacy:agent_run:erasure_approvals.go:redactStagedApprovals":                     "an agent run parks in awaiting_approval behind a staged approval and is only ever resumed by an approval.decided event. Erasure withdraws that approval without emitting one, so the run would wait forever holding the payload just destroyed — pending carries the staged call's arguments, which for a send is the recipient and the body. Ended here, in the same transaction as the withdrawal, for the reason workflow_run is",
	"internal/modules/privacy:comms_outbound:deliveries.go:redactDeliveries":                            "the send log stores a second copy of an outbound message's recipients, subject and body, so Art. 17 erasure and the retention erase action scrub it in the SAME transaction that scrubs the activity it belongs to — routing it through comms would let the timeline row commit as a tombstone while the delivery still served the whole message",
	"internal/modules/privacy:comms_outbound:erasure_restrict.go:redactDeliveryAddressing":              "the send log stores a second copy of an outbound message's recipients, subject and body, so Art. 17 erasure and the retention erase action scrub it in the SAME transaction that scrubs the activity it belongs to — routing it through comms would let the timeline row commit as a tombstone while the delivery still served the whole message",
	// direct audit_log/event_outbox writers: these paths need columns
	// storekit's writer does not carry.
	"internal/modules/approvals:audit_log:service.go:audit":   "approval evidence stamps passport_id/on_behalf_of, columns storekit's writer does not carry; same append-only table, this module's own writer",
	"internal/modules/approvals:event_outbox:service.go:emit": "approvals stages its events with the full envelope (passport actor fields) storekit.Emit does not carry; still outbox-only publishing",
	// the non-production admin data-reset orchestration (compose, cross-module
	// by nature — it sweeps every module's workspace_id tables in one
	// transaction) must clear the workspace's staged events alongside the
	// domain rows it just deleted: event_outbox has no workspace_id column
	// (tenancy lives in the envelope) and no owning module's store call could
	// scope a delete to "this workspace's queued events" without compose
	// growing a dependency on every module it sweeps.
	"internal/compose:event_outbox:datasweep.go:clearWorkspaceOutbox": "the reset orchestration clears this workspace's staged events in the same transaction as the domain sweep, so no relay ever wakes on an envelope pointing at a row the reset just deleted",
	// identity owns login/failed-login, which land in system_log (a login
	// mutates no record). They fire before/without an authenticated
	// principal for storekit.LogSystem to stamp — bootstrap and failed
	// logins have no session yet — so identity appends the append-only rows
	// directly.
	"internal/modules/identity:system_log:installation.go:createInstallation": "login and failed-login land in system_log but fire before/without an authenticated principal for storekit.LogSystem to stamp; identity appends the append-only rows itself",
	"internal/modules/identity:system_log:lockout.go:recordFailedLogin":       "login and failed-login land in system_log but fire before/without an authenticated principal for storekit.LogSystem to stamp; identity appends the append-only rows itself",
	"internal/modules/identity:system_log:reset.go:OperatorResetPassword":     "login and failed-login land in system_log but fire before/without an authenticated principal for storekit.LogSystem to stamp; identity appends the append-only rows itself",
	"internal/modules/identity:system_log:service.go:logAuthEvent":            "login and failed-login land in system_log but fire before/without an authenticated principal for storekit.LogSystem to stamp; identity appends the append-only rows itself",
})
