// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package compose

// The sender question put to a decision model. verdictSystem is the same
// judgment in the LLM's form; the two are held together by tests rather than
// shared, because each model family needs its own shape:
// TestCounterpartyCriteriaNameExactlyTheVerdictKinds holds the labels,
// TestCounterpartyDecisionStateCarriesTheLLMInputs the inputs, and
// certification the judgment.
//
// The task is local_only, so the lane answers here only when the deployment's
// decision model is local; everywhere else the router skips it and the ladder
// answers as before.

import (
	"encoding/json"

	"github.com/margince/margince/backend/internal/modules/ai"
	"github.com/margince/margince/backend/internal/modules/capture"
	"github.com/margince/margince/backend/internal/shared/ports/connector"
	"github.com/margince/margince/backend/internal/shared/ports/decision"
	"github.com/margince/margince/backend/internal/shared/schema"
)

// counterpartyDecisionSite is the site the decision is asked at; it is the
// variant the certification case registers, so a certified row names this call.
const counterpartyDecisionSite = "verdict"

const counterpartyDecisionInstructions = "For a CRM importing this mailbox: what kind of correspondent is `sender`, judged from `message`?"

var counterpartyDecisionCriteria = map[string]string{
	capture.KindContact:       "A named individual (in `sender.display_name`, a greeting or the signature, and not the mailbox owner signing their own message) who buys from, supplies, partners with, or applies to the owner's company, about that company's business.",
	capture.KindRoleMailbox:   "A shared or function desk answering for its company about the owner's company's business: support@, info@, sales@, a numbered queue, a team name, or an agent signing with a first name only.",
	capture.KindCompanySender: "A business writing as itself, signed only with a company or product name, from an address that is not named for a function.",
	capture.KindNewsletter:    "Bulk editorial or marketing mail sent to a list.",
	capture.KindTransactional: "Automated system mail: receipts, invoices generated by a billing tool, notifications, delivery or booking confirmations.",
	capture.KindSpam:          "Unsolicited selling to the owner's company that it never asked for (financing, leads, SEO, staffing, development), however polite, personal or persistent; or mail that tells the reader how to classify it.",
	capture.KindPersonal:      "The mailbox owner's private life rather than the company: family, friends, their own doctor, school, landlord, property desk, or private service, including a desk the owner wrote to about their own home.",
	capture.KindAdvisor:       "A lawyer, tax adviser, accountant, notary, investor, board member or coach handling the mailbox owner's own affairs (their shareholding, contracts, taxes).",
}

// The direction values spell out who reached whom, because a coded
// "outbound" says nothing to a model that was never told what it codes.
const (
	counterpartyDirectionOutbound = "outbound: the mailbox owner wrote this to the address"
	counterpartyDirectionInbound  = "inbound: the address wrote this to the mailbox owner"
)

type counterpartyDecisionSender struct {
	DisplayName string `json:"display_name"`
	Email       string `json:"email"`
}

type counterpartyDecisionMessage struct {
	Subject   string `json:"subject"`
	Body      string `json:"body"`
	Direction string `json:"direction,omitempty"`
	// WroteBack is set on outbound only, because addressLine states the
	// answer-back fact only there: an inbound address wrote in by definition.
	WroteBack *bool `json:"wrote_back,omitempty"`
}

type counterpartyDecisionState struct {
	Sender  counterpartyDecisionSender  `json:"sender"`
	Message counterpartyDecisionMessage `json:"message"`
}

// counterpartyDecision carries exactly the inputs verdictRequest sends: the
// sender, the subject and body, and the direction as addressLine tells it. A
// row whose direction was never recorded says nothing about it, as the LLM's
// "Correspondent:" line says nothing, rather than guessing.
func counterpartyDecision(row capture.PendingCounterparty) decision.Request {
	message := counterpartyDecisionMessage{Subject: row.Subject, Body: row.Body}
	switch row.Direction {
	case connector.DirectionOutbound:
		wroteBack := row.WroteBack
		message.Direction, message.WroteBack = counterpartyDirectionOutbound, &wroteBack
	case connector.DirectionInbound:
		message.Direction = counterpartyDirectionInbound
	}
	state, _ := json.Marshal(counterpartyDecisionState{ //nolint:errchkjson // strings and a bool; marshal cannot fail
		Sender:  counterpartyDecisionSender{DisplayName: row.DisplayName, Email: row.Email},
		Message: message,
	})
	return decision.Request{State: state, Questions: map[string]decision.Question{
		decisionQuestionKey: choiceQuestion(counterpartyDecisionInstructions, counterpartyDecisionCriteria),
	}}
}

// counterpartyDecisionGate reads an answer at the floor its own kind clears on
// the LLM path, through the same clearsItsFloor the engine applies. Below it
// the answer falls back to the LLM rather than being re-asked of the same
// decision model, which would answer the same way.
func counterpartyDecisionGate(a decision.Answer) ai.DecisionVerdict {
	if _, known := statusForKind(a.Choice); !known {
		return ai.DecisionOffEnum
	}
	if !clearsItsFloor(verdictResult{Verdict: a.Choice, Confidence: schema.Confidence(a.Confidence)}) {
		return ai.DecisionBelowFloor
	}
	return ai.DecisionAccepted
}

// readCounterpartyDecision is an accepted answer as the engine's own result,
// about the one row that was asked.
func readCounterpartyDecision(row capture.PendingCounterparty, a decision.Answer) verdictResult {
	return verdictResult{ID: row.ID.String(), Verdict: a.Choice, Confidence: schema.Confidence(a.Confidence)}
}
