// Code generated by tools/gen-jobs from api/jobs.yaml. DO NOT EDIT.

package compose

import (
	"time"

	"github.com/riverqueue/river"

	"github.com/margince/margince/backend/internal/platform/jobs"
)

// jobContractHash is the sha256 of api/jobs.yaml this file was generated
// from — the same fingerprint jobs.JobContractHash carries, so a stale
// half of the pair is visible without diffing the two tables.
const jobContractHash = "95adbfaf26fb3f3e80620c78f6c98f13f3052ca93f49070a1cb53e17a92dcb5f"

// declaredJobArgs is every args type api/jobs.yaml declares, and nothing
// else. A job kind the file has never heard of cannot satisfy it, so it
// cannot be passed to either registration function below — and those two
// are how the runner registers, so an undeclared kind does not compile.
//
// A union rather than a marker interface, because a marker is something a
// new type can declare for itself: the set has to be the file's to state.
type declaredJobArgs interface {
	river.JobArgs

	AccountScanArgs |
		AgentSchedulerArgs |
		AgentTaskRetentionArgs |
		AIActivityReconcileArgs |
		AIActivityRetentionArgs |
		AiModelRateRefreshArgs |
		ApprovalAutoApplyArgs |
		ApprovalExpiryArgs |
		AssuranceSweepArgs |
		AssuranceWorkspaceArgs |
		BriefGenerateArgs |
		BriefGenerateWorkspaceArgs |
		CaptureAutoEnrichSweepArgs |
		CaptureBackfillArgs |
		CaptureClassifyArgs |
		ConfidentialityVerdictArgs |
		CounterpartyVerdictArgs |
		CaptureDigestArgs |
		CaptureDigestWorkspaceArgs |
		CaptureEnrichArgs |
		CaptureSyncArgs |
		CaptureTraceSweepArgs |
		CheckOrganizationVatArgs |
		CloseDateSweepArgs |
		CloseDateWorkspaceArgs |
		AuthzDisagreementArgs |
		ScheduledSendArgs |
		ScheduledSendRecoveryArgs |
		SendEmailArgs |
		DocumentExtractArgs |
		EmbedDriftSweepArgs |
		EmbedReindexArgs |
		FinanceSyncSweepArgs |
		FollowUpReconcileArgs |
		FollowUpWorkspaceArgs |
		ForecastSnapshotSweepArgs |
		ForecastSnapshotWorkspaceArgs |
		FxRateRefreshArgs |
		GeocodeBackfillArgs |
		GeocodeOrganizationArgs |
		GmailSyncArgs |
		GmailWatchArgs |
		GmailWatchRenewArgs |
		GraphEdgeReconcileArgs |
		GraphEdgeWorkspaceArgs |
		GraphWatchArgs |
		GraphWatchRenewArgs |
		IdempotencyRetentionArgs |
		IdempotencyRetentionWorkspaceArgs |
		IntroExpiryArgs |
		KnowledgeIngestArgs |
		LinkReconcileArgs |
		LinkReconcileWorkspaceArgs |
		LinkedInRematchArgs |
		LinkedInRematchWorkspaceArgs |
		OrgNamePromotionArgs |
		OrgNamePromotionWorkspaceArgs |
		OverlayReconcileArgs |
		OverlayReconcileWorkspaceArgs |
		OverlayRefetchArgs |
		OwedVerdictArgs |
		ParticipantBackfillArgs |
		ParticipantBackfillWorkspaceArgs |
		PrivacyRetentionArgs |
		ProviderLookupArgs |
		ProviderLookupSweepArgs |
		ProviderRunPollArgs |
		ProviderRunPollSweepArgs |
		ProviderRunSubmitArgs |
		SignalScanArgs |
		SignalScanWorkspaceArgs |
		SiteDeepReadArgs |
		TechnicalEnrichBackfillArgs |
		TechnicalEnrichOrganizationArgs |
		TelegramIngestArgs |
		TelegramPollArgs |
		TelegramPollSweepArgs |
		TimeScanArgs |
		TimeScanWorkspaceArgs |
		TranscriptProposeArgs |
		VCardIngestArgs |
		VoiceBuildArgs |
		VoiceBuildRetryArgs |
		WebhookRetryArgs |
		WeeklyReviewGenerateArgs |
		WeeklyReviewGenerateWorkspaceArgs
}

// addDeclaredWorker is the sanctioned registration path. Its type parameter
// is constrained to the declared set, so a kind absent from api/jobs.yaml
// cannot be named here at all — the error lands on the registration line
// the author is writing, as `does not satisfy declaredJobArgs`.
//
// It takes the registry, not river.Workers: River's Workers map is
// unexported, so the registry is the only thing that can tell MustBeTotal
// what this build registered.
func addDeclaredWorker[T declaredJobArgs](reg *jobRegistry, w jobs.WorkOnly[T]) {
	addGovernedWorker[T](reg, w, 0)
}

// addDeclaredWorkerWithTimeout serves the kinds whose timeout is an
// operator's to set, and so is computed at boot rather than stated in
// api/jobs.yaml. Every other kind takes its wall clock from the file and
// registers through addDeclaredWorker; jobtimeoutwiring_test.go derives
// which is which from the declared TimeoutPolicy rather than a list.
//
// The mark it leaves lets the census check that same claim against the
// wiring it built rather than against the source: passing through here is
// the only way a kind's wall clock comes from anywhere but the file.
func addDeclaredWorkerWithTimeout[T declaredJobArgs](reg *jobRegistry, w jobs.WorkOnly[T], supplied time.Duration) {
	addGovernedWorker[T](reg, w, supplied)
	var zero T
	reg.markOperatorSupplied(zero.Kind())
}

// The declared dispatchers: each enumerates the fleet and enqueues, and does
// no tenant work of its own.
var (
	_ jobs.FleetWide = AssuranceSweepArgs{}
	_ jobs.FleetWide = BriefGenerateArgs{}
	_ jobs.FleetWide = CaptureDigestArgs{}
	_ jobs.FleetWide = CloseDateSweepArgs{}
	_ jobs.FleetWide = FollowUpReconcileArgs{}
	_ jobs.FleetWide = ForecastSnapshotSweepArgs{}
	_ jobs.FleetWide = GmailSyncArgs{}
	_ jobs.FleetWide = GmailWatchArgs{}
	_ jobs.FleetWide = GraphEdgeReconcileArgs{}
	_ jobs.FleetWide = GraphWatchArgs{}
	_ jobs.FleetWide = IdempotencyRetentionArgs{}
	_ jobs.FleetWide = LinkReconcileArgs{}
	_ jobs.FleetWide = LinkedInRematchArgs{}
	_ jobs.FleetWide = OrgNamePromotionArgs{}
	_ jobs.FleetWide = OverlayReconcileArgs{}
	_ jobs.FleetWide = ParticipantBackfillArgs{}
	_ jobs.FleetWide = ProviderLookupSweepArgs{}
	_ jobs.FleetWide = ProviderRunPollSweepArgs{}
	_ jobs.FleetWide = SignalScanArgs{}
	_ jobs.FleetWide = TelegramPollSweepArgs{}
	_ jobs.FleetWide = TimeScanArgs{}
	_ jobs.FleetWide = VoiceBuildRetryArgs{}
	_ jobs.FleetWide = WeeklyReviewGenerateArgs{}
)

// The declared tenant-scoped kinds: each says which workspace it is for
// in its own args.
var (
	_ jobs.WorkspaceScoped = AccountScanArgs{}
	_ jobs.WorkspaceScoped = AiModelRateRefreshArgs{}
	_ jobs.WorkspaceScoped = AssuranceWorkspaceArgs{}
	_ jobs.WorkspaceScoped = BriefGenerateWorkspaceArgs{}
	_ jobs.WorkspaceScoped = CaptureBackfillArgs{}
	_ jobs.WorkspaceScoped = CaptureDigestWorkspaceArgs{}
	_ jobs.WorkspaceScoped = CaptureSyncArgs{}
	_ jobs.WorkspaceScoped = CheckOrganizationVatArgs{}
	_ jobs.WorkspaceScoped = CloseDateWorkspaceArgs{}
	_ jobs.WorkspaceScoped = ScheduledSendArgs{}
	_ jobs.WorkspaceScoped = SendEmailArgs{}
	_ jobs.WorkspaceScoped = DocumentExtractArgs{}
	_ jobs.WorkspaceScoped = FollowUpWorkspaceArgs{}
	_ jobs.WorkspaceScoped = ForecastSnapshotWorkspaceArgs{}
	_ jobs.WorkspaceScoped = FxRateRefreshArgs{}
	_ jobs.WorkspaceScoped = GeocodeOrganizationArgs{}
	_ jobs.WorkspaceScoped = GmailWatchRenewArgs{}
	_ jobs.WorkspaceScoped = GraphEdgeWorkspaceArgs{}
	_ jobs.WorkspaceScoped = GraphWatchRenewArgs{}
	_ jobs.WorkspaceScoped = IdempotencyRetentionWorkspaceArgs{}
	_ jobs.WorkspaceScoped = KnowledgeIngestArgs{}
	_ jobs.WorkspaceScoped = LinkReconcileWorkspaceArgs{}
	_ jobs.WorkspaceScoped = LinkedInRematchWorkspaceArgs{}
	_ jobs.WorkspaceScoped = OrgNamePromotionWorkspaceArgs{}
	_ jobs.WorkspaceScoped = OverlayReconcileWorkspaceArgs{}
	_ jobs.WorkspaceScoped = OverlayRefetchArgs{}
	_ jobs.WorkspaceScoped = ParticipantBackfillWorkspaceArgs{}
	_ jobs.WorkspaceScoped = ProviderLookupArgs{}
	_ jobs.WorkspaceScoped = ProviderRunPollArgs{}
	_ jobs.WorkspaceScoped = ProviderRunSubmitArgs{}
	_ jobs.WorkspaceScoped = SignalScanWorkspaceArgs{}
	_ jobs.WorkspaceScoped = SiteDeepReadArgs{}
	_ jobs.WorkspaceScoped = TechnicalEnrichOrganizationArgs{}
	_ jobs.WorkspaceScoped = TelegramIngestArgs{}
	_ jobs.WorkspaceScoped = TelegramPollArgs{}
	_ jobs.WorkspaceScoped = TimeScanWorkspaceArgs{}
	_ jobs.WorkspaceScoped = TranscriptProposeArgs{}
	_ jobs.WorkspaceScoped = VCardIngestArgs{}
	_ jobs.WorkspaceScoped = VoiceBuildArgs{}
	_ jobs.WorkspaceScoped = WeeklyReviewGenerateWorkspaceArgs{}
)
