// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package compose

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// WHICH MODEL SHOULD JUDGE THE USE-CASE LANE, answered from measurement rather
// than from the assumption that the most expensive model is the right one.
//
// The lane's semantic half is decided by a model (e2e/llm/judge.py), so the
// judge is part of the product's test apparatus and its accuracy is a fact
// somebody has to be able to check. This publishes that fact the way the
// coverage page publishes the surface: generated from committed records, and
// drift-gated so it cannot quietly stop describing the runs it names.
//
// THE GROUND TRUTH IS NOT ANOTHER MODEL'S OPINION. e2e/llm/testdata/judge holds
// 185 verdicts recorded by one model; scoring a model against those measures
// resemblance to that model and hands it a free 100% when it IS that model. The
// fixtures under e2e/llm/testdata/<case>/ carry a better label: a person wrote
// each answer to be right or wrong on a named criterion and
// scripts/test-e2e-llm-check.sh states which. That is the corpus scored here.
var updateJudgeModelEval = flag.Bool("update-judge-model-eval", false,
	"rewrite docs/reference/judge-model-eval.{json,md} from the committed eval records")

const judgeModelEvalCommand = "go test ./internal/compose/ -run TestTheJudgeModelEvalIsPublished -update-judge-model-eval"

const judgeEvalRecordDir = "aicert/records/judge_eval"

// A SUITE CASE THAT NO JUDGE MODEL CAN PASS, and therefore no model's failure.
//
// The case pins E2E_LLM_JUDGE_MODEL to a name no corpus was recorded under and
// asserts the replay is refused. An eval run drives the suite with a LIVE judge,
// where there is no recorded verdict to mismatch, so the case fails identically
// for every model under test. Counting it would charge all three for a property
// of how they were measured.
//
// Named rather than filtered by a pattern: an exemption that matched broadly
// would silently start excusing real failures, which is the one direction a
// census must not fail in.
var judgeEvalHarnessArtifacts = map[string]string{
	"judge/a verdict from another model is a stop": "the case pins a model with no recorded corpus and asserts the replay is refused; an eval drives the suite live, so there is no replay to mismatch and it fails for every model alike",
}

type judgeEvalRecord struct {
	Model                string   `json:"model"`
	GroundTruth          string   `json:"ground_truth"`
	SuiteExit            int      `json:"suite_exit"`
	CasesPassed          int      `json:"cases_passed"`
	CasesFailed          int      `json:"cases_failed"`
	JudgedFixturesPassed int      `json:"judged_fixtures_passed"`
	JudgedFixturesFailed int      `json:"judged_fixtures_failed"`
	Failures             []string `json:"failures"`
}

type judgeEvalRow struct {
	Model string `json:"model"`
	// Scored is what this model was actually charged with: every suite case
	// except the artifacts above, which no model can pass.
	Scored int `json:"scored"`
	Passed int `json:"passed"`
	// Failed is the model's own errors. Artifacts are reported separately so a
	// reader can see the arithmetic rather than trust a filtered total.
	Failed    int      `json:"failed"`
	Artifacts int      `json:"harness_artifacts"`
	Accuracy  string   `json:"accuracy"`
	Errors    []string `json:"errors"`
}

type judgeModelEval struct {
	Note      string            `json:"note"`
	GroundTru string            `json:"ground_truth"`
	Models    []judgeEvalRow    `json:"models"`
	Artifacts map[string]string `json:"harness_artifacts_excluded"`
}

func TestTheJudgeModelEvalIsPublished(t *testing.T) {
	entries, err := os.ReadDir(judgeEvalRecordDir)
	if err != nil {
		t.Fatalf("reading the judge eval records at %s: %v", judgeEvalRecordDir, err)
	}

	report := judgeModelEval{
		Note: "Generated by `" + judgeModelEvalCommand + "` from the eval records committed under " +
			judgeEvalRecordDir + ". Each record is one run of scripts/test-e2e-llm-check.sh with that model as the live judge.",
		GroundTru: "human-authored fixtures under e2e/llm/testdata/<case>/, labelled by scripts/test-e2e-llm-check.sh — no judge model produced them",
		Artifacts: judgeEvalHarnessArtifacts,
	}

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".json") {
			continue
		}
		raw, err := os.ReadFile(filepath.Join(judgeEvalRecordDir, entry.Name()))
		if err != nil {
			t.Fatalf("reading %s: %v", entry.Name(), err)
		}
		var record judgeEvalRecord
		if err := json.Unmarshal(raw, &record); err != nil {
			t.Fatalf("decoding %s: %v", entry.Name(), err)
		}

		row := judgeEvalRow{Model: record.Model, Errors: []string{}}
		for _, failure := range record.Failures {
			if _, artifact := judgeEvalHarnessArtifacts[failure]; artifact {
				row.Artifacts++
				continue
			}
			row.Errors = append(row.Errors, failure)
		}
		row.Failed = len(row.Errors)
		// The denominator excludes the artifacts, because a case no model can
		// pass measures nothing about any of them.
		row.Scored = record.CasesPassed + record.CasesFailed - row.Artifacts
		row.Passed = row.Scored - row.Failed
		if row.Scored > 0 {
			row.Accuracy = fmt.Sprintf("%.1f%%", 100*float64(row.Passed)/float64(row.Scored))
		}
		sort.Strings(row.Errors)
		report.Models = append(report.Models, row)
	}

	if len(report.Models) == 0 {
		t.Fatalf("no eval records under %s, so this page would publish an empty comparison as a finished one",
			judgeEvalRecordDir)
	}
	// Most accurate first, and by name where two tie, so the page does not
	// reorder itself between runs over a map iteration.
	sort.Slice(report.Models, func(i, j int) bool {
		if report.Models[i].Failed != report.Models[j].Failed {
			return report.Models[i].Failed < report.Models[j].Failed
		}
		return report.Models[i].Model < report.Models[j].Model
	})

	payload, err := json.MarshalIndent(report, "", "  ")
	if err != nil {
		t.Fatalf("encoding the judge eval report: %v", err)
	}
	syncJudgeModelEval(t, filepath.Join(mcpDocsDir, "judge-model-eval.json"), append(payload, '\n'))
	syncJudgeModelEval(t, filepath.Join(mcpDocsDir, "judge-model-eval.md"), renderJudgeModelEvalPage(report))
}

func syncJudgeModelEval(t *testing.T, path string, want []byte) {
	t.Helper()
	if *updateJudgeModelEval {
		if err := os.WriteFile(path, want, 0o644); err != nil {
			t.Fatalf("rewriting %s: %v", path, err)
		}
		return
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading the committed artifact %s: %v\nRegenerate with: %s", path, err, judgeModelEvalCommand)
	}
	if bytes.Equal(got, want) {
		return
	}
	t.Errorf("%s is stale — it no longer matches the committed eval records.\n"+
		"Regenerate with: %s\nand commit the result with the change that moved it.",
		path, judgeModelEvalCommand)
}

func renderJudgeModelEvalPage(r judgeModelEval) []byte {
	var p strings.Builder
	p.WriteString("# Which model judges the use-case lane\n\n")
	p.WriteString("<!-- Generated together with judge-model-eval.json; do not edit by hand. -->\n\n")
	p.WriteString(r.Note + "\n\n")
	p.WriteString("**This page is generated, and an edit made here is lost.**\n\n")

	p.WriteString("## Why this is measured at all\n\n")
	p.WriteString("The semantic half of `e2e/llm` is decided by a model rather than a regex, so the\n")
	p.WriteString("judge is part of the test apparatus and its accuracy is a fact somebody has to be\n")
	p.WriteString("able to check. A judge that is wrong in the quiet direction — passing an answer\n")
	p.WriteString("the criterion fails — turns a missed product defect into a green run.\n\n")

	p.WriteString("## Ground truth\n\n")
	p.WriteString(r.GroundTru + "\n\n")
	p.WriteString("The 185 verdicts under `e2e/llm/testdata/judge/` are deliberately NOT the ground\n")
	p.WriteString("truth here. They were recorded by one model, so scoring against them measures\n")
	p.WriteString("resemblance to that model and hands it a free hundred per cent when it is that\n")
	p.WriteString("model.\n\n")

	p.WriteString("## Result\n\n")
	p.WriteString("| judge | accuracy | scored | passed | its own errors |\n")
	p.WriteString("|---|---:|---:|---:|---:|\n")
	for _, row := range r.Models {
		p.WriteString(fmt.Sprintf("| `%s` | %s | %d | %d | %d |\n",
			row.Model, row.Accuracy, row.Scored, row.Passed, row.Failed))
	}
	p.WriteString("\n")

	p.WriteString("### What each model got wrong\n\n")
	for _, row := range r.Models {
		p.WriteString(fmt.Sprintf("**`%s`** — %d error(s)\n\n", row.Model, row.Failed))
		if len(row.Errors) == 0 {
			p.WriteString("- none\n\n")
			continue
		}
		for _, failure := range row.Errors {
			p.WriteString("- `" + failure + "`\n")
		}
		p.WriteString("\n")
	}

	if len(r.Artifacts) > 0 {
		p.WriteString("## Excluded, and why\n\n")
		p.WriteString("These suite cases fail for every model alike because of how an eval run drives\n")
		p.WriteString("the suite, not because of the model under test. They are named here rather than\n")
		p.WriteString("filtered by a pattern, so the exemption cannot quietly widen.\n\n")
		names := make([]string, 0, len(r.Artifacts))
		for name := range r.Artifacts {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			p.WriteString("- `" + name + "` — " + r.Artifacts[name] + "\n")
		}
		p.WriteString("\n")
	}
	return []byte(p.String())
}
