// Code generated by tools/gen-queryenums from api/crm.yaml. DO NOT EDIT.

package compose

// queryEnumTable maps "METHOD /v1/path" to the query parameters the contract
// declares as closed enums, with the values each admits.
var queryEnumTable = map[string][]queryEnum{
	"DELETE /v1/activities/{id}/disposition": {
		{Name: "scope", Values: []string{"mine", "thread"}, Array: false, Explode: true},
	},
	"DELETE /v1/ai-model-rates": {
		{Name: "lane", Values: []string{"chat", "embeddings", "decisions"}, Array: false, Explode: true},
	},
	"GET /v1/activities": {
		{Name: "entity_type", Values: []string{"contact", "company", "deal", "lead", "project"}, Array: false, Explode: true},
		{Name: "kind", Values: []string{"email", "call", "meeting", "note", "task", "message"}, Array: false, Explode: true},
	},
	"GET /v1/ai/call-stats": {
		{Name: "group", Values: []string{"provider", "model", "served_provider", "tier", "task"}, Array: false, Explode: true},
		{Name: "window", Values: []string{"24h", "7d", "30d"}, Array: false, Explode: true},
	},
	"GET /v1/ai/call-stats/flow": {
		{Name: "window", Values: []string{"24h", "7d", "30d"}, Array: false, Explode: true},
	},
	"GET /v1/analytics/editions/{id}/evidence": {
		{Name: "metric", Values: []string{"bookings_won", "closed_win_rate", "open_pipeline", "stage_age", "qualified_pipeline_created", "meetings_held", "accepted_opportunities", "forecast_landing"}, Array: false, Explode: true},
	},
	"GET /v1/analytics/evaluate": {
		{Name: "blocks", Values: []string{"bookings_trend", "stage_distribution", "owner_attainment", "stage_age", "sdr_outcomes", "target_progress", "forecast_support", "pipeline_movement", "metric_reading"}, Array: true, Explode: true},
		{Name: "close_window", Values: []string{"fiscal_quarter", "all_open"}, Array: false, Explode: true},
		{Name: "metrics", Values: []string{"bookings_won", "closed_win_rate", "open_pipeline", "stage_age", "qualified_pipeline_created", "meetings_held", "accepted_opportunities", "forecast_landing"}, Array: true, Explode: true},
		{Name: "period", Values: []string{"this_month", "last_month", "last_week", "this_quarter", "custom"}, Array: false, Explode: true},
		{Name: "scope_kind", Values: []string{"owner", "team", "workspace"}, Array: false, Explode: true},
		{Name: "target_basis", Values: []string{"month", "fiscal_quarter"}, Array: false, Explode: true},
	},
	"GET /v1/analytics/evaluate.csv": {
		{Name: "blocks", Values: []string{"bookings_trend", "stage_distribution", "owner_attainment", "stage_age", "sdr_outcomes", "target_progress", "forecast_support", "pipeline_movement", "metric_reading"}, Array: true, Explode: true},
		{Name: "close_window", Values: []string{"fiscal_quarter", "all_open"}, Array: false, Explode: true},
		{Name: "metrics", Values: []string{"bookings_won", "closed_win_rate", "open_pipeline", "stage_age", "qualified_pipeline_created", "meetings_held", "accepted_opportunities", "forecast_landing"}, Array: true, Explode: true},
		{Name: "period", Values: []string{"this_month", "last_month", "last_week", "this_quarter", "custom"}, Array: false, Explode: true},
		{Name: "scope_kind", Values: []string{"owner", "team", "workspace"}, Array: false, Explode: true},
		{Name: "target_basis", Values: []string{"month", "fiscal_quarter"}, Array: false, Explode: true},
	},
	"GET /v1/analytics/evidence": {
		{Name: "blocks", Values: []string{"bookings_trend", "stage_distribution", "owner_attainment", "stage_age", "sdr_outcomes", "target_progress", "forecast_support", "pipeline_movement", "metric_reading"}, Array: true, Explode: true},
		{Name: "close_window", Values: []string{"fiscal_quarter", "all_open"}, Array: false, Explode: true},
		{Name: "metric", Values: []string{"bookings_won", "closed_win_rate", "open_pipeline", "stage_age", "qualified_pipeline_created", "meetings_held", "accepted_opportunities", "forecast_landing"}, Array: false, Explode: true},
		{Name: "metrics", Values: []string{"bookings_won", "closed_win_rate", "open_pipeline", "stage_age", "qualified_pipeline_created", "meetings_held", "accepted_opportunities", "forecast_landing"}, Array: true, Explode: true},
		{Name: "period", Values: []string{"this_month", "last_month", "last_week", "this_quarter", "custom"}, Array: false, Explode: true},
		{Name: "scope_kind", Values: []string{"owner", "team", "workspace"}, Array: false, Explode: true},
		{Name: "target_basis", Values: []string{"month", "fiscal_quarter"}, Array: false, Explode: true},
	},
	"GET /v1/approvals": {
		{Name: "status", Values: []string{"pending", "approved", "rejected"}, Array: false, Explode: true},
	},
	"GET /v1/attachments": {
		{Name: "entity_type", Values: []string{"contact", "company", "deal", "activity", "lead", "project"}, Array: false, Explode: true},
	},
	"GET /v1/automations/{id}/runs": {
		{Name: "outcome", Values: []string{"fired", "failed", "blocked", "skipped", "queued_for_approval"}, Array: false, Explode: true},
	},
	"GET /v1/catch-up": {
		{Name: "record_type", Values: []string{"contact", "company", "deal", "lead", "project", "activity"}, Array: false, Explode: true},
	},
	"GET /v1/commissions": {
		{Name: "status", Values: []string{"accrued", "approved", "paid", "void"}, Array: false, Explode: true},
	},
	"GET /v1/companies": {
		{Name: "captured_by_kind", Values: []string{"human", "agent", "connector", "system"}, Array: false, Explode: true},
		{Name: "lifecycle", Values: []string{"unknown", "target", "prospect", "opportunity", "customer", "former_customer", "disqualified"}, Array: false, Explode: true},
		{Name: "relationship_type", Values: []string{"customer", "partner", "supplier", "investor", "portfolio_company", "competitor", "other"}, Array: false, Explode: true},
		{Name: "size_band", Values: []string{"1-10", "11-50", "51-200", "201-500", "501-1000", "1001-5000", "5000+"}, Array: false, Explode: true},
		{Name: "tag_mode", Values: []string{"any", "all", "none"}, Array: false, Explode: true},
	},
	"GET /v1/companies/{id}/contacts": {
		{Name: "sort", Values: []string{"recommended", "last_interaction", "-last_interaction", "strength", "-strength", "name", "-name"}, Array: false, Explode: true},
		{Name: "status", Values: []string{"waiting", "answered", "no_reply", "lapsed", "untried"}, Array: false, Explode: true},
	},
	"GET /v1/companies/{id}/contracts": {
		{Name: "status", Values: []string{"draft", "active", "expired", "cancelled", "superseded"}, Array: false, Explode: true},
	},
	"GET /v1/companies/{id}/documents": {
		{Name: "category", Values: []string{"contract", "offer", "legal", "email_attachment", "message_attachment", "other"}, Array: false, Explode: true},
		{Name: "doc_state", Values: []string{"draft", "current", "final", "superseded"}, Array: false, Explode: true},
	},
	"GET /v1/companies/{id}/hierarchy-rollup": {
		{Name: "scope", Values: []string{"tree", "self"}, Array: false, Explode: true},
	},
	"GET /v1/contacts": {
		{Name: "captured_by_kind", Values: []string{"human", "agent", "connector", "system"}, Array: false, Explode: true},
		{Name: "tag_mode", Values: []string{"any", "all", "none"}, Array: false, Explode: true},
	},
	"GET /v1/context-search": {
		{Name: "record_types", Values: []string{"contact", "company", "deal", "lead", "project"}, Array: true, Explode: true},
	},
	"GET /v1/custom-fields": {
		{Name: "object", Values: []string{"contact", "company", "deal", "lead", "project", "contract"}, Array: false, Explode: true},
		{Name: "status", Values: []string{"active", "retired"}, Array: false, Explode: true},
	},
	"GET /v1/data-subject-requests": {
		{Name: "status", Values: []string{"open", "in_progress", "fulfilled", "rejected"}, Array: false, Explode: true},
	},
	"GET /v1/deal-rooms": {
		{Name: "state", Values: []string{"draft", "building", "ready", "publishing", "live", "paused", "closed", "expired", "archived"}, Array: false, Explode: true},
	},
	"GET /v1/deals": {
		{Name: "commercial_motion", Values: []string{"new_business", "renewal", "upsell", "cross_sell", "expansion", "existing_business", "unset"}, Array: false, Explode: true},
		{Name: "forecast_category", Values: []string{"commit", "best_case", "pipeline", "omitted"}, Array: false, Explode: true},
		{Name: "partner_attribution", Values: []string{"sourced", "influenced"}, Array: false, Explode: true},
		{Name: "priority", Values: []string{"low", "medium", "high", "unset"}, Array: false, Explode: true},
		{Name: "status", Values: []string{"open", "won", "lost"}, Array: false, Explode: true},
		{Name: "tag_mode", Values: []string{"any", "all", "none"}, Array: false, Explode: true},
	},
	"GET /v1/deals/{id}/documents": {
		{Name: "category", Values: []string{"contract", "offer", "legal", "email_attachment", "message_attachment", "other"}, Array: false, Explode: true},
	},
	"GET /v1/deals/{id}/offers": {
		{Name: "status", Values: []string{"draft", "sent", "accepted", "rejected", "expired", "superseded"}, Array: false, Explode: true},
	},
	"GET /v1/dedupe/candidates": {
		{Name: "entity_type", Values: []string{"contact", "company", "lead"}, Array: false, Explode: true},
		{Name: "status", Values: []string{"open", "merged", "not_a_duplicate"}, Array: false, Explode: true},
	},
	"GET /v1/field-history": {
		{Name: "actor_type", Values: []string{"human", "agent", "system", "connector", "buyer"}, Array: false, Explode: true},
		{Name: "entity_type", Values: []string{"contact", "company", "deal", "lead", "project", "activity"}, Array: false, Explode: true},
	},
	"GET /v1/filters/vocabulary": {
		{Name: "resource", Values: []string{"contact", "company", "deal", "lead", "project"}, Array: false, Explode: true},
	},
	"GET /v1/forecast": {
		{Name: "period", Values: []string{"quarter", "month", "week"}, Array: false, Explode: true},
		{Name: "scope_kind", Values: []string{"workspace", "team", "owner"}, Array: false, Explode: true},
	},
	"GET /v1/forecast/calls": {
		{Name: "period", Values: []string{"quarter", "month", "week"}, Array: false, Explode: true},
		{Name: "scope_kind", Values: []string{"workspace", "team", "owner"}, Array: false, Explode: true},
	},
	"GET /v1/forecast/movement": {
		{Name: "reading", Values: []string{"open", "weighted", "evidence", "best_case"}, Array: false, Explode: true},
	},
	"GET /v1/leads": {
		{Name: "captured_by_kind", Values: []string{"human", "agent", "connector", "system"}, Array: false, Explode: true},
		{Name: "sla_state", Values: []string{"within_target", "at_risk", "breached"}, Array: false, Explode: true},
		{Name: "status", Values: []string{"new", "contacted", "engaged", "promoted", "disqualified"}, Array: false, Explode: true},
		{Name: "tag_mode", Values: []string{"any", "all", "none"}, Array: false, Explode: true},
	},
	"GET /v1/lists": {
		{Name: "entity_type", Values: []string{"contact", "company", "deal", "lead", "project"}, Array: false, Explode: true},
		{Name: "list_type", Values: []string{"static", "dynamic"}, Array: false, Explode: true},
		{Name: "sharing", Values: []string{"private", "team", "workspace"}, Array: true, Explode: true},
	},
	"GET /v1/mail-drafts": {
		{Name: "anchor_type", Values: []string{"activity", "contact", "company", "deal", "lead", "project"}, Array: false, Explode: true},
	},
	"GET /v1/me/ai-activity": {
		{Name: "kinds", Values: []string{"morning_brief", "overnight_at_risk_sweep", "document_extract", "site_read", "brief_ranking", "capture_classify", "capture_confidentiality_verdict", "capture_counterparty_verdict", "cert_judge", "cold_start", "deal_health", "draft_reply", "enrich", "growth_fit", "nl_search", "offer_draft", "rate_extract", "signal_extract", "site_extract", "site_fact_extract", "site_triage", "stage_evidence_extract", "summarize", "transcript", "transcript_propose", "voice_build", "corpus_ask", "weekly_review", "weekly_learnings", "propose_roles", "owed_verdict", "request_settlement", "account_scan"}, Array: true, Explode: true},
	},
	"GET /v1/meeting-prep": {
		{Name: "record_type", Values: []string{"contact", "company", "deal", "lead", "project", "activity"}, Array: false, Explode: true},
	},
	"GET /v1/onboarding/company/proposal": {
		{Name: "locale", Values: []string{"en", "de", "vi"}, Array: false, Explode: true},
	},
	"GET /v1/partners": {
		{Name: "cert_status", Values: []string{"applied", "certified", "suspended"}, Array: false, Explode: true},
		{Name: "partner_role", Values: []string{"hosting", "consulting", "strategic"}, Array: false, Explode: true},
	},
	"GET /v1/privacy/notice-cases": {
		{Name: "state", Values: []string{"open", "assigned", "queued", "delivery_failed", "completed", "provided_elsewhere", "exempt_with_reason", "blocked", "not_required"}, Array: true, Explode: true},
	},
	"GET /v1/projects": {
		{Name: "phase", Values: []string{"initiative", "pursuing", "delivering", "closed"}, Array: false, Explode: true},
	},
	"GET /v1/record-grants": {
		{Name: "record_type", Values: []string{"deal", "contact", "company", "lead", "project"}, Array: false, Explode: true},
		{Name: "subject_type", Values: []string{"user", "team"}, Array: false, Explode: true},
	},
	"GET /v1/relationships": {
		{Name: "kind", Values: []string{"employment", "deal_stakeholder", "project_stakeholder", "project_company", "partner_of", "referred_by", "co_sell_with", "works_with", "billing_contact"}, Array: false, Explode: true},
	},
	"GET /v1/reports/{report}/derivation": {
		{Name: "handle_version", Values: []string{"2"}, Array: false, Explode: true},
		{Name: "scope_kind", Values: []string{"workspace", "team", "owner"}, Array: false, Explode: true},
	},
	"GET /v1/scheduled-sends": {
		{Name: "status", Values: []string{"scheduled", "released", "sent", "cancelled", "held"}, Array: false, Explode: true},
	},
	"GET /v1/scheduling/calendars": {
		{Name: "provider", Values: []string{"gcal", "graphcal"}, Array: false, Explode: true},
	},
	"GET /v1/search": {
		{Name: "types", Values: []string{"contact", "company", "deal", "activity", "lead", "project", "product", "offer_template", "tag"}, Array: true, Explode: false},
	},
	"GET /v1/signals": {
		{Name: "kind", Values: []string{"stalled_deal", "champion_left", "reengagement", "buying_intent", "risk", "other", "contract_ended", "new_opportunity", "commitment_made", "ghosted_thread", "project_gone_quiet", "funding", "leadership_change", "expansion", "product_launch", "technical_change"}, Array: false, Explode: true},
		{Name: "resolution_state", Values: []string{"resolved", "low_confidence", "unresolved", "dropped"}, Array: false, Explode: true},
		{Name: "status", Values: []string{"open", "acknowledged", "resolved", "dismissed"}, Array: false, Explode: true},
	},
	"GET /v1/views": {
		{Name: "resource", Values: []string{"contacts", "companies", "deals", "activities", "leads", "partners", "projects"}, Array: false, Explode: true},
	},
	"GET /v1/worklist": {
		{Name: "filter", Values: []string{"all", "urgent", "customer_waiting", "leads", "deals_at_risk", "meetings", "tasks", "decisions", "system", "except_decisions", "changed_since_brief"}, Array: false, Explode: true},
		{Name: "scope", Values: []string{"mine", "unassigned", "team", "all"}, Array: false, Explode: true},
	},
}
