// Code generated by gen-composition from the enabled set under extensions/; DO NOT EDIT.
// Regenerate: make gen (tools/gen-composition). Bare go builds resolve this module's
// committed vanilla stub (composition/ at the repo root) via backend/go.mod's replace;
// composed builds use the generated module under build/composition/ via its go.work.

package composition

import (
	"github.com/margince/margince/backend/pkg/extension"
)

// Extensions returns the composed extension set for this installation;
// vanilla (an empty extensions/ tree) composes none.
func Extensions() []extension.Extension {
	return nil
}

// Verbs returns every governed operation the enabled units' contract
// fragments declare, read out of the merged contracts at generation time and
// re-emitted here as literals — so a bare role binary, which ships no
// repository, still knows each operation's route, risk tier, requested scope
// and selection prose.
func Verbs() []extension.Verb {
	return nil
}

// Jobs returns every scheduled job the enabled units' jobs.yaml fragments
// declare, read out of the merged contract at generation time and re-emitted
// here as literals — so a bare role binary knows each job's cadence, wall
// clocks, queue, attempt cap, risk tier and requested scope.
func Jobs() []extension.JobDeclaration {
	return nil
}
