// Code generated by gen-payloads; DO NOT EDIT.

package crmcontracts

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// InternalEventAiTaskStateChanged Payload for ai_task.state_changed — one AI-backed occurrence reported its current state to the AI-activity projection. Entity-less by nature: the occurrence names no domain record, and the row that will hold it does not exist until the projection this event feeds writes it.
type InternalEventAiTaskStateChanged struct {
	// AiTask The api/ai-tasks.yaml task that did the model work, when one did. Absent for an occurrence with no model call of its own.
	AiTask *string `json:"ai_task,omitempty"`

	// Attempt Which attempt this state belongs to. The lifecycle is NOT monotonic — a claimed run can be released and re-claimed — so state alone cannot order two events.
	Attempt int `json:"attempt"`

	// DegradeReason SERVER-AUTHORED prose, never a provider message and never err.Error(). That is the property that matters rather than the spelling: a provider's own text can echo key material or a prompt injection's payload, and this column reaches an ordinary rep. The emitters satisfy it with fixed literals today; what a reviewer has to check of a new one is where the string came from, not what shape it is.
	DegradeReason *string `json:"degrade_reason,omitempty"`

	// FinishedAt When this attempt settled. Present exactly for a settled state.
	FinishedAt *time.Time `json:"finished_at,omitempty"`

	// Kind The display kind the client maps to a sentence.
	Kind string `json:"kind"`

	// LeaseSeconds The source's own lease on a live attempt. The projection stores started_at (or queued_at) plus this as stale_after, and the read renders a live row past it as stalled rather than as live.
	LeaseSeconds *int `json:"lease_seconds,omitempty"`

	// OccurrenceKey That source's own idempotency key for this occurrence.
	OccurrenceKey string `json:"occurrence_key"`

	// Quantity How much the occurrence handled, in quantity_unit.
	Quantity *int `json:"quantity,omitempty"`

	// QuantityUnit What quantity counts.
	QuantityUnit *string `json:"quantity_unit,omitempty"`

	// QueuedAt When the CURRENT attempt was enqueued. Not the occurrence's first enqueue: a live row ages from the instant its attempt became current, and a re-queued occurrence dated by its original creation is past its lease before any worker sees it.
	QueuedAt time.Time `json:"queued_at"`

	// Source The subsystem that owns the occurrence — 'attachment_extraction', 'agent_runner', 'capture_sync'. Identity, not display: two sources must never collide on one occurrence key.
	Source string `json:"source"`

	// StartedAt When this attempt was claimed. Absent while queued.
	StartedAt *time.Time `json:"started_at,omitempty"`

	// State The occurrence's state as of this event.
	State string `json:"state"`

	// SubjectId That record's id.
	SubjectId *openapi_types.UUID `json:"subject_id,omitempty"`

	// SubjectLabel What that record is CALLED, as the source knew it when it emitted. The projection may not ask: it reaches back into no source's tables, so a name it is not given is a name it does not have. The label travels for the same reason the lease does.
	// Unlike degrade_reason this is RECORD DATA rather than server-authored prose, and that is admissible here for one reason — it is the reader's own record, already shown to them on the surface the occurrence came from. It is never a provider's text. Resolve it the way the product titles the thing elsewhere, so the rail and the record cannot call one document two names.
	// A SNAPSHOT, never re-resolved on read: a record renamed afterwards keeps the old name on a settled line, which is what that line was actually about. The corollary is that it cannot be re-gated either, so a source emits a label only where the occurrence's own actor is the person the record was already displayed to.
	SubjectLabel *string `json:"subject_label,omitempty"`

	// SubjectType The kind of record the occurrence is about, when it is about one.
	SubjectType *string `json:"subject_type,omitempty"`

	// Summary The occurrence's own prose. Never the status line.
	Summary *string `json:"summary,omitempty"`
}

// InternalEventBriefOpened Payload for brief.opened — a rep read their morning Brief. The product question behind it is whether the thing gets opened at all, and on the days it says something worth acting on.
// Emitted on the READ of an existing run, never on the pass that assembles one: a night that ranked a queue nobody looked at is exactly the case this event exists to make visible, and counting the assembly as an open would hide it.
// Counts only, no prose and no record data. What a rep's morning HOLDS is already recoverable from the run itself, and what they DID with it from the audit rows brief_item marks write. This payload answers one question the other two cannot: whether they came and looked.
// Entity-less, and that is what keeps it internal. Every catalogued type that is NOT in the entity-less pipeline class is subscribable by an outside consumer — publicevents_test.go derives the set exactly as webhooks.validateEventTypes does — so naming brief_run here would make "this rep opened their Brief at 06:42" a webhook anyone may select. The run id stays on the system_log row the emit writes, where it is attributable without being deliverable.
type InternalEventBriefOpened struct {
	// Items How many items the run held when it was opened, AFTER expired snoozes resurfaced — what the rep actually saw, not what the night ranked. Zero is a real and interesting reading: a quiet morning that was still opened.
	Items int `json:"items"`

	// LocalDay The run's own local day, which is its identity — one run per rep per day. Carried so a consumer can tell today's first open from a re-open of yesterday's without reaching back into brief_run.
	LocalDay openapi_types.Date `json:"local_day"`

	// Unread How many of those carried no act, dismiss or snooze mark yet. Together with items it separates a first open from a return visit without needing a second event type for the difference.
	Unread int `json:"unread"`
}

func (InternalEventAiTaskStateChanged) EventType() string { return "ai_task.state_changed" }

func (InternalEventAiTaskStateChanged) EntityType() string { return "" }

func (InternalEventBriefOpened) EventType() string { return "brief.opened" }

func (InternalEventBriefOpened) EntityType() string { return "" }
