// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

//go:build !integration

package gates

// Rendering the entity model: one page per owning area, plus the index.
//
// The page set is derived from the ownership registry rather than listed here.
// A list would be the second copy of a set the tree already knows, and it would
// go short the day a module arrived — the page would simply not exist, and
// nothing about the tree would say so.

import (
	"fmt"
	"sort"
	"strings"
)

// entityModelPages renders every page, keyed by file name.
func entityModelPages(schema *emSchema, owners map[string]string, contract map[string]string) map[string]string {
	byArea := map[string][]string{}
	for _, table := range schema.tableNames() {
		area := areaOf(owners[table])
		byArea[area] = append(byArea[area], table)
	}
	pages := map[string]string{"README.md": renderIndex(schema, owners, byArea)}
	for area, tables := range byArea {
		pages[area+".md"] = renderArea(schema, area, tables, contract)
	}
	return pages
}

// areaOf is the page a table's owner belongs on.
//
// A module gets its own page. The composition layer and the platform get one
// each: their tables are owned by a dozen small packages, and a page per package
// would be thirty files of one table, which is a worse index than no index.
// A table with no owner is platform too — the audit log and the outbox are
// written by the write backbone itself rather than by any module.
func areaOf(owner string) string {
	switch {
	case strings.HasPrefix(owner, "internal/modules/"):
		return strings.TrimPrefix(owner, "internal/modules/")
	case strings.HasPrefix(owner, "internal/compose"):
		return "compose"
	default:
		return "platform"
	}
}

const generatedBy = "<!-- Generated by backend/gates/entitymodel_test.go. Do not edit by hand. -->"

// primaryEntityCount is how many records the index draws as the model's spine.
// They are the most-referenced tables, counted rather than chosen: whichever
// records the rest of the schema hangs off ARE the ones a newcomer meets first,
// and that stays true as the schema moves.
const primaryEntityCount = 12

func renderArea(schema *emSchema, area string, tables []string, contract map[string]string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s tables\n\n%s\n\n", area, generatedBy)
	fmt.Fprintf(&b, "The %d table%s owned by `%s`, as the migrations build them. "+
		"[Back to the entity model](README.md).\n",
		len(tables), plural(len(tables)), area)
	sort.Strings(tables)
	for _, name := range tables {
		renderTable(&b, schema, schema.tables[name], contract)
	}
	return b.String()
}

func renderTable(b *strings.Builder, schema *emSchema, table *emTable, contract map[string]string) {
	fmt.Fprintf(b, "\n## %s\n\n", table.name)
	fmt.Fprintf(b, "%d column%s · %s · referenced by %d foreign key%s\n\n",
		len(table.columns), plural(len(table.columns)),
		primaryKeyPhrase(table.primaryKey), schema.inbound[table.name], plural(schema.inbound[table.name]))

	b.WriteString("| Column | Type | Required | What it is |\n|---|---|---|---|\n")
	for _, column := range sortedColumns(table) {
		fmt.Fprintf(b, "| `%s` | %s | %s | %s |\n",
			column.name, cell(typeCell(column)), yesOrBlank(column.notNull),
			cell(columnSentence(schema, table, column, contract)))
	}

	renderReferences(b, table)
	renderList(b, "Rules", append(append(append([]emConstraint{}, table.checks...), table.uniques...), table.others...))
	renderList(b, "Indexes", strippedIndexes(table))
	renderList(b, "Triggers", strippedTriggers(table))
}

// renderReferences prints the tables this one points at, which is the half of a
// relationship a reader following a column outwards needs.
func renderReferences(b *strings.Builder, table *emTable) {
	if len(table.foreignKeys) == 0 {
		return
	}
	b.WriteString("\n**Points at**\n\n| Columns | Table | When the parent goes |\n|---|---|---|\n")
	keys := append([]emConstraint{}, table.foreignKeys...)
	sort.Slice(keys, func(i, j int) bool { return keys[i].name < keys[j].name })
	for _, key := range keys {
		m := catalogForeignKey.FindStringSubmatch(key.def)
		if m == nil {
			continue
		}
		fmt.Fprintf(b, "| `%s` | `%s` | %s |\n", m[1], m[2], onDeleteMeaning(onDeleteOf(m[4])))
	}
}

func renderList(b *strings.Builder, heading string, items []emConstraint) {
	if len(items) == 0 {
		return
	}
	sorted := append([]emConstraint{}, items...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].name < sorted[j].name })
	fmt.Fprintf(b, "\n**%s**\n\n", heading)
	for _, item := range sorted {
		fmt.Fprintf(b, "- `%s`: `%s`\n", item.name, collapseDefinition(item.def))
	}
}

// strippedIndexes drops the part of every index definition that says what the
// reader already knows: which table it is on, and that it is an index.
func strippedIndexes(table *emTable) []emConstraint {
	out := make([]emConstraint, 0, len(table.indexes))
	for _, index := range table.indexes {
		def := index.def
		if at := strings.Index(def, " USING "); at >= 0 {
			def = def[at+len(" USING "):]
		}
		unique := ""
		if strings.HasPrefix(index.def, "CREATE UNIQUE") {
			unique = "unique, "
		}
		out = append(out, emConstraint{name: index.name, def: unique + def})
	}
	return out
}

// strippedTriggers drops the part of a trigger definition that repeats the
// name and the table the reader is already standing on.
func strippedTriggers(table *emTable) []emConstraint {
	out := make([]emConstraint, 0, len(table.triggers))
	for _, trigger := range table.triggers {
		def := strings.TrimPrefix(trigger.def, "CREATE CONSTRAINT TRIGGER ")
		def = strings.TrimPrefix(def, "CREATE TRIGGER ")
		def = strings.TrimPrefix(def, trigger.name+" ")
		def = strings.ReplaceAll(def, " ON public."+table.name+" ", " ")
		out = append(out, emConstraint{name: trigger.name, def: def})
	}
	return out
}

func renderIndex(schema *emSchema, owners map[string]string, byArea map[string][]string) string {
	var b strings.Builder
	b.WriteString("# Entity model\n\n" + generatedBy + "\n\n")
	b.WriteString(entityModelLede)
	renderShape(&b, schema, byArea)
	renderPrimary(&b, schema, owners)
	renderAreaIndex(&b, byArea)
	renderTableIndex(&b, schema, owners)
	return b.String()
}

func renderShape(b *strings.Builder, schema *emSchema, byArea map[string][]string) {
	columns, keys := 0, 0
	for _, table := range schema.tables {
		columns += len(table.columns)
		keys += len(table.foreignKeys)
	}
	fmt.Fprintf(b, "\n## The shape\n\n| | |\n|---|--:|\n| Tables | %d |\n| Columns | %d |\n"+
		"| Foreign keys | %d |\n| Owning areas | %d |\n",
		len(schema.tables), columns, keys, len(byArea))
}

// renderPrimary draws the records the rest of the schema hangs off.
func renderPrimary(b *strings.Builder, schema *emSchema, owners map[string]string) {
	primary := mostReferenced(schema, primaryEntityCount)
	fmt.Fprintf(b, "\n## The %d records everything else hangs off\n\n", len(primary))
	b.WriteString("Ranked by how many foreign keys point at them.\n\n")
	b.WriteString("| Record | Lives in | Columns | Foreign keys pointing at it |\n|---|---|--:|--:|\n")
	for _, name := range primary {
		area := areaOf(owners[name])
		fmt.Fprintf(b, "| [`%s`](%s.md#%s) | [%s](%s.md) | %d | %d |\n",
			name, area, name, area, area, len(schema.tables[name].columns), schema.inbound[name])
	}
	b.WriteString("\n```mermaid\nerDiagram\n")
	for _, child := range primary {
		// Sorted by the referring column: singleColumnFKs is a map, and Go
		// randomises a map walk, so an unsorted render would produce a
		// different page on every run and this gate would fail on its own
		// output rather than on a change to the schema.
		for _, column := range sortedKeys(schema.tables[child].singleColumnFKs) {
			fk := schema.tables[child].singleColumnFKs[column]
			if !contains(primary, fk.parent) || fk.parent == child {
				continue
			}
			fmt.Fprintf(b, "    %s ||--o{ %s : %s\n", fk.parent, child, fk.column)
		}
	}
	b.WriteString("```\n")
}

func renderAreaIndex(b *strings.Builder, byArea map[string][]string) {
	b.WriteString("\n## The pages\n\n| Area | Tables |\n|---|--:|\n")
	for _, area := range sortedKeys(byArea) {
		fmt.Fprintf(b, "| [%s](%s.md) | %d |\n", area, area, len(byArea[area]))
	}
}

func renderTableIndex(b *strings.Builder, schema *emSchema, owners map[string]string) {
	b.WriteString("\n## Every table\n\n| Table | Area | Columns | Referenced by |\n|---|---|--:|--:|\n")
	for _, name := range schema.tableNames() {
		area := areaOf(owners[name])
		fmt.Fprintf(b, "| [`%s`](%s.md#%s) | %s | %d | %d |\n",
			name, area, name, area, len(schema.tables[name].columns), schema.inbound[name])
	}
}

// mostReferenced is the n tables with the most inbound foreign keys, ties broken
// by name so the page does not churn on a reordering.
func mostReferenced(schema *emSchema, n int) []string {
	names := schema.tableNames()
	sort.SliceStable(names, func(i, j int) bool {
		if schema.inbound[names[i]] != schema.inbound[names[j]] {
			return schema.inbound[names[i]] > schema.inbound[names[j]]
		}
		return names[i] < names[j]
	})
	if len(names) > n {
		names = names[:n]
	}
	return names
}

// collapseDefinition makes a Postgres definition fit one line of a list item.
// The casts Postgres prints back are noise to a reader who knows the type.
func collapseDefinition(def string) string {
	flattened := strings.Join(strings.Fields(def), " ")
	for _, cast := range []string{"::text", "::character varying", "::jsonb", "::bpchar"} {
		flattened = strings.ReplaceAll(flattened, cast, "")
	}
	return strings.ReplaceAll(flattened, "`", "'")
}

// cell escapes what would otherwise end a markdown table cell early.
func cell(text string) string {
	return strings.ReplaceAll(strings.Join(strings.Fields(text), " "), "|", "\\|")
}

func plural(n int) string {
	if n == 1 {
		return ""
	}
	return "s"
}

func yesOrBlank(yes bool) string {
	if yes {
		return "yes"
	}
	return ""
}

func primaryKeyPhrase(key string) string {
	if key == "" {
		return "no primary key"
	}
	return "primary key `" + key + "`"
}
