// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

// The ratified cross-store writes, held apart from the walker that consults
// them: this file is the hand-maintained artifact and tableownership_test.go is
// the mechanism, and the two change for different reasons. It declares no test,
// so it is data rather than another gate.

package gates

import "github.com/margince/margince/backend/internal/shared/gatekit"

// crossStoreWrites are the ratified writes outside the writer's own tables,
// keyed "module-dir:table:file:receiver.func" — the write INSTANCE, so a second
// copy inside one package is ratified on its own evidence rather than riding the
// entry a sibling earned. Every entry carries its rationale inline so the gate
// is self-contained on a clean checkout.
var crossStoreWrites = gatekit.Waive(map[string]string{
	// The relay marks what it shipped, in the transaction that shipped it.
	"internal/platform/events:event_outbox:relay.go:Relay.relayBatch": "storekit WRITES the outbox row and the relay RETIRES it, which is the whole point of an outbox: the domain write and the publish are separate transactions, and marking published_at in the same transaction as the XADD is what makes a crash re-ship rather than lose. Moving it into storekit would put the shipping half inside the module seam that exists to know nothing about shipping",

	// people's merge/promotion relink rows across aggregates inside their
	// single transaction — the primary aggregate owns the single-tx
	// cross-aggregate write, because a merge that could half-commit its
	// relinks would corrupt referential history.
	"internal/modules/people:deal:merge_organization.go:absorbOrgReferences":                  "an org merge re-points the merged-away company's deal FK rows onto the survivor in the single merge transaction, because a merge that could half-commit its relinks would leave deals pointing at a company that no longer exists",
	"internal/modules/people:project:merge_organization.go:absorbOrgReferences":               "org merge re-anchors the merged-away company's projects onto the survivor in the same transaction (PROJ-LIFE-4) — the anchor is NOT NULL ... ON DELETE RESTRICT, so a project cannot stay behind, and leaving it turns the survivor's deals un-editable against the deal_project_same_org trigger",
	"internal/modules/people:activity_link:ensure.go:Store.linkActivityToPerson":              "the capture path's link INSERT, and the ONE point both the activity and the channel ensure reach — so it is where the person is settled against a merge before the row is written. Every step above it named its person from a read a merge can invalidate, and no reader of activity_link walks merged_into_id, so a link written to the retired id leaves the message on a record nobody opens",
	"internal/modules/people:activity_link:leadmerge.go:carryLeadActivitiesToLead":            "merge/promote relink timeline links in the single transaction",
	"internal/modules/people:activity_link:merge.go:relinkLinkRows":                           "merge/promote relink timeline links in the single transaction",
	"internal/modules/people:activity_link:promote.go:carryLeadActivities":                    "merge/promote relink timeline links in the single transaction",
	"internal/modules/people:attachment:merge_organization.go:absorbOrgReferences":            "org merge carries the document library's account pointer onto the survivor in the same transaction — organization_id is a denormalized READ path nothing else maintains, so a file left on the dissolved company is filed under a record that no longer exists and reads to a user as the contract having vanished",
	"internal/modules/people:activity_link:cohortpromote.go:linkCapturedCohort":               "the cohort form of linkActivityToPerson's link, for the orderings where the person arrives AFTER the mail — a backfill that meets the sender mid-run, a human typing the contact in, a verdict resolving a question the sender kept writing during. Bounded by the person's own live addresses and by mail linked to nobody, so it can only attach what a person-first ordering would already have attached",
	"internal/modules/people:activity_link:meetingcohort.go:linkAttendedMeetings":             "the same cohort link for MEETINGS, which linkCapturedCohort structurally cannot reach: that arm keys on counterparty_email and a meeting has none, because attendance is a list rather than a second party. Bounded to connector meetings this person is already a participant of, so it can only file what the capture path would have filed had the person existed first",
	"internal/modules/people:activity_participant:mergerelink.go:relinkParticipantRows":       "a merge moves who was IN a conversation, beside the activity_link rows that say how it is FILED — the two describe one message and a merge that moved only one of them left the other crediting a record no read returns. It belongs in the single merge transaction for the reason every other relink here does: a merge that could half-commit its satellites is worse than one that fails, because nothing errors and the rows are simply gone from view",
	"internal/modules/people:activity_participant:participant.go:promoteParticipantsToPerson": "capture records the counterparty by ADDRESS because no person exists yet — the creation gate runs after that transaction commits, and for a suppressed sender never runs at all. This is the ONE statement that names that party, at either width: pinned to one activity it is the capture path's own promotion, beside the link and in the same transaction; unpinned it repairs the cohort a person acquires by arriving after their mail. People owns it because settling the merge redirect and reading person_email is what the promotion is defined by, and activities can do neither without importing a sibling",
	"internal/modules/people:list_member:organizationarchive.go:Store.ArchiveOrganization":    "archiving a company purges its list memberships in the archive transaction — a membership outliving the record it points at is a list row that renders as a gap",
	"internal/modules/people:list_member:personarchive.go:archivePersonRows":                  "archiving a person purges their list memberships in the archive transaction — a membership outliving the record it points at is a list row that renders as a gap",
	"internal/modules/people:taggable:lead.go:Store.DisqualifyLead":                           "disqualifying a lead archives it and purges its tag rows in the same transaction, the same rule the company and person archives hold — and it is reachable now because an import files what it CREATES under one word, so an undone run archives the lead and a lead left tagged still answers a filter for the batch that was reversed",
	"internal/modules/people:taggable:organizationarchive.go:Store.ArchiveOrganization":       "archiving a company purges its tag rows in the archive transaction — a tag outliving the record it points at keeps the company reachable from a filter that should no longer find it",
	"internal/modules/people:taggable:personarchive.go:archivePersonRows":                     "archiving a person purges their tag rows in the archive transaction — a tag outliving the record it points at keeps the person reachable from a filter that should no longer find them",
	"internal/modules/people:person_consent:consentcarry.go:dropCollidingConsent":             "merge carries the survivor's consent state in the single transaction",
	"internal/modules/people:person_consent:consentcarry.go:flipCarriedWithdrawals":           "merge carries the survivor's consent state in the single transaction",
	"internal/modules/people:person_consent:consentcarry.go:repointCarriedConsent":            "merge carries the survivor's consent state in the single transaction",
	"internal/modules/people:person_confirm_submission:mergerelink.go:relinkPersonReferences": "a person merge carries the merged-away contact's confirm-page submissions onto the survivor in the single merge transaction. What these rows hold is a request the workspace still owes an answer to — a correction the subject typed, or their asking to be removed — and the survivor's queue is the only place a rep will ever read one. Left on the retired record it hangs off a row no read returns, which is a data subject's request quietly dropped rather than refused",
	"internal/modules/people:consent_event:consentcarry.go:carryConsent":                      "merge re-points the append-only consent proof log in the single transaction",
	"internal/modules/people:consent_event:consentcarry.go:flipCarriedWithdrawals":            "merge re-points the append-only consent proof log in the single transaction",
	// The outbound-send reconcile folds the provider's own captured echo of a
	// message this workspace sent into the send's own row. That fold is one
	// indivisible act — links copied, review moved, key released, row archived
	// — run in one best-effort transaction the delivery store may roll back
	// whole. The queued counterparty review is part of it: a human verdict the
	// survivor does not re-queue, which must not be left asking about a message
	// the workspace can no longer see.
	"internal/modules/activities:capture_pending_counterparty:messageidentity.go:repointEchoReviews": "the message-identity absorb re-points the archived echo's queued counterparty dispositions onto the surviving send, in the same transaction as the rest of the fold — a sibling call would have to write on this very transaction anyway, so routing it through capture would buy a hop and no isolation, while splitting the fold across two owners would let half of it survive a rollback",
	// capture is the ONE connector.Sink (interfaces.md §1): one transaction
	// per inbound record writes raw original + normalized domain row, so a
	// crash can never keep evidence without the record or vice versa.
	"internal/modules/capture:activity:sinkactivity.go:Sink.upsertActivity":                           "the connector sink materializes the normalized activity in the same transaction as its raw_capture original",
	"internal/modules/capture:activity:sinkaudience.go:limitLinkLessAudience":                         "the connector sink narrows a materialized activity's audience in the same ingest transaction — the audience is decided from what the ingest saw, and a row committed at the wider setting is readable by people the narrowing was meant to exclude",
	"internal/modules/capture:activity:sinkproject.go:linkActivityToProject":                          "the connector sink stamps the materialized activity's project attribution in the same ingest transaction, so the row is never briefly attributed to nothing",
	"internal/modules/capture:activity_link:sinkactivity.go:Sink.linkActivity":                        "the connector sink links the materialized activity in the same ingest transaction",
	"internal/modules/capture:activity_link:sinkproject.go:linkActivityToProject":                     "the connector sink links the materialized activity in the same ingest transaction",
	"internal/modules/capture:activity_participant:purgeselect.go:ReleaseImportTx":                    "the reverse of the stamp below, and it has to be reversible in the same place for the same reason: a purge releases this seat's claim on a message a colleague also imported, which means removing exactly the two rows capture wrote when it imported it — the import row and the participant row. Splitting the pair across two modules would let one be deleted and the other survive, leaving a seat readable on mail they asked to be rid of or counted as a participant of a message they no longer import",
	"internal/modules/capture:activity_participant:purgeselect.go:ReleaseEveryImportTx":               "ReleaseImportTx's sibling for a message that was DESTROYED rather than released, and it is here on its own evidence rather than the other's: a workspace purge empties the activity for everybody, so leaving the import and participant rows behind gives every colleague a claim on mail the workspace was told is gone — a stub on their timeline that nothing else would ever collect. It removes exactly the two rows capture wrote when it imported the message, and it must stay paired with them for the same reason ReleaseImportTx does: splitting the pair across two modules lets one be deleted and the other survive. It differs by being keyed on the ACTIVITY alone rather than on a seat, which is right only because there is no surviving copy for anybody to hold a claim on",
	"internal/modules/capture:activity_link:sinkmeetinglinks.go:Sink.linkResolvedMeetingParticipants": "a meeting names no counterparty, so the ensure that files mail never runs for one and a synced meeting landed with no link at all — unreachable from every page that finds activity through activity_link. The people are already resolved on the participant rows this same transaction wrote, and the filing must be IN that transaction because the audience a link-less record is born with is decided there too",
	"internal/modules/capture:activity_participant:participant.go:StampFurtherParticipants":           "the connector principal is the ONLY place the mailbox owner is known (capture_connection is per-user-per-provider); by the time any other module sees the activity its captured_by reads connector:gmail and the human behind it is unrecoverable, so the participant rows commit in the same ingest transaction as the activity they describe",
	"internal/modules/capture:activity_participant:participant.go:insertParticipant":                  "the connector principal is the ONLY place the mailbox owner is known (capture_connection is per-user-per-provider); by the time any other module sees the activity its captured_by reads connector:gmail and the human behind it is unrecoverable, so the participant rows commit in the same ingest transaction as the activity they describe",
	"internal/modules/capture:lead:sinklead.go:Sink.upsertLead":                                       "the connector sink materializes inbound leads in the same transaction as their raw_capture original",
	// deals' archive purges the archived deal's collection memberships in
	// the same transaction — a dangling list/tag row would resurrect the
	// deal in segment queries.
	"internal/modules/deals:list_member:dealarchive.go:Store.ArchiveDeal":  "archiving a deal removes its list memberships in the archive transaction",
	"internal/modules/deals:taggable:dealarchive.go:Store.ArchiveDeal":     "archiving a deal removes its tag rows in the archive transaction",
	"internal/modules/deals:relationship:dealarchive.go:Store.ArchiveDeal": "archiving a deal archives its stakeholder relationships in the archive transaction — a live relationship to an archived deal would leak it into row-scope walks",
	// The project's archive carries the same three, for the same reasons: the
	// edges are attributes of the grouping being archived, and each must go in
	// the SAME transaction or a reader sees a live edge to a record that no
	// longer exists.
	"internal/modules/projects:list_member:project.go:Store.ArchiveProject":  "archiving a project removes its list memberships in the archive transaction",
	"internal/modules/projects:taggable:project.go:Store.ArchiveProject":     "archiving a project removes its tag rows in the archive transaction",
	"internal/modules/projects:relationship:project.go:Store.ArchiveProject": "archiving a project archives its stakeholder relationships in the archive transaction — a live relationship to an archived project would leak it into row-scope walks",
	// privacy is the module whose JOB is crossing stores: a data-subject
	// obligation (erasure Art. 17, retention ADR-0011) must reach every
	// table holding the subject in ONE transaction per record — the
	// sanctioned single-transaction exception; routing each purge
	// through the owning module's API would trade the atomicity that IS
	// the guarantee for boundary hygiene.
	"internal/modules/privacy:person:erasure.go:anonymizeSubjectRows":                                        "erasure/retention anonymize the person row in place in the single erasure transaction (Art. 17)",
	"internal/modules/privacy:person:retentionactions.go:anonymizePersonRecord":                              "erasure/retention anonymize the person row in place in the single erasure transaction (Art. 17)",
	"internal/modules/privacy:deal_room_participant:erasuredealroom.go:anonymizeDealRoomSeats":               "erasure anonymizes the subject's Deal Room seat in place — the one named outside person stored without a person row — in the single erasure transaction",
	"internal/modules/privacy:deal_room_session:erasuredealroom.go:purgeDealRoomSeatTraces":                  "erasure deletes the erased subject's live room credentials in the same transaction: access they did not consent to keep must not outlive the request",
	"internal/modules/privacy:deal_room_engagement:erasuredealroom.go:purgeDealRoomSeatTraces":               "erasure deletes the erased subject's room activity trail (when they signed in, what they took) in the same transaction",
	"internal/modules/privacy:person_email:erasure.go:deleteSubjectIdentifierRows":                           "erasure deletes the subject's email channel rows in the single erasure transaction",
	"internal/modules/privacy:person_email:retentionactions.go:anonymizePersonRecord":                        "the person/anonymize action deletes the subject's address rows in the same transaction, so the record stops naming them by any key it is resolved on — an address left behind re-identifies the row it was stripped from",
	"internal/modules/privacy:preference_token:erasure_consent.go:deleteConsentCapabilities":                 "erasure deletes the subject's preference-center token in the single erasure transaction — it is a live capability over their consent record on a session-less edge, and anonymize-in-place means 0048's ON DELETE CASCADE never fires, so an erased subject would keep accruing consent rows through the capability the erasure certifies destroyed",
	"internal/modules/privacy:consent_doi_token:erasure_consent.go:deleteConsentCapabilities":                "erasure deletes the subject's double-opt-in token in the same transaction and for the same reason as the preference-center token beside it — a bearer secret in their mailbox whose only function is to authorise a grant, which anonymize-in-place would otherwise leave live for its full 72 hours after the erasure certified the data destroyed",
	"internal/modules/privacy:confirm_token:erasure_consent.go:deleteConsentCapabilities":                    "erasure deletes the confirm-details link beside the two capabilities above, and this is the strongest of the three: the link does not merely authorise a grant, it DISPLAYS the record. Anonymize-in-place leaves the person row standing, so ON DELETE CASCADE never fires and an erased subject would hold a working view of data the installation certified destroyed",
	"internal/modules/privacy:comms_outbound:erasure_payloads.go:erasePayloads":                              "erasure clears the vault reference on the subject's controller deliveries, in the same transaction and immediately AFTER destroying the material it names. The order is the reason this write exists here rather than in the column scrub beside it: the reference lives in the row, so nulling it first would orphan a live confirmation link in the vault with no key left to find it, and a failure between the two would roll back with the reference intact so a retry is idempotent",
	"internal/modules/privacy:person_acquisition_evidence:erasure.go:anonymizeSubjectRows":                   "erasure deletes the record of why this contact existed, in the single erasure transaction. It records what the person did or what was done to obtain them, and has no meaning after them — so it goes with the addresses beside it rather than being tombstoned like a decision, which is the controller's own evidence about a send. A merge MOVES these rows onto the survivor rather than copying them, so the delete by person_id reaches whichever record the subject now is",
	"internal/modules/privacy:person_acquisition_evidence:retentionactions.go:clearCommunicationRecord":      "the person/anonymize action deletes the same rows in the same transaction, because both acts must clear the same tables: one that cleared it and one that did not would leave the subject's acquisition record standing after an operator was told the person had been anonymized",
	"internal/modules/privacy:communication_decision:erasure_consent.go:deleteConsentCapabilities":           "erasure tombstones the recipient address and cuts the subject link on the authorization decisions in the single erasure transaction. It UPDATEs rather than deletes, and that is the whole reason it lives here: the row is the controller's own Art. 5(2) record of why a message was permitted, so destroying it would erase the evidence that sends already made were lawful, while leaving the address would keep the erased mailbox readable on every decision it appears in",
	"internal/modules/privacy:communication_basis:erasure_consent.go:deleteConsentCapabilities":              "erasure deletes the subject's non-consent bases in the same transaction — each row exists only to say something about THIS person (they wrote to us on a date, in a thread), so unlike the decision beside it a basis has no life after the subject and anonymize-in-place would leave it naming a thread and a person who asked to be forgotten",
	"internal/modules/privacy:communication_suppression:erasure_consent.go:deleteConsentCapabilities":        "erasure deletes the subject's objections and restrictions in the same transaction, for the reason the bases go: a suppression is a statement about one person. It is safe to delete precisely because the person row is going too — a suppression outliving its subject could only ever match a future record that happened to reuse the address, which is somebody else",
	"internal/modules/privacy:person_confirm_submission:erasure_consent.go:deleteConsentCapabilities":        "the same transaction deletes what came back through that link — the subject's own name and address as they proposed them. Not a capability but subject data, and data the workspace was asked to hold rather than anything it agreed: an unaccepted proposal surviving an erasure is the subject's plaintext outliving the request to destroy it",
	"internal/modules/privacy:confirm_token:retentionactions.go:anonymizePersonRecord":                       "the person/anonymize action deletes the confirm link for the reason it deletes the opt-in token beside it, and more urgently: a live link would show an old mailbox the very fields this action has just emptied",
	"internal/modules/privacy:person_confirm_submission:retentionactions.go:anonymizePersonRecord":           "and the submissions with it — they hold the subject's name and address in plaintext, which is exactly the content the anonymization above just cleared from the person row",
	"internal/modules/privacy:communication_decision:retentionactions.go:clearCommunicationRecord":           "the person/anonymize action tombstones the recipient address and cuts the subject link on the authorization decisions, exactly as the eraser does. Both acts must clear the same tables or a subject anonymized rather than erased keeps their address on every decision naming them, after an operator was told the record was anonymized. The row survives in both because it is the controller's Art. 5(2) evidence that a send already made was lawful",
	"internal/modules/privacy:communication_basis:retentionactions.go:clearCommunicationRecord":              "the same action deletes the subject's non-consent bases, for the reason the eraser deletes them: a basis names a thread and a date and says why writing to THIS person was lawful. An anonymized subject who returns arrives as a new record, so a surviving basis would authorize writing to them on the strength of a conversation nobody can now identify",
	"internal/modules/privacy:communication_suppression:retentionactions.go:clearCommunicationRecord":        "and the suppressions with them. The suppression LIST is the separate mechanism that keeps an anonymized subject from being re-contacted; a per-person objection left attached to a record that no longer names anybody protects nobody and would only ever match a future record reusing the address, which is somebody else",
	"internal/modules/privacy:consent_doi_token:retentionactions.go:anonymizePersonRecord":                   "the person/anonymize action deletes the subject's opt-in tokens in the same transaction: an anonymized subject may lawfully return, but they return by being invited again, not by an old token in an old mailbox still working",
	"internal/modules/privacy:activity_participant:erasure_graph.go:subjectParticipantsBlank":                "erasure nulls the subject's person and address arms on the interaction participants in the single erasure transaction — the address arm exists precisely for a party who never became a record, so it survives the person_email purge and would keep the erased address readable and re-matchable; the ROW is kept where other participants remain, because the other people in that conversation are not the subject",
	"internal/modules/privacy:activity_participant:erasure_graph.go:subjectParticipantsDelete":               "erasure nulls the subject's person and address arms on the interaction participants in the single erasure transaction — the address arm exists precisely for a party who never became a record, so it survives the person_email purge and would keep the erased address readable and re-matchable; the ROW is kept where other participants remain, because the other people in that conversation are not the subject",
	"internal/modules/privacy:activity_participant:retention_graph.go:scrubPersonGraphTraces":                "the nightly retention sweep nulls the subject's person and address arms on the interaction participants, inside the retention engine's per-record transaction — the address arm exists for a party who never became a record, so it survives the person_email purge and would keep the swept address readable and re-matchable; the ROW is kept where other participants remain, because the other people in that conversation are not the subject",
	"internal/modules/identity:linkedin_connection:users.go:Service.revokeBorrowedAuthority":                 "deactivation deletes the departing user's imported LinkedIn network in the single deactivation transaction — it is their private address book of third parties whose only tie to this installation was that person's employment, so it cannot outlive the employment; doing it here keeps it atomic with the session and passport revocation rather than leaving a window in which the account is gone and the address book is not",
	"internal/modules/privacy:weekly_plan_commitment:erasure_commitments.go:redactCommitmentsNaming":         "erasure redacts what a colleague wrote about the subject on their own weekly plan, in the single erasure transaction. The link accepts 'person', so a rep can commit to an action about a contact and type a free-text label, help request and manager answer naming them — and no other clause in the cascade can see those rows: the table carries no person FK for a schema cascade to walk and is keyed to the app_user who wrote it rather than to the subject. Redacted rather than deleted, because the ROW is the rep's work record and the erasure request is the contact's: it reaches the contact's data and stops at the employee's record of having worked",
	"internal/modules/privacy:linkedin_connection:erasure_graph.go:deleteSubjectLinkedInGhosts":              "erasure deletes the subject's LinkedIn ghosts in the single erasure transaction — a ghost holds the subject's name, employer and address, imported from a colleague's export without the subject ever being asked, and it is invisible to every person-keyed clause because a ghost is not a person row",
	"internal/modules/privacy:graph_interaction_edge:erasure_graph.go:deleteSubjectInteractionEdges":         "erasure drops the subject's interaction edges in the single erasure transaction rather than leaving it to the cg:graph-edge consumer — an Art. 17 obligation discharged by an event is one that fails silently when the bus is behind, and the projection holds who corresponded with the subject, how often and how recently",
	"internal/modules/privacy:graph_interaction_edge:retention_graph.go:scrubPersonGraphTraces":              "the nightly retention sweep drops the subject's interaction edges inside the retention engine's per-record transaction — an edge names who spoke to whom, so it re-identifies the swept party from the graph alone",
	"internal/modules/privacy:graph_contact_edge:erasure_graph.go:deleteSubjectInteractionEdges":             "erasure drops the subject's contact↔contact edges, both endpoint columns, in the single erasure transaction — the same Art. 17 reasoning as the interaction projection above, and the far-end column is the copy-paste that would otherwise be missed",
	"internal/modules/privacy:graph_contact_edge:retention_graph.go:scrubPersonGraphTraces":                  "the nightly retention sweep drops the swept party's contact↔contact edges on either end inside the per-record transaction — the pair re-identifies them from the graph alone whichever side they stand on",
	"internal/modules/privacy:capture_pending_counterparty:erasure.go:deleteSubjectIdentifierRows":           "erasure drops the capture dispositions keyed on the subject's own address in the single erasure transaction — left behind, they would keep the erased address readable and still answering the capture gates",
	"internal/modules/privacy:capture_pending_counterparty:retentionactions.go:anonymizePersonRecord":        "the person/anonymize action drops the capture discovery rows in the same transaction — a pending counterparty is the subject's address waiting to become a record, so leaving it re-mints them on the next ingest",
	"internal/modules/privacy:person_social:erasure.go:deleteSubjectIdentifierRows":                          "erasure and retention delete the subject's social-handle rows in the same anonymization transaction",
	"internal/modules/privacy:person_social:retentionactions.go:anonymizePersonRecord":                       "erasure and retention delete the subject's social-handle rows in the same anonymization transaction",
	"internal/modules/privacy:voice_learning_signal:retentionai.go:RetentionService.eraseVoiceSignalContent": "the nightly retention sweep erases over-age draft plaintext in place; the counters row survives (voice_draftread.go stamps the per-row deadline)",
	"internal/modules/privacy:person_phone:erasure.go:deleteSubjectIdentifierRows":                           "erasure deletes the subject's phone channel rows in the single erasure transaction",
	"internal/modules/privacy:person_phone:retentionactions.go:anonymizePersonRecord":                        "the person/anonymize action deletes the subject's phone rows in the same transaction, so the record stops naming them by any key it is resolved on",
	"internal/modules/privacy:person_channel_identity:erasure_channels.go:eraseChannelIdentities":            "erasure and the retention anonymizer delete the subject's channel-identity rows in the single erasure/per-record transaction — the identity is the key an inbound message would re-bind them by, so it has to go in the same commit that hashes it onto the suppression list",
	"internal/modules/privacy:person_channel_identity:retentionactions.go:anonymizePersonRecord":             "erasure and the retention anonymizer delete the subject's channel-identity rows in the single erasure/per-record transaction — the identity is the key an inbound message would re-bind them by, so it has to go in the same commit that hashes it onto the suppression list",
	"internal/modules/privacy:lead:erasure_leadtwins.go:anonymizeLeadTwins":                                  "erasure/retention anonymize the subject's segregated lead rows in the same transaction",
	"internal/modules/privacy:lead:retentionactions.go:RetentionService.anonymizeLead":                       "erasure/retention anonymize the subject's segregated lead rows in the same transaction",
	"internal/modules/privacy:lead_score_history:erasure_leadtwins.go:anonymizeLeadTwins":                    "the score's explanation is about the subject: its factors embed the ids of activities they took part in, inside JSON no field-level scrub reaches, and the lead is ANONYMIZED rather than deleted so nothing cascades",
	"internal/modules/privacy:lead_score_history:retentionactions.go:RetentionService.anonymizeLead":         "the score's explanation is about the subject: its factors embed the ids of activities they took part in, inside JSON no field-level scrub reaches, and the lead is ANONYMIZED rather than deleted so nothing cascades",
	"internal/modules/privacy:lead_manual_signal:erasure_leadtwins.go:anonymizeLeadTwins":                    "a manual scoring signal is a colleague's written judgement about the subject, carrying their name — it cannot outlive the record it judges, and the anonymize fires no cascade",
	"internal/modules/privacy:lead_manual_signal:retentionactions.go:RetentionService.anonymizeLead":         "a manual scoring signal is a colleague's written judgement about the subject, carrying their name — it cannot outlive the record it judges, and the anonymize fires no cascade",
	"internal/modules/privacy:activity:erasure_restrict.go:restrictShieldedTimeline":                         "a restriction shields a timeline row instead of destroying it (Art. 18): the content stays, readable by nobody, until the hold lifts — so the restriction must be stamped in the same transaction that decided it, or a row is briefly readable after the decision that shielded it",
	"internal/modules/privacy:activity:erasure_restrict.go:stampLegacyHandelsbriefe":                         "commercial correspondence carries a statutory retention floor that outranks an erasure request, and the floor is stamped onto the row in the erasure's own transaction — an unstamped Handelsbrief is one the next sweep destroys",
	"internal/modules/privacy:activity:erasuretimeline.go:redactSubjectTimeline":                             "Art. 17 redaction nulls the subject's timeline content in the single erasure transaction — a timeline row is other people's record too, so it is redacted in place rather than deleted",
	"internal/modules/privacy:activity:restrictionoverride.go:Eraser.PinToFloor":                             "a controller pinning a record to its retention floor writes the hold onto the activity in the deciding transaction — the pin IS the decision, and a gap between them is a window in which the sweep can still take the row",
	"internal/modules/privacy:activity:retentionactions.go:RetentionService.archiveActivity":                 "the time-based sweep archives an activity that has outlived its class, inside the retention engine's per-record transaction",
	"internal/modules/privacy:activity:retentionactions.go:RetentionService.eraseActivityContent":            "the time-based sweep nulls an expired activity's content in the retention engine's per-record transaction, leaving the timeline row other people still need",
	"internal/modules/privacy:activity:retentionrestricted.go:liftAndEraseHeldRecord":                        "a restriction expiring is the one moment a held row may be destroyed, and the lift and the erasure are ONE statement because the data-layer guard admits nothing else — a lift that left the body readable would undo the restriction and keep the data",
	"internal/modules/privacy:activity_retention_evidence:erasure_restrict.go:stampLegacyHandelsbriefe":      "Art. 17 erasure stamps a Handelsbrief captured before the stamp writer existed, and writes the evidence its restriction rests on, in the single erasure transaction — the guard refuses a restriction with no evidence behind it, and for a pre-stamp row the deal links the erasure reads are the only evidence there is",
	"internal/modules/privacy:activity_retention_evidence:restrictionoverride.go:recordPinEvidence":          "Art. 17 erasure stamps a Handelsbrief captured before the stamp writer existed, and writes the evidence its restriction rests on, in the single erasure transaction — the guard refuses a restriction with no evidence behind it, and for a pre-stamp row the deal links the erasure reads are the only evidence there is",
	"internal/modules/privacy:attachment:erasure_attachments.go:Eraser.eraseAttachments":                     "Art. 17 erasure deletes attachments hung off the subject or a subject-only activity in the single erasure transaction",
	"internal/modules/privacy:deal:retentionactions.go:RetentionService.archiveDeal":                         "retention archives over-age lost deals per its audited per-record transaction",
	"internal/modules/privacy:embedding:erasure.go:purgePersonDerivedRows":                                   "erasure/retention purge the subject's vectors — a similarity probe must not reconstruct erased text",
	"internal/modules/privacy:embedding:erasure.go:purgeRedactedActivityTraces":                              "erasure/retention purge the subject's vectors — a similarity probe must not reconstruct erased text",
	"internal/modules/privacy:embedding:erasure_restrict.go:holdShieldedTimeline":                            "erasure/retention purge the subject's vectors — a similarity probe must not reconstruct erased text",
	"internal/modules/privacy:embedding:erasuretimeline.go:subjectActivityEmbeddingsDelete":                  "erasure/retention purge the subject's vectors — a similarity probe must not reconstruct erased text",
	"internal/modules/privacy:embedding:restrictionoverride.go:pinnedRecordLeavesDerivedCopies":              "erasure/retention purge the subject's vectors — a similarity probe must not reconstruct erased text",
	"internal/modules/privacy:embedding:retentionactions.go:RetentionService.anonymizeLead":                  "erasure/retention purge the subject's vectors — a similarity probe must not reconstruct erased text",
	"internal/modules/privacy:embedding:retentionactions.go:anonymizePersonRecord":                           "erasure/retention purge the subject's vectors — a similarity probe must not reconstruct erased text",
	"internal/modules/privacy:embedding:activitycontenterasure.go:Eraser.purgeContentDerivedFrom":            "erasure/retention purge the subject's vectors — a similarity probe must not reconstruct erased text",
	"internal/modules/activities:embedding:capturenoise.go:Store.RedactCapturedNoiseTx":                      "the ADR-0072 noise redaction drops the vectors built from the mail it just nulled, in the same transaction — an embedding of redacted text is that text in another shape, and leaving it would let a similarity probe reconstruct what the workspace decided not to retain. Same obligation as the privacy waiver above, at the other place content is destroyed; the embed lane cannot do it itself because it never observes an archived row",
	"internal/modules/activities:embedding:audienceretraction.go:RetractDerivedForActivityTx":                "narrowing a message's audience drops the vector built from it, in the same transaction as the narrowing. The obligation is the sibling of the noise redaction above and the reason is the same shape: an embedding is the message's text in another shape, it is built as the system principal over the whole workspace and queried by everyone, so leaving it lets a similarity probe reach a message the narrowing just withheld. The embed lane cannot do it itself — its query returns no row for a narrowed message, and no row means 'nothing to index', never 'delete what is there'",
	"internal/modules/privacy:capture_trace:erasuretimeline.go:purgeDerivedTraces":                           "erasure deletes the subject's rows from the 24-hour capture trace in the single erasure transaction, beside raw_capture and ai_call_payload above. The trace's sweep bounds exposure to a day; it does not ANSWER a request made inside that day, and an erasure honoured everywhere except one diagnostic table is not honoured. Only the payload columns can name anybody, and on the default posture they DO: capture.trace_payloads ships on, because a trace naming nobody cannot say why a message went missing. So this statement is the one that carries the erasure for a table that normally holds identifiers, rather than a precaution against a posture few installations choose. Exact equality rather than the ILIKE its neighbours use, because this column is written normalized and indexed",
	"internal/modules/privacy:capture_trace:erasure_channels.go:purgeChannelCaptureTrace":                    "the OTHER half of the same erasure, and a separate waiver because the key names the function. The lane above matches an ADDRESS; a counterparty the pipeline knew by a provider account is named in the trace by their display name instead (capture/trace.go, traceChannelPayload), so a subject who only ever wrote from a channel had every trace row survive an erasure that reported success. Scoped to the providers the subject is actually bound on, so it cannot reach a same-named person on a transport they never used. It lives in privacy rather than capture for the same reason its sibling does: the erasure is one transaction, and a cascade that left one table to another module's scheduler would be a cascade with a gap in it",
	"internal/modules/privacy:raw_capture:erasure_channels.go:purgeChannelRawCapture":                        "erasure purges raw provider payloads carrying the subject's identifiers in the single erasure transaction",
	"internal/modules/privacy:raw_capture:erasuretimeline.go:purgeDerivedTraces":                             "erasure purges raw provider payloads carrying the subject's identifiers in the single erasure transaction",
	"internal/modules/privacy:person_profile_field:erasure.go:purgePersonDerivedRows":                        "Art. 17 and the retention sweep delete the subject's enrichment sidecar inside the single erasure transaction, beside field_provenance and ai_feedback: anonymize-in-place leaves the person row standing, so nothing cascades here, and the row holds the subject's title and employer with the verbatim sentence naming them",
	"internal/modules/privacy:person_profile_field:retentionactions.go:anonymizePersonRecord":                "Art. 17 and the retention sweep delete the subject's enrichment sidecar inside the single erasure transaction, beside field_provenance and ai_feedback: anonymize-in-place leaves the person row standing, so nothing cascades here, and the row holds the subject's title and employer with the verbatim sentence naming them",
	"internal/modules/privacy:person_provider_claim:erasure_provider.go:purgeProviderPurchases":              "Art. 17 and the retention sweep delete what a licensed data provider asserted about the subject, inside the single erasure transaction and for the same reason person_profile_field is here: anonymize-in-place leaves the person row standing, so nothing cascades, and a claim IS the purchased value — a bought email and employer would otherwise sit on the page beside an \"Erased Subject\" name. Deleted rather than nulled, because a claim nulled in place is a row asserting something about a person nobody may now assert anything about",
	"internal/modules/privacy:person_provider_claim:retentionactions.go:purgeSubjectPurchases":               "Art. 17 and the retention sweep delete what a licensed data provider asserted about the subject, inside the single erasure transaction and for the same reason person_profile_field is here: anonymize-in-place leaves the person row standing, so nothing cascades, and a claim IS the purchased value — a bought email and employer would otherwise sit on the page beside an \"Erased Subject\" name. Deleted rather than nulled, because a claim nulled in place is a row asserting something about a person nobody may now assert anything about",
	"internal/modules/privacy:provider_applied_field:erasure_provider.go:purgeProviderPurchases":             "the same erasure, one table over: what a purchase FILLED on the record, deleted beside the claims that carried it. The row keeps the value it wrote for a plain column — the title, the profile URL — because the revert has nothing else to recognise its own value by, so it is subject data and cannot outlive the subject. Anonymize-in-place leaves the person row standing, so the foreign key's cascade never fires and this statement is what removes them",
	"internal/modules/privacy:provider_applied_field:retentionactions.go:purgeSubjectPurchases":              "the retention sweep's half of the same delete, for the same reason: a bought title left in this table would name an \"Erased Subject\" and still say what their job was",
	"internal/modules/privacy:provider_run:erasure_provider.go:purgeProviderPurchases":                       "the same two paths scrub the runs that bought that data, using storekit.ScrubProviderRunColumns — the SAME six-column clause integrations' own delete-data action uses, shared precisely because the two drifted once and the erasure cleaned less than the settings toggle did. It is a scrub and not a delete on purpose: the row stops naming anybody while the spend it records survives, because what the installation paid is an accounting fact about the installation once it names no one (PI-AC-8), and that is what keeps a spend history stable across an erasure",
	"internal/modules/privacy:provider_run:retentionactions.go:purgeSubjectPurchases":                        "the same two paths scrub the runs that bought that data, using storekit.ScrubProviderRunColumns — the SAME six-column clause integrations' own delete-data action uses, shared precisely because the two drifted once and the erasure cleaned less than the settings toggle did. It is a scrub and not a delete on purpose: the row stops naming anybody while the spend it records survives, because what the installation paid is an accounting fact about the installation once it names no one (PI-AC-8), and that is what keeps a spend history stable across an erasure",
	"internal/modules/people:provider_run:mergerelink.go:relinkProviderPurchases":                            "the person merge relinks the merged-away record's runs onto the survivor, and must decide the collision between two live runs where the unique index admits only one. It happens inside the merge transaction because that is the only place both person ids and both sides' run states are known at once; integrations cannot see a merge and people cannot hand the decision over mid-transaction. The write touches person_id, state and input_fingerprint only — never a reservation, never a credit — and the rule it enforces is integrations' own: a run past `queued` may have been paid for, so it is re-fingerprinted out of the live-run index rather than cancelled, the same idiom markSkipped uses",
	"internal/modules/privacy:ai_feedback:erasure_leadtwins.go:anonymizeLeadTwins":                           "Art. 17 deletes the subject's correction ledger inside the single erasure transaction, exactly as it does field_provenance beside it: the ledger holds a human-typed value ABOUT the subject, and a claim nobody may now assert anything about has nothing left to suppress",
	"internal/modules/privacy:ai_feedback:erasure.go:purgePersonDerivedRows":                                 "Art. 17 deletes the subject's correction ledger inside the single erasure transaction, exactly as it does field_provenance beside it: the ledger holds a human-typed value ABOUT the subject, and a claim nobody may now assert anything about has nothing left to suppress",
	"internal/modules/privacy:ai_feedback:retentionactions.go:anonymizePersonRecord":                         "the person/anonymize action deletes the verdicts recorded about the subject in the same transaction — a verdict carries the corrected VALUE a human typed, which is the subject's own data in a table nothing else on this path reaches",
	"internal/modules/privacy:ai_call_payload:erasuretimeline.go:purgeDerivedTraces":                         "erasure purges captured AI payloads mentioning the subject's identifiers, and retention ages every payload out at 365d — the special-category-adjacent content, deleted in the single erasure/per-record transaction while the ai_call metadata row survives",
	"internal/modules/privacy:ai_call_payload:retentionactions.go:RetentionService.erasePayload":             "erasure purges captured AI payloads mentioning the subject's identifiers, and retention ages every payload out at 365d — the special-category-adjacent content, deleted in the single erasure/per-record transaction while the ai_call metadata row survives",
	"internal/modules/privacy:ai_call:retentionai.go:RetentionService.eraseEmbedCall":                        "retention erases embedding-kind ai_call trace rows past their fixed 90-day cap (spec §4) in the single erasure/per-record transaction — a fixed operational cap, not an admin-editable retention_policy row",
	"internal/modules/consent:retention_policy:retention.go:SeedDefaultRetentionTx":                          "bootstrap plants the DM-SEED-1..6 defaults inside the workspace-creation transaction, beside the consent purposes it ships with, so a new installation is compliant before it serves a request. Boot-time only and one row per scope — the table's store, its RBAC gate and every runtime write live in privacy, which owns it",
	"internal/modules/privacy:communication_decision:erasure_leadtwins.go:anonymizeLeadTwins":                "the lead arm of the same tombstone the person arm applies in erasure_consent.go. A decision written while the subject was still a lead carries subject_kind='lead', which the person-keyed statement cannot see — and this is an ANONYMIZE, so the lead row survives and no cascade fires. Left alone the row keeps a live recipient address and a lead id that still points at the erased person",
	"internal/modules/privacy:communication_basis:erasure_leadtwins.go:anonymizeLeadTwins":                   "the lead arm of the basis delete beside it, in the same statement as the four per-lead scrubs above, and for the reason they are there: the lead row is anonymized rather than deleted, so ON DELETE CASCADE never fires and a basis naming the lead would outlive the erasure",
	"internal/modules/privacy:communication_suppression:erasure_leadtwins.go:anonymizeLeadTwins":             "and the lead's suppressions with them, same statement and same reason — safe to delete here because the eraser hashes every address onto erasure_suppression, so the subject cannot be re-captured at all",
	"internal/modules/privacy:field_provenance:erasure_leadtwins.go:anonymizeLeadTwins":                      "Art. 17 erasure deletes the subject's field-origin metadata in the single erasure transaction — provenance must not outlive the fields it annotates",
	"internal/modules/privacy:field_provenance:erasure.go:purgePersonDerivedRows":                            "Art. 17 erasure deletes the subject's field-origin metadata in the single erasure transaction — provenance must not outlive the fields it annotates",
	"internal/modules/privacy:field_provenance:erasuretimeline.go:redactSubjectTimeline":                     "Art. 17 erasure deletes the subject's field-origin metadata in the single erasure transaction — provenance must not outlive the fields it annotates",
	"internal/modules/privacy:field_provenance:retentionactions.go:anonymizePersonRecord":                    "the person/anonymize action deletes the field-level provenance in the same transaction — provenance records what each stripped field used to hold and who put it there, so it outlives the value it describes unless it goes with it",
	"internal/modules/privacy:field_provenance:activitycontenterasure.go:Eraser.purgeContentDerivedFrom":     "Art. 17 erasure deletes the subject's field-origin metadata in the single erasure transaction — provenance must not outlive the fields it annotates",
	"internal/modules/privacy:scheduled_send:scheduledsends.go:redactScheduledSends":                         "a message the rep chose to send later holds the subject's address, subject line and body BEFORE any activity exists, so the activity-keyed scrubs cannot reach it — Art. 17 empties the payload and cancels a pending one in the same transaction as the rest of the cascade, because a scheduled send that survived it would arrive the morning after the erasure certified the data destroyed",
	"internal/modules/privacy:approval:erasure_approvals.go:redactApprovalsCitingActivities":                 "a proposal's evidence is a VERBATIM quote of the body the caller just nulled, and nothing else in either engine reaches it — a proposal read from a meeting targets the ACTIVITY, so the subject-match arms never fire. Keyed on what the evidence CITES, because once the body is NULL the quote is the only place those words still exist. Pending rows are expired in the same statement: a blanked card left decidable is one a colleague can still approve",
	"internal/modules/privacy:approval:erasure_approvals.go:redactStagedApprovals":                           "a staged proposal naming the subject holds a whole composed message, and pending rows are EXPIRED rather than merely emptied — a blanked card still in the inbox is one a colleague can approve, running its effect against an empty payload, or one whose gates cannot refuse it because nobody is named to refuse on behalf of",
	"internal/modules/privacy:transcript_read:transcriptreadings.go:purgeTranscriptReadings":                 "a reading of a transcript is a record OF a body — how many lines it addressed, which proposals came out of them — so it cannot outlive that body, and both destructive engines delete it in the SAME transaction that nulls the body. Its own schema means it to go by cascade (core 0245), but neither engine ever DELETES an activity: Art. 17 redacts the row in place and retention nulls its content, both because a timeline row is other people's record too, so that cascade has never once fired. Routing it through activities would leave the transcript committed as a tombstone while a reading still answered questions about how long it was",
	"internal/modules/privacy:workflow_run:erasure_approvals.go:redactStagedApprovals":                       "the automation runs parked behind those withdrawn proposals are ended IN THE SAME STATEMENT: everywhere else a withdrawal reaches its parked run by riding the approval.decided event, this path emits none, and the expiry sweep cannot repair it because it scans for pending and these rows are already terminal — the run would wait forever",
	"internal/modules/privacy:workflow_run:erasure_approvals.go:redactWorkflowRuns":                          "an automation run records what it planned and what it did, so its own payload quotes the subject — nothing is withdrawn here, the run is already finished and this empties the history it left behind",
	"internal/modules/privacy:agent_run:erasure_approvals.go:redactStagedApprovals":                          "an agent run parks in awaiting_approval behind a staged approval and is only ever resumed by an approval.decided event. Erasure withdraws that approval without emitting one, so the run would wait forever holding the payload just destroyed — pending carries the staged call's arguments, which for a send is the recipient and the body. Ended here, in the same transaction as the withdrawal, for the reason workflow_run is",
	"internal/modules/privacy:comms_outbound:deliveries.go:redactDeliveries":                                 "the send log stores a second copy of an outbound message's recipients, subject and body, so Art. 17 erasure and the retention erase action scrub it in the SAME transaction that scrubs the activity it belongs to — routing it through comms would let the timeline row commit as a tombstone while the delivery still served the whole message",
	"internal/modules/privacy:comms_outbound:erasure_restrict.go:redactDeliveryAddressing":                   "the send log stores a second copy of an outbound message's recipients, subject and body, so Art. 17 erasure and the retention erase action scrub it in the SAME transaction that scrubs the activity it belongs to — routing it through comms would let the timeline row commit as a tombstone while the delivery still served the whole message",
	// direct audit_log/event_outbox writers: these paths need columns
	// storekit's writer does not carry.
	"internal/modules/approvals:audit_log:service.go:Service.audit":   "approval evidence stamps passport_id/on_behalf_of, columns storekit's writer does not carry; same append-only table, this module's own writer",
	"internal/modules/approvals:event_outbox:service.go:Service.emit": "approvals stages its events with the full envelope (passport actor fields) storekit.Emit does not carry; still outbox-only publishing",
	// the non-production admin data-reset orchestration (compose, cross-module
	// by nature — it sweeps every module's workspace_id tables in one
	// transaction) must clear the workspace's staged events alongside the
	// domain rows it just deleted: event_outbox has no workspace_id column
	// (tenancy lives in the envelope) and no owning module's store call could
	// scope a delete to "this workspace's queued events" without compose
	// growing a dependency on every module it sweeps.
	"internal/compose:event_outbox:datasweep.go:clearWorkspaceOutbox": "the reset orchestration clears this workspace's staged events in the same transaction as the domain sweep, so no relay ever wakes on an envelope pointing at a row the reset just deleted",
	// identity owns login/failed-login, which land in system_log (a login
	// mutates no record). They fire before/without an authenticated
	// principal for storekit.LogSystem to stamp — bootstrap and failed
	// logins have no session yet — so identity appends the append-only rows
	// directly.
	"internal/modules/identity:system_log:installation.go:createInstallation":   "the installation bootstrap writes its own ledger row: it runs before any principal exists, so storekit.LogSystem has nobody to stamp as captured_by",
	"internal/modules/identity:system_log:lockout.go:Service.recordFailedLogin": "login and failed-login land in system_log but fire before/without an authenticated principal for storekit.LogSystem to stamp; identity appends the append-only rows itself",
	"internal/modules/identity:system_log:reset.go:OperatorResetPassword":       "an operator reset writes its own ledger row: the operator acts out of band and is not an authenticated principal of this workspace, so storekit.LogSystem has nobody to stamp",
	"internal/modules/identity:system_log:service.go:logAuthEvent":              "login and failed-login land in system_log but fire before/without an authenticated principal for storekit.LogSystem to stamp; identity appends the append-only rows itself",
	"internal/modules/identity:system_log:ssologin.go:Handlers.logOidcFailure":  "a refused federated sign-in has no authenticated principal for storekit.LogSystem to stamp either — same posture as recordFailedLogin (lockout.go), just for the OIDC login path instead of the password one",
})
