// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package mailmap

// What a captured message is allowed to become. Two rules, deliberately
// separate because they pull opposite ways on the same headers:
//
//   - SkipReason decides what never reaches the timeline at all. It is NARROW:
//     ADR-0072 §1 keeps a transactional sender's message and suppresses only the
//     contact/company derivation, so the tier gate has to see the mail it judges.
//   - isMachineTouched decides what may vouch for an address. It is WIDE, and
//     only ever withholds evidence: an autoresponder's reply is genuinely
//     owner-authored and genuinely in Sent, so nothing downstream could tell it
//     from correspondence the owner chose.
//
// One answer cannot serve both, and the headers they read are the same ones.

import (
	"strings"

	"github.com/emersion/go-message/mail"
)

// SkipReason names why a message is intentionally dropped, or reports that
// it should be captured. The rule set keeps automated/system noise off the
// timeline: no stable id, no sender, an auto-reply, or the delivery system
// itself.
func (m Message) SkipReason() (string, bool) {
	if m.messageID == "" {
		return "no Message-ID", true
	}
	if m.from == "" {
		return "no From address", true
	}
	if m.autoReply {
		return autoReplied, true
	}
	if isDeliverySystemSender(m.from) {
		return "delivery-system sender", true
	}
	return "", false
}

// isDeliverySystemSender flags mail from the message-transport system itself —
// a bounce, a DSN, a postmaster notice. There is no correspondent behind it and
// nothing on the other end to have a relationship with, so it is dropped before
// anything is written.
//
// Deliberately NARROWER than "looks automated". A no-reply or notifications
// address is a real company writing to the workspace — a signed envelope,
// an invoice, a shipping notice — and ADR-0072 §1 is explicit that such a
// message keeps its place on the timeline while the tier gate suppresses the
// contact and company derivation. Dropping it here would make that promise false
// and would starve the T2 corroboration rule (CAP-PARAM-6), which exists to
// recognize exactly these machine localparts, of the mail it judges.
func isDeliverySystemSender(addr string) bool {
	local, _, found := strings.Cut(strings.ToLower(addr), "@")
	if !found {
		return false
	}
	// BATV/prvs tags sit before any separator a normalization would strip. The
	// scheme signs the RETURN PATH, which this never sees — matching From means
	// a relay that rewrites From with a tag has its mail dropped. Rare, and it
	// costs a timeline row rather than granting anything.
	if strings.HasPrefix(local, "prvs=") || strings.HasPrefix(local, "msprvs1=") {
		return true
	}
	// VERP encodes the original recipient into the bounce address
	// (`bounces-12345@`, `bounce+tag@`), so the trailing tag is dropped before
	// matching. `_` is stripped for parity with the T2 registry's own reading
	// of these localparts (CAP-PARAM-6) — one spelling, two rules.
	local, _, _ = strings.Cut(local, "+")
	local = strings.NewReplacer(".", "", "-", "", "_", "").Replace(local)
	local = strings.TrimRight(local, "0123456789")
	switch local {
	case "mailerdaemon", "postmaster", "bounce", "bounces":
		return true
	}
	return false
}

// The two RFC 3834 values that mean a contact's mail reaches the tier gate:
// `no` is not automatic at all, and `auto-generated` is mail a system
// originated on its own — an invoice, a notice, a signed envelope — as opposed
// to mail it generated in reply to something we sent.
const (
	notAutomatic  = "no"
	autoGenerated = "auto-generated"
	// autoReplied is the legacy Precedence spelling and the reason SkipReason
	// gives. RFC 3834's own keyword is `auto-replied`, which the switches carry
	// separately.
	autoReplied = "auto-reply"
)

// headerKeyword is the ONE reading of a structured header value: RFC 3834 §5
// allows parameters after a semicolon (`auto-replied; owner-email=…`) and RFC
// 5322 allows comments around the value (`auto-generated (invoice)`), so the
// keyword is what precedes the first semicolon once comments are gone. Both
// rules read it the same way — two readings would let a value mean one thing to
// the drop and another to the veto.
func headerKeyword(value string) (keyword string, readable bool) {
	// Only the region before the first top-level semicolon can decide the
	// keyword, so only that region's well-formedness can disqualify it. RFC
	// 3834 §5 parameters live after the semicolon, and a comment left unclosed
	// out there says nothing about a keyword that already parsed cleanly.
	keyword, wellFormed := scanValue(value, true)
	if !wellFormed {
		return "", false
	}
	return keyword, true
}

// isMalformedValue reports whether the value as a WHOLE failed to parse. The
// veto asks this rather than the keyword question: it may withhold evidence
// freely, so anything it cannot read in full is something a machine may have
// had a hand in.
func isMalformedValue(value string) bool {
	if _, wellFormed := scanValue(value, false); !wellFormed {
		return true
	}
	return !hasWellFormedParameters(value)
}

// hasWellFormedParameters reports whether everything after the keyword parses as
// RFC 3834 §5 parameters: semicolon-separated `attribute=value` pairs, where the
// attribute is an RFC 2045 token. Anything else means the sender wrote something
// we cannot read, and the veto treats unreadable as machine-touched.
//
// The segments are found with the same scan as the keyword, not by splitting on
// semicolons: a parameter value may legally contain one inside a quoted-string
// (`x="a;b"`), and cutting there would condemn a perfectly ordinary value.
func hasWellFormedParameters(value string) bool {
	params, wellFormed := parameterSegments(value)
	if !wellFormed {
		return false
	}
	for _, param := range params {
		attribute, parameterValue, found := strings.Cut(param, "=")
		// The attribute is not trimmed: RFC 2045 puts no space around the `=`,
		// so `a =b` is not a parameter either.
		if !found || !isToken(attribute) || !isParameterValue(parameterValue) {
			return false
		}
	}
	return true
}

// parameterSegments returns the parameter region split at the semicolons that
// separate parameters — those outside any comment or quoted-string — dropping
// the keyword and any empty segments a trailing separator leaves.
func parameterSegments(value string) (params []string, wellFormed bool) {
	whole, wellFormed := scanValue(value, false)
	if !wellFormed {
		return nil, false
	}
	keyword, _ := scanValue(value, true)
	rest := strings.TrimPrefix(whole, keyword)
	var current strings.Builder
	quoted := false
	for i := 0; i < len(rest); i++ {
		switch c := rest[i]; {
		case c == '"':
			quoted = !quoted
			current.WriteByte(c)
		case c == ';' && !quoted:
			params = appendParameter(params, current.String())
			current.Reset()
		default:
			current.WriteByte(c)
		}
	}
	return appendParameter(params, current.String()), true
}

// appendParameter adds one segment unless it is empty — `no;` and `no;;` carry
// no parameter, which is not the same as carrying a malformed one.
func appendParameter(params []string, segment string) []string {
	if segment = strings.TrimSpace(segment); segment != "" {
		return append(params, segment)
	}
	return params
}

// isParameterValue reports whether s could be a parameter value at all, which
// is only "there is one". Deliberately not an RFC 2045 token test: RFC 3834 §5's
// own example is `owner-email=alice@example.com`, and `@` is a tspecial — a
// strict reading would veto the canonical form and starve the gate of evidence
// to catch spellings nobody sends. What this rule is for is noticing that the
// parameter region holds something that is not a parameter at all.
func isParameterValue(s string) bool {
	return strings.TrimSpace(s) != ""
}

// isToken reports whether s is an RFC 2045 token: at least one character, none
// of them a space, a control, or one of the tspecials that structure a header.
func isToken(s string) bool {
	if s == "" {
		return false
	}
	return !strings.ContainsAny(s, "()<>@,;:\\\"/[]?= \t") && strings.IndexFunc(s, func(r rune) bool {
		return r < 0x20 || r == 0x7f
	}) < 0
}

// reachesGate reports whether an Auto-Submitted value names mail the tier gate
// should judge: not automatic at all, or a system's own notice.
func reachesGate(autoSubmitted string) bool {
	keyword, readable := headerKeyword(autoSubmitted)
	if !readable {
		// Unreadable is not permission. A value whose comment was never closed
		// could have said anything before it was swallowed.
		return false
	}
	return strings.EqualFold(keyword, notAutomatic) || strings.EqualFold(keyword, autoGenerated)
}

// isAutoReplyPrecedence reports whether a legacy Precedence value names a reply.
// Shared by both rules so a new spelling cannot be added to one and forgotten in
// the other — forgetting the wide one is the failure this split exists to stop.
func isAutoReplyPrecedence(value string) bool {
	keyword, readable := headerKeyword(value)
	if !readable {
		// An unreadable Precedence cannot be trusted to NAME a reply, and
		// refusing it would widen the narrow rule — a newsletter the tier gate
		// must see would be dropped for a malformed header. The wide rule reads
		// the same value as machine-touched, so nothing is granted by keeping it.
		return false
	}
	switch strings.ToLower(keyword) {
	case "auto_reply", autoReplied, "auto_replied", "auto-replied":
		return true
	}
	return false
}

func isAutoReply(autoSubmitted, precedence []string) bool {
	for _, v := range autoSubmitted {
		// Every occurrence is read, not the topmost: a relay that PREPENDS its
		// own `auto-generated` would otherwise mask the responder's
		// `auto-replied` sitting underneath it.
		if !reachesGate(v) {
			return true
		}
	}
	for _, v := range precedence {
		if isAutoReplyPrecedence(v) {
			return true
		}
	}
	return false
}

// isMachineTouched reports whether ANY machine hand shows on this message —
// including the bulk-family markers a newsletter carries, which isAutoReply
// deliberately lets through so the tier gate can judge them.
//
// Why this is a second rule rather than a wider first one: see the file header.
func isMachineTouched(autoSubmitted, precedence []string, machineHandledHeader bool) bool {
	if machineHandledHeader {
		return true
	}
	for _, v := range autoSubmitted {
		// The KEYWORD, exactly as the drop rule reads it: `no; owner-email=…`
		// is legal RFC 3834 and still means a contact wrote this.
		if isMalformedValue(v) {
			return true
		}
		keyword, readable := headerKeyword(v)
		if !readable || !strings.EqualFold(keyword, notAutomatic) {
			return true
		}
	}
	for _, v := range precedence {
		if isAutoReplyPrecedence(v) {
			return true
		}
		if isMalformedValue(v) {
			return true
		}
		keyword, _ := headerKeyword(v)
		switch strings.ToLower(keyword) {
		case "bulk", "list", "junk":
			return true
		}
	}
	return false
}

// stripHeaderComments removes RFC 5322 comments — parenthesized runs, which may
// nest and may contain quoted pairs. Header values are attacker-shaped text, so
// this walks the bytes rather than trusting a pattern: an unclosed parenthesis
// swallows the rest, which keeps a malformed value from resolving to a keyword
// it does not carry.

// scanValue walks a structured header value once, honouring the two RFC 5322
// constructs that make a byte mean something other than itself: a comment
// (parenthesized, nesting) and a quoted-string. Comments are dropped, quoted
// strings are kept verbatim, and a quoted-pair escapes whichever follows.
//
// stopAtParameters ends the walk at the first semicolon that is neither, which
// is the RFC 3834 §5 parameter separator — callers wanting only the keyword ask
// for that, so an unclosed comment out in the parameter region cannot condemn a
// keyword that already parsed.
//
// wellFormed reports that every comment closed and every quote was matched. It
// is the difference between "the value is X" and "the value might have been
// anything before something ate it", and no caller may read the text without it.
func scanValue(value string, stopAtParameters bool) (scanned string, wellFormed bool) {
	var out strings.Builder
	depth, quoted := 0, false
	for i := 0; i < len(value); i++ {
		c := value[i]
		switch {
		case c == '\\' && i+1 < len(value) && (depth > 0 || quoted):
			// A quoted-pair: the next byte is content, so neither a parenthesis
			// nor a quote after it can steer the scan.
			if depth == 0 {
				out.WriteByte(value[i+1])
			}
			i++
		case quoted:
			quoted = c != '"'
			out.WriteByte(c)
		case depth > 0:
			depth += commentDepthDelta(c)
		case c == ';' && stopAtParameters:
			return strings.TrimSpace(out.String()), true
		case c == '(':
			depth++
		default:
			// A quoted-string is opaque: RFC 3834 parameters may carry one
			// (`owner-email="a(b@x"`), and a parenthesis inside it opens no
			// comment. An unmatched ')' out here is content, not a close.
			quoted = c == '"'
			out.WriteByte(c)
		}
	}
	return strings.TrimSpace(out.String()), depth == 0 && !quoted
}

// commentDepthDelta reports how one byte inside a comment moves its nesting.
func commentDepthDelta(c byte) int {
	switch c {
	case '(':
		return 1
	case ')':
		return -1
	}
	return 0
}

func hasMachineHandledHeader(header mail.Header) bool {
	for _, name := range machineHandledHeaders {
		if header.Has(name) {
			return true
		}
	}
	return false
}

// machineHandledHeaders are the markers that say a machine handled or authored
// this message where no RFC 3834 value does. The first two are the legacy
// autoresponder spellings that predate that RFC and still ship in Exim recipes
// and older groupware; X-Loop is the most common homegrown one. The List-*
// pair is the modern spelling of what `Precedence: list` says, and landing the
// two on opposite sides of the same question is the split's own defect class.
//
// All of them only ever WITHHOLD attestation. A message the owner truly wrote
// loses nothing by not vouching for an address unless that address is already
// transactional-suppressed, so the wide reading costs little and the narrow one
// costs a spare nobody chose.
var machineHandledHeaders = []string{
	"X-Autoreply", "X-Autorespond", "X-Loop", "List-Id", "List-Unsubscribe",
}
