-- Deliberately empty: this backfill has no safe inverse, and the unsafe one
-- recreates the outage it was written to end.
--
-- The up only writes where the key is ABSENT, so it cannot say afterwards which
-- roles it changed. A workspace created after the tag work landed already holds
-- these grants from seedSystemRoles — the up skipped those roles — and a
-- rollback that removed `objects.tag` wherever it found it would strip exactly
-- those, leaving a fresh installation 403ing on every tag route. That is the
-- bug, reintroduced by the rollback of its own fix.
--
-- Leaving the key costs nothing. It stays valid while the object exists, and if
-- the tag work itself is rolled back the key is inert rather than dangerous:
-- policy.Parse tolerates an unknown object on the read path, deleting it from
-- the parsed document and logging it, so a stale grant reaches
-- principal.Permissions by no path. Dropping the object is that migration's own
-- business, not this one's.
