-- Irreversible by design.
--
-- The up migration expired held drafts that record no human. Restoring them to
-- 'pending' would need to know which rows were pending before it ran, and the
-- update kept no record of that — a row expired here is indistinguishable from
-- one that expired on its own window a moment earlier.
--
-- Reinstating every expired held draft instead would resurrect messages whose
-- windows closed for ordinary reasons, putting stale replies back in front of a
-- human as though they were live. Doing nothing is the honest inverse: the
-- automations that composed these drafts re-stage them on their next firing.
SELECT 1;
