-- Reverses the cascading-key indexes, restoring each widened partial index to
-- the predicate it carried before.

SET LOCAL lock_timeout = '3s';
DROP INDEX idx_activity_request_settlement_judged_through_activity;
DROP INDEX idx_analytics_share_snapshot;
DROP INDEX idx_auth_token_user_cascade;
DROP INDEX idx_booking_page_host_user;
DROP INDEX idx_brief_item_deal;
DROP INDEX idx_capture_exclusion_user;
DROP INDEX idx_capture_pending_counterparty_activity;
DROP INDEX idx_capture_pending_counterparty_owner;
DROP INDEX idx_close_date_run_member_deal;
DROP INDEX idx_communication_basis_contact;
DROP INDEX idx_communication_basis_lead;
DROP INDEX idx_communication_decision_delivery;
DROP INDEX idx_communication_review_delivery_intent;
DROP INDEX idx_communication_suppression_contact;
DROP INDEX idx_communication_suppression_lead;
DROP INDEX idx_company_domain_company;
DROP INDEX idx_company_domain_disposition_company;
DROP INDEX idx_contact_confirm_submission_token;
DROP INDEX idx_contact_email_contact;
DROP INDEX idx_contact_phone_contact;
DROP INDEX idx_contact_signature_enrich_state_activity;
DROP INDEX idx_conversation_claim_contact;
DROP INDEX idx_conversation_claim_source_activity;
DROP INDEX idx_deal_correction_deal;
DROP INDEX idx_deal_document_hide_attachment;
DROP INDEX idx_deal_room_deal;
DROP INDEX idx_deal_room_comment_room;
DROP INDEX idx_deal_room_document_room_cascade;
DROP INDEX idx_deal_room_engagement_participant_room;
DROP INDEX idx_deal_room_participant_room;
DROP INDEX idx_deal_room_session_participant_room;
DROP INDEX idx_deal_room_session_room;
DROP INDEX idx_deal_room_thread_document;
DROP INDEX idx_dedupe_candidate_left_company;
DROP INDEX idx_dedupe_candidate_left_contact;
DROP INDEX idx_dedupe_candidate_left_lead;
DROP INDEX idx_dedupe_candidate_right_company;
DROP INDEX idx_dedupe_candidate_right_contact;
DROP INDEX idx_dedupe_candidate_right_lead;
DROP INDEX idx_linkedin_connection_matched_contact;
DROP INDEX idx_linkedin_connection_owner_user;
DROP INDEX idx_notice_recipient_user;
DROP INDEX idx_oauth_authorization_code_user;
DROP INDEX idx_oauth_grant_user;
DROP INDEX idx_passport_on_behalf_of;
DROP INDEX idx_preference_token_contact;
DROP INDEX idx_privacy_notice_case_contact;
DROP INDEX idx_provider_applied_field_run_contact_provider;
DROP INDEX idx_provider_run_contact;
DROP INDEX idx_record_assignment_company;
DROP INDEX idx_record_assignment_deal;
DROP INDEX idx_record_assignment_project;
DROP INDEX idx_relationship_counterparty_contact;
DROP INDEX idx_role_assignment_team;
DROP INDEX idx_saved_view_owner_cascade;
DROP INDEX idx_session_user;
DROP INDEX idx_stage_pipeline;
DROP INDEX idx_stage_progression_outcome_from_stage;
DROP INDEX idx_stage_progression_outcome_to_stage;
DROP INDEX idx_stage_progression_policy_from_stage;
DROP INDEX idx_stage_progression_policy_to_stage;
DROP INDEX idx_webhook_subscription_owner;
DROP INDEX idx_withdrawal_credential_purpose;
CREATE INDEX idx_brief_item_deal ON brief_item (deal_id) WHERE (state <> 'new'::text);
CREATE INDEX idx_company_domain_company ON company_domain (company_id) WHERE (archived_at IS NULL);
CREATE INDEX idx_contact_email_contact ON contact_email (contact_id) WHERE (archived_at IS NULL);
CREATE INDEX idx_contact_phone_contact ON contact_phone (contact_id) WHERE (archived_at IS NULL);
CREATE INDEX idx_record_assignment_company ON record_assignment (company_id) WHERE (company_id IS NOT NULL AND archived_at IS NULL);
CREATE INDEX idx_record_assignment_deal ON record_assignment (deal_id) WHERE (deal_id IS NOT NULL AND archived_at IS NULL);
CREATE INDEX idx_record_assignment_project ON record_assignment (project_id) WHERE (project_id IS NOT NULL AND archived_at IS NULL);
CREATE INDEX idx_session_user ON session (user_id) WHERE (revoked_at IS NULL);
CREATE INDEX idx_stage_pipeline ON stage (pipeline_id) WHERE (archived_at IS NULL);
