// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

//go:build integration

package integration

// The ask over the REAL HTTP stack — router, middleware, the compose engine the
// api role wires, and the wire shape the screen reads.
//
// The store suites drive Retrieve directly and the engine is not theirs to
// reach. Three things only exist at this layer: that WithCorpusAsk actually
// replaces the 501 the seat answers without it; that a composition with no
// embed lane answers 200 + retrieval_unavailable rather than 501, because the
// caller asked a real corpus a real question and "nothing was searched" is an
// answer the contract names; and that every outcome carries the corpus's own
// words, which is what the screen quotes back.

import (
	"context"
	"io"
	"log/slog"
	"net/http"
	"testing"

	"github.com/margince/margince/backend/internal/compose"
	"github.com/margince/margince/backend/internal/compose/integration/apptest"
	"github.com/margince/margince/backend/internal/shared/ports/model"
)

// unaskableEmbedder reports no binding, which is what an installation with no
// AI routing has. Embed is unreachable — the empty identity is checked first —
// and answers an error rather than a plausible vector so a future caller that
// reaches it fails loudly.
type unaskableEmbedder struct{}

func (unaskableEmbedder) EmbedIdentity() (string, int) { return "", 0 }

func (unaskableEmbedder) Embed(context.Context, model.EmbedRequest) (model.Embeddings, error) {
	return model.Embeddings{}, context.Canceled
}

func askCorpusOverHTTP(t *testing.T, e *apptest.AppEnv, corpusID, question string) (int, AnyMap) {
	t.Helper()
	var answer AnyMap
	status := e.Call(t, "POST", "/v1/knowledge/corpora/"+corpusID+"/ask",
		AnyMap{"question": question}, nil, &answer)
	return status, answer
}

func createCorpusOverHTTP(t *testing.T, e *apptest.AppEnv) string {
	t.Helper()
	var made AnyMap
	status := e.Call(t, "POST", "/v1/knowledge/corpora", AnyMap{
		"name":            "How-to",
		"topic_statement": "How this product is operated.",
	}, nil, &made)
	if status != http.StatusCreated {
		t.Fatalf("create corpus: status %d, %v", status, made)
	}
	id, _ := made["id"].(string)
	if id == "" {
		t.Fatalf("create corpus returned no id: %v", made)
	}
	return id
}

// Without WithCorpusAsk the endpoint keeps its explicit 501: an installation
// that composed no retrieval at all cannot search, and pretending to would be
// worse than saying so.
func TestAskingACorpusWithoutTheEngineWiredIsNotImplemented(t *testing.T) {
	e := apptest.SetupApp(t)
	e.BootstrapWorkspace(t)
	corpusID := createCorpusOverHTTP(t, e)

	status, _ := askCorpusOverHTTP(t, e, corpusID, "how is a message filed")
	if status != http.StatusNotImplemented {
		t.Fatalf("ask with no engine wired: status %d, want 501", status)
	}
}

// With the engine wired but no embed lane, the ask ANSWERS: 200, and the
// outcome says nothing was searched.
func TestAskingWithNoEmbedLaneAnswersRetrievalUnavailableRatherThan501(t *testing.T) {
	e := apptest.SetupAppWithOptions(t,
		compose.WithCorpusAsk(unaskableEmbedder{}, nil, quietAskLog()))
	e.BootstrapWorkspace(t)
	corpusID := createCorpusOverHTTP(t, e)

	status, answer := askCorpusOverHTTP(t, e, corpusID, "how is a message filed")
	if status != http.StatusOK {
		t.Fatalf("ask with no embed lane: status %d, want 200 — %v", status, answer)
	}
	if answer["outcome"] != "retrieval_unavailable" {
		t.Fatalf("outcome = %v, want retrieval_unavailable", answer["outcome"])
	}
	// The corpus's own words ride every outcome, because the screen quotes them
	// back — a refusal naming nothing leaves the reader with nothing.
	corpus, _ := answer["corpus"].(map[string]any)
	if corpus["name"] != "How-to" || corpus["topic_statement"] == "" {
		t.Fatalf("the refusal names no corpus: %v", answer["corpus"])
	}
	// And it is generated by nobody, honestly labelled.
	if answer["generated_by"] != "deterministic" {
		t.Fatalf("generated_by = %v", answer["generated_by"])
	}
}

// A corpus holding nothing is not_ready — about the CORPUS — and never
// not_covered, which would blame a question nothing was searched for.
func TestAskingAnEmptyCorpusOverHTTPIsNotReady(t *testing.T) {
	e := apptest.SetupAppWithOptions(t,
		compose.WithCorpusAsk(askableEmbedder{}, nil, quietAskLog()))
	e.BootstrapWorkspace(t)
	corpusID := createCorpusOverHTTP(t, e)

	status, answer := askCorpusOverHTTP(t, e, corpusID, "how is a message filed")
	if status != http.StatusOK {
		t.Fatalf("ask: status %d — %v", status, answer)
	}
	if answer["outcome"] != "not_ready" {
		t.Fatalf("outcome = %v, want not_ready", answer["outcome"])
	}
}

// askableEmbedder reports a binding, so retrieval is possible and the outcome
// is decided by the corpus rather than by the installation.
type askableEmbedder struct{}

func (askableEmbedder) EmbedIdentity() (string, int) { return "fake/http@4", 4 }

func (askableEmbedder) Embed(_ context.Context, req model.EmbedRequest) (model.Embeddings, error) {
	vectors := make([][]float32, len(req.Inputs))
	for i := range vectors {
		vectors[i] = []float32{1, 0, 0, 0}
	}
	return model.Embeddings{Vectors: vectors, Dims: 4}, nil
}

// quietAskLog is the logger the engine degrades through. Discarded: the degrade
// LINE is production's honesty about a fallback, and a suite that printed it
// would bury the assertion it is here for.
func quietAskLog() *slog.Logger {
	return slog.New(slog.NewTextHandler(io.Discard, nil))
}
