// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

// Command gen-payloads compiles isolated, components-only OpenAPI documents
// into typed Go structs — the public contract for outbound event/webhook
// payloads. It reuses the oapi-codegen LIBRARY (not the CLI) over each source
// so the payload files stay isolated from api/crm.yaml: crm.yaml's webhooks:
// block is silently pruned by kin-openapi, and flipping global skip-prune
// there trips a pre-existing ApprovalToken name collision. An isolated file
// carries only our schemas, so generating every component is safe with no
// synthetic-path trick.
//
// For every schema carrying x-event-type / x-entity-type, the generator also
// projects EventType()/EntityType() methods onto the generated struct, so an
// emit site and its schema cannot drift without failing to compile.
//
// The generator is config-driven (config.go): a family is one slice entry,
// nothing here is webhook-specific.
package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"log"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/oapi-codegen/v2/pkg/codegen"

	"github.com/gradionhq/margince/backend/tools/internal/oas30"
)

func main() {
	root, err := backendRoot()
	if err != nil {
		log.Fatalf("gen-payloads: %v", err)
	}
	for _, g := range groups {
		if err := generateGroup(root, g); err != nil {
			log.Fatalf("gen-payloads: %s: %v", g.Source, err)
		}
	}
	fmt.Printf("gen-payloads: %d group(s) generated\n", len(groups))
}

// generateGroup compiles one group's Source file into its Out file.
func generateGroup(root string, g group) error {
	src, err := os.ReadFile(filepath.Join(root, g.Source)) // #nosec G304 -- build-time tool, config-driven source path
	if err != nil {
		return fmt.Errorf("reading source: %w", err)
	}
	out, err := generateSource(src, g.Package, g.VersionsVar)
	if err != nil {
		return err
	}
	dst := filepath.Join(root, g.Out)
	if err := os.WriteFile(dst, []byte(out), 0o600); err != nil { // #nosec G703 -- dst derives from this generator's own declared group list
		return fmt.Errorf("writing %s: %w", g.Out, err)
	}
	return nil
}

// generateSource is the generator core, kept file-IO-free so it is exercised
// directly by the unit test: normalize the 3.1 source into codegen's 3.0
// subset, emit models with oapi-codegen, then append the event/entity-type
// methods and re-stamp our own banner.
//
// versionsVar names the generated event-type→version map, or is empty for a
// family that owes none. It is a parameter rather than a constant because
// every family compiles into ONE Go package: a second file declaring the same
// map name would not compile, and a map nothing reads is a name to collide on
// for nothing.
func generateSource(specYAML []byte, pkg, versionsVar string) (string, error) {
	normalized, err := oas30.Bytes(specYAML)
	if err != nil {
		return "", err
	}

	loader := openapi3.NewLoader()
	spec, err := loader.LoadFromData(normalized)
	if err != nil {
		return "", fmt.Errorf("loading spec: %w", err)
	}

	// SkipPrune: the source is isolated (only our schemas), so pruning by
	// path-reachability would delete every component — there are no paths.
	// Keeping every component is exactly what we want and is safe here.
	body, err := codegen.Generate(spec, codegen.Configuration{
		PackageName: pkg,
		Generate:    codegen.GenerateOptions{Models: true},
		OutputOptions: codegen.OutputOptions{
			SkipPrune: true,
		},
	})
	if err != nil {
		return "", fmt.Errorf("codegen: %w", err)
	}
	body, err = structifyEmptyEventPayloads(body, spec)
	if err != nil {
		return "", err
	}

	methods, versions, err := eventMethodsAndVersions(spec, versionsVar)
	if err != nil {
		return "", err
	}

	assembled := restampBanner(body, pkg)
	if methods != "" {
		assembled += "\n" + methods
	}
	if versions != "" {
		assembled += "\n" + versions
	}

	formatted, err := format.Source([]byte(assembled))
	if err != nil {
		return "", fmt.Errorf("formatting generated source: %w", err)
	}
	return string(formatted), nil
}

const banner = "// Code generated by gen-payloads; DO NOT EDIT.\n"

// restampBanner drops oapi-codegen's own header (which embeds a build version
// that is not stable across environments) and replaces it with our fixed,
// drift-safe banner, keeping the generated package clause and body verbatim.
func restampBanner(body, pkg string) string {
	pkgClause := "package " + pkg
	lines := strings.Split(body, "\n")
	for i, ln := range lines {
		if ln == pkgClause {
			rest := strings.Join(lines[i:], "\n")
			return banner + "\n" + rest
		}
	}
	// No recognizable package clause: fall back to prepending the banner so
	// the failure surfaces at compile time rather than silently mis-stamping.
	return banner + "\n" + body
}

// structifyEmptyEventPayloads rewrites a nil-payload event's generated type
// from oapi-codegen's universal fallback for a zero-property object —
// `type X = map[string]interface{}` — into a real empty struct. That fallback
// fires regardless of `additionalProperties: false` (oapi-codegen only
// special-cases additionalProperties when the schema ALSO has properties),
// so every nil-payload event (deal.archived and its many `{}`-payload
// siblings) would otherwise generate as a type ALIAS to a builtin map type.
// Go forbids attaching a method to such an alias (the receiver base type
// must be a type defined in this package, and an alias to a foreign/builtin
// type has no such identity), so EventType()/EntityType() below would fail
// to compile the instant a nil-payload schema carried the event extensions —
// exactly the case this generator exists to catch at compile time, not
// silently miscompile itself. Only schemas that are BOTH event-tagged AND
// genuinely empty (no properties) are rewritten; every other schema's
// map/struct choice is left exactly as oapi-codegen decided.
func structifyEmptyEventPayloads(body string, spec *openapi3.T) (string, error) {
	if spec.Components == nil {
		return body, nil
	}
	names := make([]string, 0, len(spec.Components.Schemas))
	for name := range spec.Components.Schemas {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		ref := spec.Components.Schemas[name]
		if ref == nil || ref.Value == nil {
			continue
		}
		if _, hasEvent := ref.Value.Extensions["x-event-type"]; !hasEvent {
			continue
		}
		if len(ref.Value.Properties) != 0 {
			continue
		}
		from := "type " + name + " = map[string]interface{}"
		to := "type " + name + " struct{}"
		if !strings.Contains(body, from) {
			return "", fmt.Errorf("structifying %q: expected generated alias %q not found (oapi-codegen's empty-object output shape may have changed)", name, from)
		}
		body = strings.Replace(body, from, to, 1)
	}
	return body, nil
}

// eventMethodsAndVersions walks every schema in one pass, returning two
// generated blocks: the sorted EventType()/EntityType() method set for every
// schema carrying x-event-type / x-entity-type (the Go type name is the
// component name — the source authors them as valid PascalCase identifiers,
// which is exactly what oapi-codegen emits for such names), and
// PublicEventVersions, the map from each such schema's event type to its
// x-version extension (default 1 when absent). PublicEventVersions is the
// single generated source of truth both the coverage gate (every
// subscribable event type must be a key) and the version gate (the catalog's
// VersionOf must agree with the value) read — see
// backend/internal/modules/webhooks/payload_coverage_test.go and
// payload_version_test.go.
func eventMethodsAndVersions(spec *openapi3.T, versionsVar string) (methods, versions string, err error) {
	if spec.Components == nil {
		return "", "", nil
	}
	names := make([]string, 0, len(spec.Components.Schemas))
	for name := range spec.Components.Schemas {
		names = append(names, name)
	}
	sort.Strings(names)

	var methodsB strings.Builder
	var entries []payloadVersionEntry
	for _, name := range names {
		ref := spec.Components.Schemas[name]
		if ref == nil || ref.Value == nil {
			continue
		}
		ext := ref.Value.Extensions
		eventType, hasEvent, err := stringExtension(ext, "x-event-type", name)
		if err != nil {
			return "", "", err
		}
		entityType, hasEntity, err := stringExtension(ext, "x-entity-type", name)
		if err != nil {
			return "", "", err
		}
		if !hasEvent && !hasEntity {
			continue
		}
		if hasEvent != hasEntity {
			return "", "", fmt.Errorf("schema %q must declare both x-event-type and x-entity-type or neither", name)
		}
		// A blank line between each method keeps gofmt from column-aligning
		// adjacent single-line declarations (which would widen the ` { ` gap).
		fmt.Fprintf(&methodsB, "func (%s) EventType() string { return %q }\n\n", name, eventType)
		fmt.Fprintf(&methodsB, "func (%s) EntityType() string { return %q }\n\n", name, entityType)

		version, hasVersion, err := intExtension(ext, "x-version", name)
		if err != nil {
			return "", "", err
		}
		if !hasVersion {
			version = 1
		}
		entries = append(entries, payloadVersionEntry{eventType: eventType, version: version})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].eventType < entries[j].eventType })

	if versionsVar == "" {
		return methodsB.String(), "", nil
	}

	var versionsB strings.Builder
	versionsB.WriteString("// " + versionsVar + " maps every subscribable event type carrying a\n")
	versionsB.WriteString("// PublicEvent<Event> schema to that schema's x-version extension\n")
	versionsB.WriteString("// (default 1 when absent). It is the single generated source of truth for\n")
	versionsB.WriteString("// both the coverage gate (every subscribable event type must be a key here)\n")
	versionsB.WriteString("// and the version gate (VersionOf(type) must equal this map's value).\n")
	versionsB.WriteString("var " + versionsVar + " = map[string]int{\n")
	for _, e := range entries {
		fmt.Fprintf(&versionsB, "\t%q: %d,\n", e.eventType, e.version)
	}
	versionsB.WriteString("}\n")

	return methodsB.String(), versionsB.String(), nil
}

// payloadVersionEntry is one PublicEventVersions row before it is
// rendered — collected once per schema alongside its EventType()/EntityType()
// methods so extension parsing is not duplicated across two passes.
type payloadVersionEntry struct {
	eventType string
	version   int
}

// stringExtension reads an x- extension as a string. kin-openapi decodes
// extensions into map[string]any via encoding/json, so a scalar string lands
// as a Go string; json.RawMessage is tolerated for forward-compatibility.
func stringExtension(ext map[string]any, key, schema string) (string, bool, error) {
	raw, ok := ext[key]
	if !ok {
		return "", false, nil
	}
	switch v := raw.(type) {
	case string:
		return v, true, nil
	case json.RawMessage:
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return "", false, fmt.Errorf("schema %q: %s must be a string: %w", schema, key, err)
		}
		return s, true, nil
	default:
		return "", false, fmt.Errorf("schema %q: %s must be a string, got %T", schema, key, raw)
	}
}

// intExtension reads an x- extension as an integer. encoding/json decodes a
// bare JSON number into a Go float64 when the target is interface{} (kin-openapi's
// extension map), so that is the expected shape; json.RawMessage is tolerated
// for forward-compatibility, same as stringExtension.
func intExtension(ext map[string]any, key, schema string) (int, bool, error) {
	raw, ok := ext[key]
	if !ok {
		return 0, false, nil
	}
	switch v := raw.(type) {
	case float64:
		// A bare JSON number decodes to float64; a fractional value (1.5)
		// would silently truncate to 1 and pass the version gate, so reject
		// anything that does not round-trip through int.
		if v != math.Trunc(v) {
			return 0, false, fmt.Errorf("schema %q: %s must be an integer, got %v", schema, key, v)
		}
		return int(v), true, nil
	case json.RawMessage:
		var n int
		if err := json.Unmarshal(v, &n); err != nil {
			return 0, false, fmt.Errorf("schema %q: %s must be an integer: %w", schema, key, err)
		}
		return n, true, nil
	default:
		return 0, false, fmt.Errorf("schema %q: %s must be an integer, got %T", schema, key, raw)
	}
}

// backendRoot locates the backend Go module root (the directory whose go.mod
// declares the backend module). The //go:generate directive runs from
// internal/contracts, but the repo's standard entry point is the repository
// root — so at each ancestor it checks both that directory's go.mod AND a
// `<ancestor>/backend/go.mod`, letting the tool run from the repo root
// (`go run ./backend/tools/gen-payloads`) as well as from inside the module.
func backendRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	const want = "module github.com/gradionhq/margince/backend"
	isBackendModule := func(gomod string) bool {
		data, err := os.ReadFile(gomod) // #nosec G304 -- walking to locate the module root
		if err != nil {
			return false
		}
		first := string(data)
		if i := strings.IndexByte(first, '\n'); i >= 0 {
			first = first[:i]
		}
		return strings.TrimSpace(first) == want
	}
	for {
		if isBackendModule(filepath.Join(dir, "go.mod")) {
			return dir, nil
		}
		if backend := filepath.Join(dir, "backend"); isBackendModule(filepath.Join(backend, "go.mod")) {
			return backend, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not locate the backend module root (%q) at or above the working directory", want)
		}
		dir = parent
	}
}
