// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package main

import (
	"fmt"
	"go/format"
	"strings"
	"time"
)

// emitSpecs renders internal/platform/jobs/specs_gen.go: the kind-keyed Spec
// table SpecFor, Declared and MustBeTotal are built on. Compose identifiers do
// reach it — the args type name, the JobRunnerConfig field paths a
// registration or cadence names, the Go constant a derived timeout tracks —
// but only ever as STRINGS a gate joins back up, never as imports: platform
// carries what the contract says about a kind and never learns what its worker
// does.
//
// Kinds arrive already sorted, so the map literal is byte-stable across runs.
func emitSpecs(c contract, contractHash string) (string, error) {
	var b strings.Builder
	b.WriteString("// Code generated by tools/gen-jobs from api/jobs.yaml. DO NOT EDIT.\n\n")
	b.WriteString("package jobs\n\n")
	b.WriteString("import \"time\"\n\n")

	b.WriteString("// JobContractHash is the sha256 of api/jobs.yaml at generation time.\n")
	b.WriteString("// One run of gen-jobs writes this table and compose's, so both carry the\n")
	b.WriteString("// same fingerprint and the census compares the two: a mismatch is a pair\n")
	b.WriteString("// where one half was regenerated and the other was not, which the compiler\n")
	b.WriteString("// would believe. It says nothing about the file on disk — a pair\n")
	b.WriteString("// regenerated TOGETHER from a stale contract matches here, and the drift\n")
	b.WriteString("// gate is what catches that.\n")
	fmt.Fprintf(&b, "const JobContractHash = %q\n\n", contractHash)

	b.WriteString("// specs is every declared kind. A kind absent from this table is a kind\n")
	b.WriteString("// nobody declared, and MustBeTotal is what names them: the runner calls it\n")
	b.WriteString("// over the kinds it registered and refuses the boot when any is missing,\n")
	b.WriteString("// because a kind with no Spec would run at River's one-minute default.\n")
	b.WriteString("var specs = map[string]Spec{\n")
	for _, name := range c.sortedKinds() {
		writeSpec(&b, name, c.Kinds[name])
	}
	b.WriteString("}\n\n")

	b.WriteString("// queues is every declared queue and the worker bound stated for it. The\n")
	b.WriteString("// queue set is still composition's to BUILD — River takes a QueueConfig,\n")
	b.WriteString("// which this package has no business knowing — and this table is what the\n")
	b.WriteString("// census holds that construction to, in both directions.\n")
	b.WriteString("var queues = map[string]int{\n")
	for _, name := range c.sortedQueues() {
		fmt.Fprintf(&b, "\t%q: %d,\n", name, c.Queues[name].MaxWorkers)
	}
	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("formatting the generated spec table: %w", err)
	}
	return string(formatted), nil
}

// writeSpec renders one map entry. Every field the entry does not declare is
// left off rather than written as its zero: the reader of a generated table
// should be able to see what the contract actually said.
func writeSpec(b *strings.Builder, name string, def kindDef) {
	fmt.Fprintf(b, "\t%q: {\n", name)
	fmt.Fprintf(b, "\t\tKind: %q,\n", name)
	fmt.Fprintf(b, "\t\tGoType: %q,\n", def.GoType)
	fmt.Fprintf(b, "\t\tRole: %s,\n", roleConst(def.Role))
	if def.fleetWide() {
		b.WriteString("\t\tFleet: true,\n")
	}
	fmt.Fprintf(b, "\t\tQueue: %q,\n", def.Queue)
	fmt.Fprintf(b, "\t\tTimeout: %s,\n", timeoutLiteral(*def.Timeout))
	if def.MaxAttempts != nil {
		fmt.Fprintf(b, "\t\tMaxAttempts: %d,\n", *def.MaxAttempts)
	}
	if def.FansOutTo != "" {
		fmt.Fprintf(b, "\t\tFanOutUnit: %s,\n", unitConst(def.FanOutUnit))
		fmt.Fprintf(b, "\t\tFanOutTo: %q,\n", def.FansOutTo)
	}
	fmt.Fprintf(b, "\t\tOptsOwner: %s,\n", optsConst(def.OptsOwner))
	if lit := cadenceLiteral(def.Cadence); lit != "" {
		fmt.Fprintf(b, "\t\tCadence: %s,\n", lit)
	}
	if lit := registrationLiteral(def.Registration); lit != "" {
		fmt.Fprintf(b, "\t\tRegistration: %s,\n", lit)
	}
	if def.Fault != nil {
		fmt.Fprintf(b, "\t\tFault: FaultPolicy{NilAfterLogging: %q},\n", def.Fault.NilAfterLogging)
	}
	if lit := argsLiteral(def); lit != "" {
		fmt.Fprintf(b, "\t\tArgs: %s,\n", lit)
	}
	b.WriteString("\t},\n")
}

// argsLiteral renders a kind's declared args fields in field-name order, and
// returns "" for the fieldless dispatchers. The order is the emitter's because
// the census reports on it: a diff in a generated table should read as the
// change somebody made, not as a map that happened to walk differently.
func argsLiteral(def kindDef) string {
	if len(def.Args) == 0 {
		return ""
	}
	fields := make([]string, 0, len(def.Args))
	for _, name := range def.sortedArgs() {
		arg := def.Args[name]
		switch {
		case arg.Scalar:
			fields = append(fields, fmt.Sprintf("{Name: %q, Scalar: true, Reason: %q}", name, arg.Reason))
		case arg.Reason != "":
			// An id that argued for itself, because its name reads like
			// content. The reason is carried rather than dropped: it is what
			// the content gate demands of such a field.
			fields = append(fields, fmt.Sprintf("{Name: %q, Reason: %q}", name, arg.Reason))
		default:
			fields = append(fields, fmt.Sprintf("{Name: %q}", name))
		}
	}
	return "[]ArgField{" + strings.Join(fields, ", ") + "}"
}

func roleConst(role string) string {
	if role == roleDispatcher {
		return "Dispatcher"
	}
	return "Worker"
}

func unitConst(unit string) string {
	switch unit {
	case unitConnection:
		return "FanOutConnection"
	case unitBuild:
		return "FanOutBuild"
	default:
		return "FanOutWorkspace"
	}
}

func optsConst(owner string) string {
	switch owner {
	case optsFanOut:
		return "OptsFanOut"
	case optsArgs:
		return "OptsArgs"
	default:
		return "OptsCaller"
	}
}

// timeoutLiteral renders the policy. A {derived: …} entry keeps BOTH its
// resolved duration (what Govern hands River) and the constant name (what the
// census compares against), so the declaration tracks the upstream constant
// instead of freezing a copy of its value.
func timeoutLiteral(t timeoutDef) string {
	switch {
	case t.None:
		return "TimeoutPolicy{None: true}"
	case t.Operator != "":
		return fmt.Sprintf("TimeoutPolicy{OperatorField: %q}", t.Operator)
	case t.Derived != "":
		return fmt.Sprintf("TimeoutPolicy{Fixed: %s, DerivedFrom: %q}", goDuration(t.Fixed), t.Derived)
	default:
		return fmt.Sprintf("TimeoutPolicy{Fixed: %s}", goDuration(t.Fixed))
	}
}

// cadenceLiteral returns "" only for a kind that has no schedule to declare —
// a worker, which is enqueued by its dispatcher and never ticked. A
// dispatcher a human's confirm enqueues renders {OnDemand: true} instead: the
// compiled table is what every consumer reads, and a dropped field would make
// a deliberate absence indistinguishable from a schedule someone lost.
func cadenceLiteral(c *cadenceDef) string {
	if c == nil {
		return ""
	}
	if c.OnDemand {
		return "Cadence{OnDemand: true}"
	}
	fields := make([]string, 0, 2)
	if c.Fixed != 0 {
		fields = append(fields, "Fixed: "+goDuration(c.Fixed))
	}
	if c.Operator != "" {
		fields = append(fields, fmt.Sprintf("OperatorField: %q", c.Operator))
	}
	if c.ScheduleWhenPositive != "" {
		fields = append(fields, fmt.Sprintf("ScheduleWhenPositive: %q", c.ScheduleWhenPositive))
	}
	return "Cadence{" + strings.Join(fields, ", ") + "}"
}

// registrationLiteral returns "" for a kind that registers unconditionally.
func registrationLiteral(r *registrationDef) string {
	if r == nil || len(r.When) == 0 {
		return ""
	}
	quoted := make([]string, 0, len(r.When))
	for _, field := range r.When {
		quoted = append(quoted, fmt.Sprintf("%q", field))
	}
	lit := "Registration{When: []string{" + strings.Join(quoted, ", ") + "}"
	if r.Absent == absentRegistersAnyway {
		lit += ", AbsentRegistersAnyway: true"
	}
	return lit + "}"
}

// goDuration renders a duration as the Go source a human would have written.
// The ladder is deterministic — the same duration always renders the same way
// — which is what keeps the drift gate from firing on a re-run.
func goDuration(d time.Duration) string {
	switch {
	case d == 0:
		return "0"
	case d%time.Hour == 0:
		return fmt.Sprintf("%d * time.Hour", d/time.Hour)
	case d%time.Minute == 0:
		return fmt.Sprintf("%d * time.Minute", d/time.Minute)
	case d%time.Second == 0:
		return fmt.Sprintf("%d * time.Second", d/time.Second)
	default:
		return fmt.Sprintf("%d * time.Nanosecond", d)
	}
}
