// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package main

import (
	"fmt"
	"go/format"
	"strings"
)

// emitKinds renders internal/compose/jobkinds_gen.go: the closed set of args
// types a worker may be registered under, the registration entry points
// constrained to it, and the role assertions that used to be a hand-written
// list beside them. All three come from the same source as the spec table, so
// the set, the roles and the declaration cannot drift apart.
//
// Kinds arrive already sorted, so every emitted list is byte-stable.
func emitKinds(c contract, contractHash string) (string, error) {
	var b strings.Builder
	b.WriteString("// Code generated by tools/gen-jobs from api/jobs.yaml. DO NOT EDIT.\n\n")
	b.WriteString("package compose\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"time\"\n\n")
	b.WriteString("\t\"github.com/riverqueue/river\"\n\n")
	b.WriteString("\t\"github.com/margince/margince/backend/internal/platform/jobs\"\n")
	b.WriteString(")\n\n")

	b.WriteString("// jobContractHash is the sha256 of api/jobs.yaml this file was generated\n")
	b.WriteString("// from — the same fingerprint jobs.JobContractHash carries, so a stale\n")
	b.WriteString("// half of the pair is visible without diffing the two tables.\n")
	fmt.Fprintf(&b, "const jobContractHash = %q\n\n", contractHash)

	writeDeclaredSet(&b, c)
	writeAddDeclaredWorker(&b)
	writeRoleAssertions(&b, c)

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("formatting the generated kind set: %w", err)
	}
	return string(formatted), nil
}

// writeDeclaredSet renders the type-set constraint. It is a union rather than
// a marker interface on purpose: a marker is something a new type can declare
// for itself, and the whole point is that a kind api/jobs.yaml has never heard
// of cannot be registered at all.
func writeDeclaredSet(b *strings.Builder, c contract) {
	b.WriteString("// declaredJobArgs is every args type api/jobs.yaml declares, and nothing\n")
	b.WriteString("// else. A job kind the file has never heard of cannot satisfy it, so it\n")
	b.WriteString("// cannot be passed to either registration function below — and those two\n")
	b.WriteString("// are how the runner registers, so an undeclared kind does not compile.\n")
	b.WriteString("//\n")
	b.WriteString("// A union rather than a marker interface, because a marker is something a\n")
	b.WriteString("// new type can declare for itself: the set has to be the file's to state.\n")
	b.WriteString("type declaredJobArgs interface {\n")
	b.WriteString("\triver.JobArgs\n\n")
	for i, name := range c.sortedKinds() {
		sep := " |"
		if i == len(c.Kinds)-1 {
			sep = ""
		}
		fmt.Fprintf(b, "\t%s%s\n", c.Kinds[name].GoType, sep)
	}
	b.WriteString("}\n\n")
}

// writeAddDeclaredWorker renders the sanctioned registration entry points.
//
// Both take the registry rather than *river.Workers: River keeps its own
// registry map unexported, so the registry is the only thing that can tell
// jobs.MustBeTotal what this build actually registered. A signature over
// *river.Workers would compile and register correctly while leaving the
// boot-time totality check reading an empty list.
func writeAddDeclaredWorker(b *strings.Builder) {
	b.WriteString("// addDeclaredWorker is the sanctioned registration path. Its type parameter\n")
	b.WriteString("// is constrained to the declared set, so a kind absent from api/jobs.yaml\n")
	b.WriteString("// cannot be named here at all — the error lands on the registration line\n")
	b.WriteString("// the author is writing, as `does not satisfy declaredJobArgs`.\n")
	b.WriteString("//\n")
	b.WriteString("// It takes the registry, not river.Workers: River's Workers map is\n")
	b.WriteString("// unexported, so the registry is the only thing that can tell MustBeTotal\n")
	b.WriteString("// what this build registered.\n")
	b.WriteString("func addDeclaredWorker[T declaredJobArgs](reg *jobRegistry, w jobs.WorkOnly[T]) {\n")
	b.WriteString("\taddGovernedWorker[T](reg, w, 0)\n")
	b.WriteString("}\n\n")

	b.WriteString("// addDeclaredWorkerWithTimeout serves the kinds whose timeout is an\n")
	b.WriteString("// operator's to set, and so is computed at boot rather than stated in\n")
	b.WriteString("// api/jobs.yaml. Every other kind takes its wall clock from the file and\n")
	b.WriteString("// registers through addDeclaredWorker; jobtimeoutwiring_test.go derives\n")
	b.WriteString("// which is which from the declared TimeoutPolicy rather than a list.\n")
	b.WriteString("//\n")
	b.WriteString("// The mark it leaves lets the census check that same claim against the\n")
	b.WriteString("// wiring it built rather than against the source: passing through here is\n")
	b.WriteString("// the only way a kind's wall clock comes from anywhere but the file.\n")
	b.WriteString("func addDeclaredWorkerWithTimeout[T declaredJobArgs](reg *jobRegistry, w jobs.WorkOnly[T], supplied time.Duration) {\n")
	b.WriteString("\taddGovernedWorker[T](reg, w, supplied)\n")
	b.WriteString("\tvar zero T\n")
	b.WriteString("\treg.markOperatorSupplied(zero.Kind())\n")
	b.WriteString("}\n\n")
}

// writeRoleAssertions renders the compile-time role markers. They are
// load-bearing — jobs.WorkspaceScoped is what binds a job's workspace, and the
// fleet-report gate reads both markers — so a misspelled accessor or a marker
// on the wrong type is a build error at the args type, which is where a
// contributor will actually see it.
func writeRoleAssertions(b *strings.Builder, c contract) {
	b.WriteString("// The FLEET-WIDE kinds: a row of one carries no tenant. A dispatcher\n")
	b.WriteString("// enumerates and enqueues; a collapsed pass walks the workspaces itself\n")
	b.WriteString("// (ADR-0103). Both own no workspace, which is what the marker asserts.\n")
	b.WriteString("var (\n")
	for _, name := range c.sortedKinds() {
		if def := c.Kinds[name]; def.fleetWide() {
			fmt.Fprintf(b, "\t_ jobs.FleetWide = %s{}\n", def.GoType)
		}
	}
	b.WriteString(")\n\n")

	// Keyed on the ARGS, not on the role. A worker carries a tenant while its
	// module still has one to carry (ADR-0091 §8 phase D is removing them one
	// module at a time), and a worker whose args no longer name a workspace must
	// not be asserted to bind one — the marker would be a claim about a field
	// that does not exist.
	b.WriteString("// The declared tenant-scoped kinds: each says which workspace it is for\n")
	b.WriteString("// in its own args.\n")
	b.WriteString("var (\n")
	for _, name := range c.sortedKinds() {
		if def := c.Kinds[name]; def.Role == roleWorker && def.hasWorkspaceArg() {
			fmt.Fprintf(b, "\t_ jobs.WorkspaceScoped = %s{}\n", def.GoType)
		}
	}
	b.WriteString(")\n")
}
