// Package crm provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package crm

import (
	"time"
)

// Defines values for ActivityCaptureLabel.
const (
	ActivityCaptureLabelCommitment ActivityCaptureLabel = "commitment"
	ActivityCaptureLabelMeeting    ActivityCaptureLabel = "meeting"
	ActivityCaptureLabelNoise      ActivityCaptureLabel = "noise"
)

// Valid indicates whether the value is a known member of the ActivityCaptureLabel enum.
func (e ActivityCaptureLabel) Valid() bool {
	switch e {
	case ActivityCaptureLabelCommitment:
		return true
	case ActivityCaptureLabelMeeting:
		return true
	case ActivityCaptureLabelNoise:
		return true
	default:
		return false
	}
}

// Defines values for ActivityContentState.
const (
	Available ActivityContentState = "available"
	Withheld  ActivityContentState = "withheld"
)

// Valid indicates whether the value is a known member of the ActivityContentState enum.
func (e ActivityContentState) Valid() bool {
	switch e {
	case Available:
		return true
	case Withheld:
		return true
	default:
		return false
	}
}

// Defines values for ActivityDirection.
const (
	ActivityDirectionInbound  ActivityDirection = "inbound"
	ActivityDirectionOutbound ActivityDirection = "outbound"
)

// Valid indicates whether the value is a known member of the ActivityDirection enum.
func (e ActivityDirection) Valid() bool {
	switch e {
	case ActivityDirectionInbound:
		return true
	case ActivityDirectionOutbound:
		return true
	default:
		return false
	}
}

// Defines values for ActivityKind.
const (
	ActivityKindCall    ActivityKind = "call"
	ActivityKindEmail   ActivityKind = "email"
	ActivityKindMeeting ActivityKind = "meeting"
	ActivityKindMessage ActivityKind = "message"
	ActivityKindNote    ActivityKind = "note"
	ActivityKindTask    ActivityKind = "task"
)

// Valid indicates whether the value is a known member of the ActivityKind enum.
func (e ActivityKind) Valid() bool {
	switch e {
	case ActivityKindCall:
		return true
	case ActivityKindEmail:
		return true
	case ActivityKindMeeting:
		return true
	case ActivityKindMessage:
		return true
	case ActivityKindNote:
		return true
	case ActivityKindTask:
		return true
	default:
		return false
	}
}

// Defines values for ActivityMeetingStatus.
const (
	ActivityMeetingStatusBooked   ActivityMeetingStatus = "booked"
	ActivityMeetingStatusCanceled ActivityMeetingStatus = "canceled"
	ActivityMeetingStatusHeld     ActivityMeetingStatus = "held"
	ActivityMeetingStatusNoShow   ActivityMeetingStatus = "no_show"
)

// Valid indicates whether the value is a known member of the ActivityMeetingStatus enum.
func (e ActivityMeetingStatus) Valid() bool {
	switch e {
	case ActivityMeetingStatusBooked:
		return true
	case ActivityMeetingStatusCanceled:
		return true
	case ActivityMeetingStatusHeld:
		return true
	case ActivityMeetingStatusNoShow:
		return true
	default:
		return false
	}
}

// Defines values for ActivityAudience.
const (
	Participants ActivityAudience = "participants"
	Selected     ActivityAudience = "selected"
	Workspace    ActivityAudience = "workspace"
)

// Valid indicates whether the value is a known member of the ActivityAudience enum.
func (e ActivityAudience) Valid() bool {
	switch e {
	case Participants:
		return true
	case Selected:
		return true
	case Workspace:
		return true
	default:
		return false
	}
}

// Defines values for ActivityLinkEntityType.
const (
	ActivityLinkEntityTypeDeal         ActivityLinkEntityType = "deal"
	ActivityLinkEntityTypeLead         ActivityLinkEntityType = "lead"
	ActivityLinkEntityTypeOrganization ActivityLinkEntityType = "organization"
	ActivityLinkEntityTypePerson       ActivityLinkEntityType = "person"
	ActivityLinkEntityTypeProject      ActivityLinkEntityType = "project"
)

// Valid indicates whether the value is a known member of the ActivityLinkEntityType enum.
func (e ActivityLinkEntityType) Valid() bool {
	switch e {
	case ActivityLinkEntityTypeDeal:
		return true
	case ActivityLinkEntityTypeLead:
		return true
	case ActivityLinkEntityTypeOrganization:
		return true
	case ActivityLinkEntityTypePerson:
		return true
	case ActivityLinkEntityTypeProject:
		return true
	default:
		return false
	}
}

// Defines values for CreateActivityRequestDirection.
const (
	CreateActivityRequestDirectionInbound  CreateActivityRequestDirection = "inbound"
	CreateActivityRequestDirectionOutbound CreateActivityRequestDirection = "outbound"
)

// Valid indicates whether the value is a known member of the CreateActivityRequestDirection enum.
func (e CreateActivityRequestDirection) Valid() bool {
	switch e {
	case CreateActivityRequestDirectionInbound:
		return true
	case CreateActivityRequestDirectionOutbound:
		return true
	default:
		return false
	}
}

// Defines values for CreateActivityRequestKind.
const (
	CreateActivityRequestKindCall    CreateActivityRequestKind = "call"
	CreateActivityRequestKindEmail   CreateActivityRequestKind = "email"
	CreateActivityRequestKindMeeting CreateActivityRequestKind = "meeting"
	CreateActivityRequestKindMessage CreateActivityRequestKind = "message"
	CreateActivityRequestKindNote    CreateActivityRequestKind = "note"
	CreateActivityRequestKindTask    CreateActivityRequestKind = "task"
)

// Valid indicates whether the value is a known member of the CreateActivityRequestKind enum.
func (e CreateActivityRequestKind) Valid() bool {
	switch e {
	case CreateActivityRequestKindCall:
		return true
	case CreateActivityRequestKindEmail:
		return true
	case CreateActivityRequestKindMeeting:
		return true
	case CreateActivityRequestKindMessage:
		return true
	case CreateActivityRequestKindNote:
		return true
	case CreateActivityRequestKindTask:
		return true
	default:
		return false
	}
}

// Defines values for CreateActivityRequestLinksEntityType.
const (
	CreateActivityRequestLinksEntityTypeDeal         CreateActivityRequestLinksEntityType = "deal"
	CreateActivityRequestLinksEntityTypeLead         CreateActivityRequestLinksEntityType = "lead"
	CreateActivityRequestLinksEntityTypeOrganization CreateActivityRequestLinksEntityType = "organization"
	CreateActivityRequestLinksEntityTypePerson       CreateActivityRequestLinksEntityType = "person"
	CreateActivityRequestLinksEntityTypeProject      CreateActivityRequestLinksEntityType = "project"
)

// Valid indicates whether the value is a known member of the CreateActivityRequestLinksEntityType enum.
func (e CreateActivityRequestLinksEntityType) Valid() bool {
	switch e {
	case CreateActivityRequestLinksEntityTypeDeal:
		return true
	case CreateActivityRequestLinksEntityTypeLead:
		return true
	case CreateActivityRequestLinksEntityTypeOrganization:
		return true
	case CreateActivityRequestLinksEntityTypePerson:
		return true
	case CreateActivityRequestLinksEntityTypeProject:
		return true
	default:
		return false
	}
}

// Defines values for CreateActivityRequestMeetingStatus.
const (
	CreateActivityRequestMeetingStatusBooked   CreateActivityRequestMeetingStatus = "booked"
	CreateActivityRequestMeetingStatusCanceled CreateActivityRequestMeetingStatus = "canceled"
	CreateActivityRequestMeetingStatusHeld     CreateActivityRequestMeetingStatus = "held"
	CreateActivityRequestMeetingStatusNoShow   CreateActivityRequestMeetingStatus = "no_show"
)

// Valid indicates whether the value is a known member of the CreateActivityRequestMeetingStatus enum.
func (e CreateActivityRequestMeetingStatus) Valid() bool {
	switch e {
	case CreateActivityRequestMeetingStatusBooked:
		return true
	case CreateActivityRequestMeetingStatusCanceled:
		return true
	case CreateActivityRequestMeetingStatusHeld:
		return true
	case CreateActivityRequestMeetingStatusNoShow:
		return true
	default:
		return false
	}
}

// Activity A polymorphic timeline item. Mirrors the `activity` table + `activity_link`.
// **Per-kind field constraints** (enforced server-side to match the DB `activity_task_fields`
// CHECK; the OpenAPI cannot express these conditionally): `due_at`/`assignee_id`/`is_done`/
// `done_at` are valid ONLY when `kind=task`; `meeting_status` ONLY when `kind=meeting`;
// `duration_seconds` only for meeting/call; `direction` is null for note/task. Setting a
// disallowed field for the kind returns `422 code: field_not_valid_for_kind` (the API rejects
// what the DB CHECK would reject, rather than 500-ing at write time).
// `channel_provider` is the same kind of constraint in both directions: non-null exactly
// when `kind=message` (ADR-0107/A158).
type Activity struct {
	ArchivedAt *time.Time `json:"archived_at,omitempty"`

	// AssigneeId Task only.
	AssigneeId *string `json:"assignee_id,omitempty"`

	// Audience Who may read this activity's CONTENT once the row is discoverable at all. `workspace` — everyone who can discover it (the default); `participants` — the humans on it (the capturing mailbox owner, anyone stamped as a participant by seat); `selected` — the participants plus the users and teams named through PATCH /activities/{id}/audience. Set only through that endpoint, by a human with write authority over the activity.
	Audience *ActivityAudience `json:"audience,omitempty"`

	// AudienceReason Why `audience` is what it is, for a captured message whose audience the system derived rather than a human set: `posture` (a mailbox asked for it), `workspace_floor` (the workspace turned mail sharing off), `no_record` (the message is filed under no record), `pending_verdict` (nothing has judged the message yet), `manual` (a human said so). Null on a row nothing derived. WITHHELD with the content — the reason describes what the message is about, so a colleague who may not read a held message does not learn why it is held either; it is absent whenever `content_state` is `withheld`.
	AudienceReason *string `json:"audience_reason,omitempty"`
	Body           *string `json:"body,omitempty"`

	// BulkMailAttested This message carried an RFC 2369 List-Unsubscribe header, so the SENDER declared it bulk. Per message, never per sender: the same address sends a newsletter and a reply, and treating the sender as bulk would bury the reply.
	BulkMailAttested *bool `json:"bulk_mail_attested,omitempty"`

	// CaptureLabel What this message turned out to be, from the batched capture classification. Null means unclassified, which is a backlog state and not a verdict of "ordinary".
	CaptureLabel *ActivityCaptureLabel `json:"capture_label,omitempty"`

	// CapturedBy Server-stamped from the authenticated principal (human:<uuid> | agent:<id> | connector:<name>); never client-supplied.
	CapturedBy *string `json:"captured_by,omitempty"`

	// ChannelProvider Which transport carried this message — non-null exactly when `kind=message`.
	// The kind says what sort of interaction happened; this says what carried it. They
	// are separate axes, and reading one off the other is what ADR-0107 retired.
	ChannelProvider *ProviderRef `json:"channel_provider,omitempty"`

	// ContentState Whether this response carries the activity's content. `withheld` means the caller may discover the row (a linked record is theirs to read) but is not in its audience: only the safe markers are filled — id, kind, channel_provider, occurred_at, direction, audience, links, is_done/due_at for a task, provenance and timestamps — and subject, body, thread_key, capture_label, source_id and raw are null. An `available` row is complete.
	ContentState *ActivityContentState `json:"content_state,omitempty"`
	CreatedAt    time.Time             `json:"created_at"`

	// Direction inbound/outbound for email/call; null for note/task.
	Direction *ActivityDirection `json:"direction,omitempty"`
	DoneAt    *time.Time         `json:"done_at,omitempty"`

	// DueAt Task only.
	DueAt *time.Time `json:"due_at,omitempty"`

	// DurationSeconds Meeting/call only.
	DurationSeconds *int `json:"duration_seconds,omitempty"`

	// HostUserId Meeting only: the member of this organization who held it. It is the one place an activity names OUR side of an exchange — a mail says only which contact it was with, and the mailbox behind it is not on the row. Null on every other kind, and on a meeting nobody was recorded as hosting.
	HostUserId *string `json:"host_user_id,omitempty"`
	Id         string  `json:"id"`

	// IsDone Task only.
	IsDone *bool        `json:"is_done,omitempty"`
	Kind   ActivityKind `json:"kind"`

	// Links One activity may link to >1 entity (person + deal).
	Links *[]ActivityLink `json:"links,omitempty"`

	// MeetingStatus Set only when kind=meeting.
	MeetingStatus *ActivityMeetingStatus  `json:"meeting_status,omitempty"`
	OccurredAt    time.Time               `json:"occurred_at"`
	Raw           *map[string]interface{} `json:"raw,omitempty"`

	// RemindAt Task only. Reminder-fire time; the B-E16.6 scan reads tasks whose reminder is due, not-done, and un-archived.
	RemindAt *time.Time `json:"remind_at,omitempty"`
	Source   string     `json:"source"`

	// SourceId Provider message/event id — idempotency key part.
	SourceId *string `json:"source_id,omitempty"`

	// SourceSystem gmail/gcal/outlook/transcript — idempotency key part.
	SourceSystem *string `json:"source_system,omitempty"`
	Subject      *string `json:"subject,omitempty"`

	// ThreadKey The provider's own conversation id (Gmail threadId, Graph conversationId, the RFC822 References root), stamped by capture. It is what makes a thread a thread: grouping by subject would merge two unrelated "Re: Update" exchanges and split one that was renamed mid-conversation. Null on anything capture did not thread — a note, a task, a message whose provider offered none.
	ThreadKey *string   `json:"thread_key,omitempty"`
	UpdatedAt time.Time `json:"updated_at"`

	// Version Monotonic row version, incremented by the server on every mutation (data-model §1.3a).
	// Echoed back as the `version` field on every mutable entity. To make a write conditional,
	// send the last-seen value in `If-Match`; a mismatch returns `409 code: version_skew`
	// (ErrVersionSkew) so the client re-reads before retrying. Applies to the native SoR path,
	// not only overlay mode.
	Version *RowVersion `json:"version,omitempty"`
}

// ActivityCaptureLabel What this message turned out to be, from the batched capture classification. Null means unclassified, which is a backlog state and not a verdict of "ordinary".
type ActivityCaptureLabel string

// ActivityContentState Whether this response carries the activity's content. `withheld` means the caller may discover the row (a linked record is theirs to read) but is not in its audience: only the safe markers are filled — id, kind, channel_provider, occurred_at, direction, audience, links, is_done/due_at for a task, provenance and timestamps — and subject, body, thread_key, capture_label, source_id and raw are null. An `available` row is complete.
type ActivityContentState string

// ActivityDirection inbound/outbound for email/call; null for note/task.
type ActivityDirection string

// ActivityKind defines model for Activity.Kind.
type ActivityKind string

// ActivityMeetingStatus Set only when kind=meeting.
type ActivityMeetingStatus string

// ActivityAudience Who may read an activity's content — see Activity.audience.
type ActivityAudience string

// ActivityLink defines model for ActivityLink.
type ActivityLink struct {
	ActivityId *string                `json:"activity_id,omitempty"`
	EntityId   string                 `json:"entity_id"`
	EntityType ActivityLinkEntityType `json:"entity_type"`
	Id         *string                `json:"id,omitempty"`
}

// ActivityLinkEntityType defines model for ActivityLink.EntityType.
type ActivityLinkEntityType string

// CreateActivityRequest defines model for CreateActivityRequest.
type CreateActivityRequest struct {
	AssigneeId *string `json:"assignee_id,omitempty"`
	Body       *string `json:"body,omitempty"`

	// ChannelProvider Which transport carried this message. REQUIRED when `kind=message` and MUST be
	// null otherwise; violating either direction returns
	// `422 code: field_not_valid_for_kind`. Must name a provider this installation has
	// registered.
	ChannelProvider *ProviderRef                    `json:"channel_provider,omitempty"`
	Direction       *CreateActivityRequestDirection `json:"direction,omitempty"`
	DueAt           *time.Time                      `json:"due_at,omitempty"`
	DurationSeconds *int                            `json:"duration_seconds,omitempty"`
	Kind            CreateActivityRequestKind       `json:"kind"`
	Links           *[]struct {
		EntityId   string                               `json:"entity_id"`
		EntityType CreateActivityRequestLinksEntityType `json:"entity_type"`
	} `json:"links,omitempty"`
	MeetingStatus *CreateActivityRequestMeetingStatus `json:"meeting_status,omitempty"`
	OccurredAt    *time.Time                          `json:"occurred_at,omitempty"`
	Raw           *map[string]interface{}             `json:"raw,omitempty"`

	// RemindAt Task only.
	RemindAt     *time.Time `json:"remind_at,omitempty"`
	Source       string     `json:"source"`
	SourceId     *string    `json:"source_id,omitempty"`
	SourceSystem *string    `json:"source_system,omitempty"`
	Subject      *string    `json:"subject,omitempty"`
}

// CreateActivityRequestDirection defines model for CreateActivityRequest.Direction.
type CreateActivityRequestDirection string

// CreateActivityRequestKind defines model for CreateActivityRequest.Kind.
type CreateActivityRequestKind string

// CreateActivityRequestLinksEntityType defines model for CreateActivityRequest.Links.EntityType.
type CreateActivityRequestLinksEntityType string

// CreateActivityRequestMeetingStatus defines model for CreateActivityRequest.MeetingStatus.
type CreateActivityRequestMeetingStatus string

// ProviderRef A reference to a messaging transport registered in THIS installation
// (ADR-0107/A158). Deliberately a pattern-constrained string rather than an enum:
// which providers exist is a deployment fact — what this binary composed, including
// any extension unit present under `extensions/` — so an enum here would assert that
// the legal set is identical in every installation, which is false. The contract
// states the invariant; `GET /v1/channel-providers` resolves the live set.
type ProviderRef = string

// RowVersion Monotonic row version, incremented by the server on every mutation (data-model §1.3a).
// Echoed back as the `version` field on every mutable entity. To make a write conditional,
// send the last-seen value in `If-Match`; a mismatch returns `409 code: version_skew`
// (ErrVersionSkew) so the client re-reads before retrying. Applies to the native SoR path,
// not only overlay mode.
type RowVersion = int64
