// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

// Command gen-queryenums derives, from the contract, which query parameters
// of which route are closed enums. The server refuses a value outside the
// enum with one 422 that names the allowed values. A new enum parameter is
// covered by being declared, with no handler code.
package main

import (
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"sort"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// routePrefix is the base path the generated router mounts every operation
// under; the chi pattern a request matches carries it.
const routePrefix = "/v1"

type queryEnum struct {
	Name   string
	Values []string
}

func main() {
	in := flag.String("in", "", "authoritative crm.yaml")
	out := flag.String("out", "", "generated Go table")
	flag.Parse()
	if *in == "" || *out == "" {
		log.Fatal("gen-queryenums: -in and -out are required")
	}
	doc, err := openapi3.NewLoader().LoadFromFile(*in)
	if err != nil {
		log.Fatalf("gen-queryenums: loading %s: %v", *in, err)
	}
	table := deriveTable(doc)
	formatted, err := format.Source([]byte(render(table)))
	if err != nil {
		log.Fatalf("gen-queryenums: formatting the generated table: %v", err)
	}
	if err := os.WriteFile(*out, formatted, 0o600); err != nil {
		log.Fatalf("gen-queryenums: %v", err)
	}
	fmt.Printf("%d routes with enum query parameters generated\n", len(table))
}

// deriveTable maps "METHOD /v1/path" to the enum query parameters of that
// operation. An operation-level parameter replaces a path-level one of the
// same name, as OpenAPI says.
func deriveTable(doc *openapi3.T) map[string][]queryEnum {
	table := map[string][]queryEnum{}
	for path, item := range doc.Paths.Map() {
		for method, op := range item.Operations() {
			if method != "GET" {
				continue
			}
			if enums := enumsOf(item.Parameters, op.Parameters); len(enums) > 0 {
				table[method+" "+routePrefix+path] = enums
			}
		}
	}
	return table
}

func enumsOf(pathLevel, opLevel openapi3.Parameters) []queryEnum {
	byName := map[string]*openapi3.Parameter{}
	for _, params := range []openapi3.Parameters{pathLevel, opLevel} {
		for _, ref := range params {
			if ref != nil && ref.Value != nil && ref.Value.In == openapi3.ParameterInQuery {
				byName[ref.Value.Name] = ref.Value
			}
		}
	}
	var out []queryEnum
	for name, param := range byName {
		if values := enumValues(param.Schema); len(values) > 0 {
			out = append(out, queryEnum{Name: name, Values: values})
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

// enumValues reads the closed string set off a parameter's schema, or its
// items when the parameter is an array. A set with any non-string member is
// not a vocabulary this table can compare a query value against.
func enumValues(ref *openapi3.SchemaRef) []string {
	if ref == nil || ref.Value == nil {
		return nil
	}
	schema := ref.Value
	if schema.Items != nil && schema.Items.Value != nil {
		schema = schema.Items.Value
	}
	values := make([]string, 0, len(schema.Enum))
	for _, raw := range schema.Enum {
		s, ok := raw.(string)
		if !ok {
			return nil
		}
		values = append(values, s)
	}
	return values
}

func render(table map[string][]queryEnum) string {
	routes := make([]string, 0, len(table))
	for route := range table {
		routes = append(routes, route)
	}
	sort.Strings(routes)

	var b strings.Builder
	b.WriteString("// Code generated by tools/gen-queryenums from api/crm.yaml. DO NOT EDIT.\n\n")
	b.WriteString("package compose\n\n")
	b.WriteString("// queryEnumTable maps \"METHOD /v1/path\" to the query parameters the contract\n")
	b.WriteString("// declares as closed enums, with the values each admits.\n")
	b.WriteString("var queryEnumTable = map[string][]queryEnum{\n")
	for _, route := range routes {
		fmt.Fprintf(&b, "\t%q: {\n", route)
		for _, e := range table[route] {
			quoted := make([]string, len(e.Values))
			for i, v := range e.Values {
				quoted[i] = fmt.Sprintf("%q", v)
			}
			fmt.Fprintf(&b, "\t\t{Name: %q, Values: []string{%s}},\n", e.Name, strings.Join(quoted, ", "))
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")
	return b.String()
}
