// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

// gen-configschema emits the JSON Schema for margince.yaml.
//
// WHY IT IS GENERATED. margince.yaml is sixteen sections deep and grows a field
// whenever a capability gains a switch. A hand-written schema is a second copy
// of deployconfig.Config, and the copy goes stale silently: an editor keeps
// validating against last quarter's shape and reports a new field as an error,
// which is worse than no schema at all. So the schema is derived from the
// struct the LOADER decodes into — the same reason tools/gen-composition reads
// the published extension.Name rule rather than restating it.
//
// The routing subtree rides along under $defs. It used to be its own file,
// which made sense while a routing FILE existed; with the binding living in
// margince.yaml under `seeds.ai_routing` and in the database, its shape belongs
// where the thing it describes is written.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"

	"github.com/margince/margince/backend/internal/platform/deployconfig"
)

func main() {
	pkgDir := flag.String("pkg", "", "the deployconfig package directory, read for field documentation")
	out := flag.String("out", "", "the schema file to write")
	routingGo := flag.String("routing-go", "", "the Go file that embeds the routing $defs for GET /ai/routing/schema")
	flag.Parse()
	if *pkgDir == "" || *out == "" || *routingGo == "" {
		fail(fmt.Errorf("gen-configschema needs -pkg, -out and -routing-go"))
	}
	docs, err := fieldDocs(*pkgDir)
	if err != nil {
		fail(err)
	}
	schema, err := buildSchema(reflect.TypeOf(deployconfig.Config{}), docs)
	if err != nil {
		fail(err)
	}
	encoded, err := encode(schema)
	if err != nil {
		fail(err)
	}
	if err := os.MkdirAll(filepath.Dir(*out), 0o750); err != nil {
		fail(err)
	}
	if err := os.WriteFile(*out, encoded, 0o600); err != nil {
		fail(err)
	}
	if err := writeRoutingGo(*routingGo); err != nil {
		fail(err)
	}
}

// writeRoutingGo embeds the routing $defs in the ai module, so the admin
// screen is served the very schema the editor gate holds to the parser rather
// than a second copy of it.
func writeRoutingGo(path string) error {
	var compact bytes.Buffer
	if err := json.Compact(&compact, routingDefs()); err != nil {
		return fmt.Errorf("gen-configschema: compacting the routing $defs: %w", err)
	}
	src := fmt.Sprintf("// Code generated by gen-configschema; DO NOT EDIT.\n\npackage ai\n\n"+
		"// routingSchemaJSON is the routing $defs of config/margince.schema.json.\n"+
		"const routingSchemaJSON = %q\n", compact.String())
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return fmt.Errorf("gen-configschema: creating the routing output directory: %w", err)
	}
	return os.WriteFile(path, []byte(src), 0o600)
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
