// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"reflect"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/gradionhq/margince/backend/internal/platform/deployconfig"
)

// object is a JSON Schema object node. A map would lose key order and make the
// generated file churn between runs; an ordered slice keeps the diff readable.
type object struct {
	pairs []pair
}

type pair struct {
	key string
	// A JSON node is a string, a boolean, a nested object or a raw subtree,
	// depending on the keyword — heterogeneous is what the format IS, and any
	// narrower type here would be a union spelled as an interface with one
	// implementation per JSON kind.
	//craft:ignore naked-any the value of a JSON Schema keyword, whose type varies by keyword
	value any
}

// set appends a keyword and its value, in the order the document reads.
//
//craft:ignore naked-any the value of a JSON Schema keyword, whose type varies by keyword — see pair.value
func (o *object) set(key string, value any) { o.pairs = append(o.pairs, pair{key, value}) }

func (o object) MarshalJSON() ([]byte, error) {
	var b bytes.Buffer
	b.WriteByte('{')
	for i, p := range o.pairs {
		if i > 0 {
			b.WriteByte(',')
		}
		k, err := json.Marshal(p.key)
		if err != nil {
			return nil, fmt.Errorf("gen-configschema: key %q: %w", p.key, err)
		}
		v, err := json.Marshal(p.value)
		if err != nil {
			return nil, fmt.Errorf("gen-configschema: value at %q: %w", p.key, err)
		}
		b.Write(k)
		b.WriteByte(':')
		b.Write(v)
	}
	b.WriteByte('}')
	return b.Bytes(), nil
}

// buildSchema walks the config struct and returns the document root.
func buildSchema(root reflect.Type, docs docIndex) (object, error) {
	body, err := structNode(root, docs)
	if err != nil {
		return object{}, err
	}
	var doc object
	doc.set("$schema", "https://json-schema.org/draft/2020-12/schema")
	doc.set("$id", "https://margince.dev/schema/margince.json")
	doc.set("title", "Margince installation config (margince.yaml)")
	doc.set("$comment", "GENERATED by tools/gen-configschema from deployconfig.Config — do not edit")
	for _, p := range body.pairs {
		doc.set(p.key, p.value)
	}
	doc.set("$defs", routingDefs())
	return doc, nil
}

// structNode renders one Go struct as a schema object.
//
// additionalProperties is false because the loader decodes with
// KnownFields(true): a key margince.yaml does not know is a boot ERROR, and a
// schema that shrugged at it would tell an operator their typo is fine right up
// until the server refuses to start.
func structNode(t reflect.Type, docs docIndex) (object, error) {
	props := &object{}
	for i := range t.NumField() {
		f := t.Field(i)
		if inlined(f) {
			// Refused rather than skipped. An inline embed's fields are decoded
			// at THIS level, so skipping it emits a schema missing keys the
			// loader accepts — and with additionalProperties:false that schema
			// then reports valid config as an error. deployconfig has no inline
			// field today; the day it gains one, generation stops here instead
			// of shipping a document that is wrong in the strictest direction.
			return object{}, fmt.Errorf("%s.%s is yaml:\",inline\" and this generator does not flatten it — teach structNode, do not skip", t.Name(), f.Name)
		}
		name, ok := yamlName(f)
		if !ok {
			continue
		}
		node, err := fieldNode(t, f, docs)
		if err != nil {
			return object{}, err
		}
		props.set(name, node)
	}
	var out object
	out.set("type", "object")
	out.set("additionalProperties", false)
	out.set("properties", props)
	return out, nil
}

// fieldNode renders one field, documented from the Go source above it.
func fieldNode(owner reflect.Type, f reflect.StructField, docs docIndex) (object, error) {
	node, err := typeNode(f.Type, docs)
	if err != nil {
		return object{}, fmt.Errorf("%s.%s: %w", owner.Name(), f.Name, err)
	}
	doc := docs.lookup(owner.Name(), f.Name)
	if doc == "" {
		doc = docs.forType(namedType(f.Type).Name())
	}
	if doc != "" {
		documented := object{}
		documented.set("description", doc)
		documented.pairs = append(documented.pairs, node.pairs...)
		return documented, nil
	}
	return node, nil
}

// inlined reports whether a field's contents are decoded at the parent's level.
func inlined(f reflect.StructField) bool {
	tag, ok := f.Tag.Lookup("yaml")
	if !ok {
		return false
	}
	for _, opt := range strings.Split(tag, ",")[1:] {
		if opt == "inline" {
			return true
		}
	}
	return false
}

// yamlName reads the field's yaml key, or reports that it has none.
func yamlName(f reflect.StructField) (string, bool) {
	tag, ok := f.Tag.Lookup("yaml")
	if !ok {
		return "", false
	}
	name, _, _ := strings.Cut(tag, ",")
	if name == "" || name == "-" {
		return "", false
	}
	return name, true
}

// typeNode maps one Go type onto its schema.
func typeNode(t reflect.Type, docs docIndex) (object, error) {
	// A pointer is how this config spells "unset is distinguishable from the
	// zero value"; the schema cares about the pointee.
	if t.Kind() == reflect.Pointer {
		return typeNode(t.Elem(), docs)
	}
	if node, special := specialNode(t); special {
		return node, nil
	}
	switch t.Kind() {
	case reflect.String:
		return scalar("string"), nil
	case reflect.Bool:
		return scalar("boolean"), nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return scalar("integer"), nil
	case reflect.Float32, reflect.Float64:
		return scalar("number"), nil
	case reflect.Slice:
		items, err := typeNode(t.Elem(), docs)
		if err != nil {
			return object{}, err
		}
		var out object
		out.set("type", "array")
		out.set("items", items)
		return out, nil
	case reflect.Map:
		if t.Key().Kind() != reflect.String {
			return object{}, fmt.Errorf("map key %s is not a string — YAML gives string keys, so this type cannot round-trip", t.Key())
		}
		values, err := typeNode(t.Elem(), docs)
		if err != nil {
			return object{}, err
		}
		// additionalProperties carries the VALUE schema here rather than false:
		// the keys are the operator's to choose (a model id, a provider name),
		// which is the one place this document does not know them in advance.
		var out object
		out.set("type", "object")
		out.set("additionalProperties", values)
		return out, nil
	case reflect.Struct:
		return structNode(t, docs)
	default:
		return object{}, fmt.Errorf("no schema mapping for %s (kind %s) — teach typeNode, do not guess", t, t.Kind())
	}
}

// specialNode covers the types whose YAML form is not their Go shape.
func specialNode(t reflect.Type) (object, bool) {
	switch t {
	case reflect.TypeOf(deployconfig.Secret{}):
		// A reference, never a literal: the loader refuses anything else, and
		// the pattern comes from the loader rather than being written twice.
		var out object
		out.set("type", "string")
		out.set("pattern", deployconfig.SecretRefPattern)
		// The two FORMS, named after neither field nor vendor: this node is
		// reached by every Secret in the file, and an example naming one of them
		// is wrong everywhere else — the admin password suggesting an SMTP
		// variable is worse than no example at all.
		out.set("examples", []string{"${env:VARIABLE_NAME}", "${file:/run/secrets/name}"})
		return out, true
	case reflect.TypeOf(yaml.Node{}):
		// The one free-form subtree: seeds.ai_routing is decoded later, by the
		// ai package, against the shape under $defs.
		var out object
		out.set("$ref", "#/$defs/aiRouting")
		return out, true
	default:
		return object{}, false
	}
}

// namedType unwraps a pointer so a *Section is documented like a Section.
func namedType(t reflect.Type) reflect.Type {
	if t.Kind() == reflect.Pointer {
		return t.Elem()
	}
	return t
}

func scalar(kind string) object {
	var out object
	out.set("type", kind)
	return out
}

// encode renders the document, indented, with a trailing newline so the file is
// a well-formed text file and re-generating it produces no whitespace diff.
func encode(doc object) ([]byte, error) {
	var b bytes.Buffer
	enc := json.NewEncoder(&b)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	if err := enc.Encode(doc); err != nil {
		return nil, fmt.Errorf("gen-configschema: encoding: %w", err)
	}
	return b.Bytes(), nil
}
