// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package aicert

// The certified decision table: which (task, site, provider, model) the
// decisions lane may serve, generated from the committed decision records into
// internal/modules/ai/decisioncert_gen.go. The runtime reads only that table,
// so a record that goes stale drops its row at the next `make gen`, and the
// drift check here names the record whose row moved.

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"regexp"
	"sort"
	"strings"

	"github.com/margince/margince/backend/internal/compose/aitasks"
	"github.com/margince/margince/backend/internal/modules/ai"
)

// decisionCertHeader is the generated file's head, down to the package clause.
const decisionCertHeader = `// Code generated by compose/aicert/decisioncertcmd from internal/compose/aicert/records. DO NOT EDIT.
// Regenerate with ` + "`make gen`" + `. A row exists for every decision record that is certified
// and whose scenario stamps are the ones this build computes; a stale record has none.

package ai
`

// decisionCertRecordsDir is how a row's comment names the records tree: the
// directory the corpus and records sit beside, as every aicert message spells it.
const decisionCertRecordsDir = "records"

// DecisionCertRow is one row of the generated table, with the records that
// earned it — named on the row, so a diff that drops it names its record.
type DecisionCertRow struct {
	Key     ai.DecisionCertKey
	Cert    ai.DecisionCert
	Records []string
}

// DecisionCertTable is the table this build's corpus, census and records give,
// beside the readiness it was read from.
func DecisionCertTable(corpus []Scenario, census *aitasks.Registry, records []Record) ([]DecisionCertRow, []DecisionRow, error) {
	stamps, err := CurrentDecisionStamps(corpus, census)
	if err != nil {
		return nil, nil, err
	}
	readiness := DecisionReadiness(stamps, records)
	return DecisionCertRows(readiness), readiness, nil
}

// Serves is whether this decision record earns a row in the generated table:
// certified, still describing every scenario it measured, and measuring at
// least one the site still ships. A record the corpus has moved out from under
// serves nothing. Asked of the record rather than of its table key, because
// the key names no environment class and two records can share one.
func (r DecisionRow) Serves() bool {
	return r.Record.Verdict == VerdictCertified && !r.Standing.Stale && r.Standing.Measured > 0
}

// DecisionCertRows is one row per certified key, sorted by key. Two current
// records of one key — one binding certified under two environment classes —
// share the row, which names both; the first in record order supplies its
// stamp.
func DecisionCertRows(readiness []DecisionRow) []DecisionCertRow {
	byKey := map[ai.DecisionCertKey]*DecisionCertRow{}
	for _, row := range readiness {
		if !row.Serves() {
			continue
		}
		rec := row.Record
		key := ai.DecisionCertKey{Task: ai.Task(rec.Task), Site: rec.Site, Provider: rec.Provider, Model: rec.Model}
		held, seen := byKey[key]
		if !seen {
			held = &DecisionCertRow{Key: key, Cert: ai.DecisionCert{PromptVersion: rec.PromptVersion, CorpusVersion: rec.CorpusVersion}}
			byKey[key] = held
		}
		held.Records = append(held.Records, recordPath(decisionCertRecordsDir, rec))
	}
	rows := make([]DecisionCertRow, 0, len(byKey))
	for _, row := range byKey {
		rows = append(rows, *row)
	}
	sort.Slice(rows, func(i, j int) bool { return decisionCertKeyLess(rows[i].Key, rows[j].Key) })
	return rows
}

func decisionCertKeyLess(a, b ai.DecisionCertKey) bool {
	if a.Task != b.Task {
		return a.Task < b.Task
	}
	if a.Site != b.Site {
		return a.Site < b.Site
	}
	if a.Provider != b.Provider {
		return a.Provider < b.Provider
	}
	return a.Model < b.Model
}

// RenderDecisionCertTable is the generated file for rows, gofmt'd.
func RenderDecisionCertTable(rows []DecisionCertRow) ([]byte, error) {
	var src strings.Builder
	src.WriteString(decisionCertHeader)
	if len(rows) == 0 {
		src.WriteString("\nvar decisionCertified = map[DecisionCertKey]DecisionCert{}\n")
	} else {
		src.WriteString("\nvar decisionCertified = map[DecisionCertKey]DecisionCert{\n")
		for _, row := range rows {
			for _, path := range row.Records {
				fmt.Fprintf(&src, "\t// %s\n", path)
			}
			fmt.Fprintf(&src, "\t{Task: %q, Site: %q, Provider: %q, Model: %q}: {PromptVersion: %q, CorpusVersion: %q},\n",
				row.Key.Task, row.Key.Site, row.Key.Provider, row.Key.Model, row.Cert.PromptVersion, row.Cert.CorpusVersion)
		}
		src.WriteString("}\n")
	}
	formatted, err := format.Source([]byte(src.String()))
	if err != nil {
		return nil, fmt.Errorf("aicert: the decision certification table does not format: %w", err)
	}
	return formatted, nil
}

// rowRecord matches the comment line a row names its record on.
var rowRecord = regexp.MustCompile(`(?m)^\t// (` + decisionCertRecordsDir + `/\S+\.json)$`)

// DecisionCertDrift compares the committed table with the one this build
// renders, naming each record whose row was added or dropped. A dropped row
// whose record went stale says so, because the fix is a re-run or deleting the
// record, not a regeneration that would only make the drop official.
func DecisionCertDrift(committed []byte, rows []DecisionCertRow, readiness []DecisionRow) error {
	want, err := RenderDecisionCertTable(rows)
	if err != nil {
		return err
	}
	if bytes.Equal(committed, want) {
		return nil
	}
	had := map[string]bool{}
	for _, m := range rowRecord.FindAllSubmatch(committed, -1) {
		had[string(m[1])] = true
	}
	has := map[string]bool{}
	for _, row := range rows {
		for _, path := range row.Records {
			has[path] = true
		}
	}
	problems := driftProblems(had, has, readiness)
	return errors.New("the decision certification table is not what the committed records give — run `make gen`" +
		strings.Join(append([]string{""}, problems...), "\n  - "))
}

// driftProblems names each record whose row the committed table (had) and the
// rendered one (has) disagree about, sorted.
func driftProblems(had, has map[string]bool, readiness []DecisionRow) []string {
	var problems []string
	for _, row := range readiness {
		path := recordPath(decisionCertRecordsDir, row.Record)
		switch {
		case had[path] && !has[path] && row.Standing.Stale:
			problems = append(problems, fmt.Sprintf("%s went stale (%s) and loses its row: re-certify it or delete the record", path, row.Standing.Reason()))
		case had[path] && !has[path]:
			problems = append(problems, fmt.Sprintf("%s no longer earns a row", path))
		case has[path] && !had[path]:
			problems = append(problems, fmt.Sprintf("%s earns a row the committed table lacks", path))
		}
	}
	for path := range had {
		if !recordNamed(readiness, path) {
			problems = append(problems, fmt.Sprintf("%s has a row, and no such decision record is committed", path))
		}
	}
	sort.Strings(problems)
	return problems
}

func recordNamed(readiness []DecisionRow, path string) bool {
	for _, row := range readiness {
		if recordPath(decisionCertRecordsDir, row.Record) == path {
			return true
		}
	}
	return false
}
