// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package aicert

// The generated decision table: reproduced from the committed trees, a row
// dropped the moment its record's decision question moves, and the drop named
// by the record that lost it.

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/margince/margince/backend/internal/compose"
	"github.com/margince/margince/backend/internal/modules/ai"
)

// committedDecisionTable is the generated file the runtime reads.
var committedDecisionTable = filepath.Join("..", "..", "modules", "ai", "decisioncert_gen.go")

// The committed table is exactly what the committed corpus, census and records
// give. A decision record that went stale fails here, naming itself, before a
// runtime could serve a lane on a question it was never measured on.
func TestTheDecisionCertTableIsCurrent(t *testing.T) {
	census, err := compose.NewTaskCensus()
	if err != nil {
		t.Fatalf("building the census: %v", err)
	}
	corpus, err := LoadCorpus("corpus", census)
	if err != nil {
		t.Fatalf("loading the corpus: %v", err)
	}
	records, err := LoadRecords("records")
	if err != nil {
		t.Fatalf("loading the records: %v", err)
	}
	rows, readiness, err := DecisionCertTable(corpus, census, records)
	if err != nil {
		t.Fatalf("building the table: %v", err)
	}
	committed, err := os.ReadFile(committedDecisionTable)
	if err != nil {
		t.Fatalf("reading %s: %v", committedDecisionTable, err)
	}
	if err := DecisionCertDrift(committed, rows, readiness); err != nil {
		t.Fatal(err)
	}
}

// With no decision record there is no row, and the empty table is the
// placeholder the ai module shipped before the generator existed, byte for
// byte — so `make gen` over an empty record set changes nothing.
func TestAnEmptyRecordSetRendersTheCommittedPlaceholder(t *testing.T) {
	const placeholder = "// Code generated by compose/aicert/decisioncertcmd from internal/compose/aicert/records. DO NOT EDIT.\n" +
		"// Regenerate with `make gen`. A row exists for every decision record that is certified\n" +
		"// and whose scenario stamps are the ones this build computes; a stale record has none.\n" +
		"\n" +
		"package ai\n" +
		"\n" +
		"var decisionCertified = map[DecisionCertKey]DecisionCert{}\n"
	got, err := RenderDecisionCertTable(nil)
	if err != nil {
		t.Fatalf("RenderDecisionCertTable: %v", err)
	}
	if string(got) != placeholder {
		t.Fatalf("the empty table renders\n%s\nwant the placeholder\n%s", got, placeholder)
	}
}

// certifiedWidgetRecord is a certified decision record of the stand-in site,
// stamped under form.
func certifiedWidgetRecord(t *testing.T, form widgetForm) (Record, []Scenario) {
	t.Helper()
	scenarios := []Scenario{decidingScenario("basic", ai.TaskSiteTriage)}
	stamps, err := DecisionScenarioStamps(scenarios, decidingCensus(t, ai.TaskSiteTriage, form))
	if err != nil {
		t.Fatalf("DecisionScenarioStamps: %v", err)
	}
	return Record{
		Task: string(ai.TaskSiteTriage), Kind: KindDecision, Site: widgetVariant,
		Provider: jevLane.Provider, Model: jevLane.Model, EnvClass: string(ai.ProfileCloudFrontier),
		PromptVersion: FoldScenarioStamps(stamps), CorpusVersion: corpusVersionV1, Verdict: VerdictCertified,
		Scenarios: []ScenarioRecord{{Scenario: "basic", Site: widgetVariant, Stamp: stamps["basic"], Verdict: VerdictCertified}},
	}, scenarios
}

// Editing a decision criterion drops the row certified under the old one, and
// the drift names the record — the file to re-certify or delete.
func TestEditingACriterionDropsItsRowAndNamesTheRecord(t *testing.T) {
	was := defaultWidgetForm()
	rec, scenarios := certifiedWidgetRecord(t, was)
	rows, _, err := DecisionCertTable(scenarios, decidingCensus(t, ai.TaskSiteTriage, was), []Record{rec})
	if err != nil || len(rows) != 1 {
		t.Fatalf("under the criteria it was recorded with: %d rows, %v; want one", len(rows), err)
	}
	committed, err := RenderDecisionCertTable(rows)
	if err != nil {
		t.Fatalf("RenderDecisionCertTable: %v", err)
	}
	if !strings.Contains(string(committed), "// records/site_triage/decision_widget_jev_compatible_typesafe_jev-1.13_cloud_frontier.json") ||
		!strings.Contains(string(committed), `{Task: "site_triage", Site: "widget", Provider: "jev_compatible", Model: "typesafe/jev-1.13"}`) {
		t.Fatalf("the rendered row does not name its record and key:\n%s", committed)
	}

	edited := was
	edited.criterion = "the subject is a widget, and says so"
	rows, readiness, err := DecisionCertTable(scenarios, decidingCensus(t, ai.TaskSiteTriage, edited), []Record{rec})
	if err != nil {
		t.Fatalf("DecisionCertTable: %v", err)
	}
	if len(rows) != 0 {
		t.Fatalf("a criterion edit left %d rows; the record describes a question this build no longer asks", len(rows))
	}
	drift := DecisionCertDrift(committed, rows, readiness)
	if drift == nil {
		t.Fatal("the committed row survived its record going stale")
	}
	for _, want := range []string{"decision_widget_jev_compatible_", "re-certify it or delete the record", "make gen"} {
		if !strings.Contains(drift.Error(), want) {
			t.Errorf("the drift %q does not say %q", drift, want)
		}
	}
}

// A not_supported record earns no row, and neither does a certified one whose
// every measured scenario has left the corpus.
func TestOnlyACertifiedCurrentRecordEarnsARow(t *testing.T) {
	form := defaultWidgetForm()
	rec, scenarios := certifiedWidgetRecord(t, form)
	census := decidingCensus(t, ai.TaskSiteTriage, form)

	refused := rec
	refused.Verdict = VerdictNotSupported
	if rows, _, err := DecisionCertTable(scenarios, census, []Record{refused}); err != nil || len(rows) != 0 {
		t.Errorf("a not_supported record: %d rows, %v; want none", len(rows), err)
	}
	if rows, _, err := DecisionCertTable(nil, census, []Record{rec}); err != nil || len(rows) != 0 {
		t.Errorf("a record over a corpus that no longer holds its scenario: %d rows, %v; want none", len(rows), err)
	}
}
