// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package identity

// docs/reference/rbac-matrix.md is where someone who cannot read Go — an
// auditor, a customer's security reviewer, whoever signs off the deployment —
// finds out what the six seeded roles permit. A table maintained by hand is a
// claim about the code and ages into a lie; this one is rendered from the
// documents the server seeds and re-checked on every unit pass, so the
// published page is the permissions rather than a description of them.

import (
	"encoding/json"
	"maps"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/margince/margince/backend/internal/modules/identity/internal/policy"
)

// rbacMatrixDoc is the published page. repoArtifact lands on the backend module
// root, and docs/ belongs to the repository one level above it: the matrix is a
// document for readers, not an artifact of the Go module that renders it.
var rbacMatrixDoc = repoArtifact(filepath.Join("..", "docs", "reference", "rbac-matrix.md"))

// roleGrant and roleDocument mirror the JSON the server writes into
// role.permissions. The page is rendered from that JSON rather than from
// policy's in-memory types on purpose: the stored document is what a workspace
// actually gets, so a change to its wire shape surfaces here as a changed page
// instead of passing unnoticed.
type roleGrant struct {
	Create bool `json:"create"`
	Read   bool `json:"read"`
	Update bool `json:"update"`
	Delete bool `json:"delete"`
}

type roleDocument struct {
	Objects  map[string]roleGrant `json:"objects"`
	RowScope string               `json:"row_scope"`
}

func TestPublishedRBACMatrixMatchesTheSeededRoleDocuments(t *testing.T) {
	documents := make(map[string]roleDocument, len(systemRoles))
	for _, role := range systemRoles {
		var doc roleDocument
		if err := json.Unmarshal(policy.MustDefaultJSON(role.key), &doc); err != nil {
			t.Fatalf("decoding the seeded document for role %q: %v", role.key, err)
		}
		documents[role.key] = doc
	}
	syncArtifact(t, rbacMatrixDoc, renderRBACMatrix(documents))
}

func renderRBACMatrix(documents map[string]roleDocument) []byte {
	var page strings.Builder
	page.WriteString(matrixHeader)
	page.WriteString(matrixLegend)
	writeRoleTable(&page, documents)
	writeGrantTable(&page, documents)
	page.WriteString(matrixExclusions)
	return []byte(page.String())
}

// writeRoleTable lists the roles in the order the server seeds them, which runs
// from the widest authority to the narrowest — the order someone reads a
// permission table in.
func writeRoleTable(page *strings.Builder, documents map[string]roleDocument) {
	page.WriteString("## The six roles a workspace starts with\n\n")
	page.WriteString("| Role | Name in the app | Row scope |\n|---|---|---|\n")
	for _, role := range systemRoles {
		page.WriteString("| `" + role.key + "` | " + role.name + " | " +
			documents[role.key].RowScope + " |\n")
	}
	page.WriteString("\n")
}

func writeGrantTable(page *strings.Builder, documents map[string]roleDocument) {
	page.WriteString("## What each role may do to each kind of record\n\n| Object |")
	divider := "|---|"
	for _, role := range systemRoles {
		page.WriteString(" `" + role.key + "` |")
		divider += "---|"
	}
	page.WriteString("\n" + divider + "\n")
	for _, object := range matrixObjects(documents) {
		page.WriteString("| `" + object + "` |")
		for _, role := range systemRoles {
			page.WriteString(" " + renderCRUD(documents[role.key].Objects[object]) + " |")
		}
		page.WriteString("\n")
	}
	page.WriteString("\n")
}

// matrixObjects is the union of every object the seeded documents name, sorted
// alphabetically rather than left in policy's declaration order: a reader
// arrives holding an object name and needs to find its row. The union comes
// from the documents themselves because a role document is what reaches the
// database — an object nobody grants anything on has nothing to publish.
func matrixObjects(documents map[string]roleDocument) []string {
	named := map[string]struct{}{}
	for _, doc := range documents {
		for object := range doc.Objects {
			named[object] = struct{}{}
		}
	}
	return slices.Sorted(maps.Keys(named))
}

// renderCRUD spells a cell as the four verbs in one fixed order, holding the
// place of a verb the role lacks with a dash. Absence has to be as visible as
// presence: a reader scanning a column for what a role cannot do should not
// have to count letters.
func renderCRUD(held roleGrant) string {
	const verbs = "CRUD"
	cell := []byte("----")
	for i, granted := range []bool{held.Create, held.Read, held.Update, held.Delete} {
		if granted {
			cell[i] = verbs[i]
		}
	}
	return string(cell)
}

const matrixHeader = `# RBAC matrix: what each seeded role may do

<!-- Generated by backend/internal/modules/identity/rbacmatrix_test.go. Do not edit. -->

**This page is generated, and an edit made here is lost.** It is rendered
straight from the permission documents the server writes into every new
workspace, so it states what the software enforces — not what somebody believed
it enforced on the day they last wrote it down.

To change a permission, change the seeded policy in
backend/internal/modules/identity/internal/policy/policy.go and regenerate this
page from the backend directory:

    go test ./internal/modules/identity/ -run RBAC -update

The same test runs on every build without -update and fails when this page and
the seeded values disagree, so the two cannot drift apart unnoticed.

`

const matrixLegend = `## How to read the table

Each row is one kind of record the system governs. Each column is one of the
roles a new workspace starts with.

Every cell holds four positions — **C R U D** — always in that order:

- **C** — create a record of this kind
- **R** — read one
- **U** — update one
- **D** — delete or archive one

A letter means the role may do that. A dash in its place means it may not. So
CRU- is create, read and update but never delete, and ---- is no access at all.

**Row scope is a second, independent question,** and it belongs to the role
rather than to a cell, so it is listed once per role below. The letters say what
a role may do to a *kind* of record; row scope says *which* records of that kind
it may WRITE:

- **own** — only records the user owns.
- **team** — records the user owns and records owned by a teammate, resolved
  through live team membership.
- **all** — every record in the workspace.

Both questions have to pass, and they do not bind equally. Row scope narrows
WRITES; a customer record — person, organization, lead, deal, project — is read
by every seat that holds its read grant, whatever their scope. So a rep holding
CRU- on deals reads the whole workspace's deals and may update only the ones
their scope reaches, while a read-only auditor holding R--- reads them all and
changes none.

`

const matrixExclusions = `## What this page does not cover

Read this as one of several answers, not as the whole access-control story.

### Admin-only areas that have no row in the table

Parts of the system are not governed by these objects at all. They are open to
the admin role and to nobody else, whatever the table above says:

- **User administration** — inviting someone, changing a person's role,
  deactivating or reactivating an account.
- **Privacy and GDPR work** — erasing a subject's data, and assembling the
  export that answers a subject-access request.
- **The audit log** — reading the record of who changed what.

If the question is whether somebody can reach one of those, this page cannot
answer it. The only question there is whether that person holds the admin role.

### An agent gets no more than a row here shows, and normally much less

A person can lend their access to an AI agent by issuing it a passport. The
passport carries no role from this table. Its holder may do only what *both* of
these allow, at the moment of each call:

- the scopes written into the passport when it was issued, which are chosen for
  one job and are usually a narrow slice of what the person can do; and
- the live permissions of the person who granted it, re-read on every single
  call — so changing that person's role, or deactivating them, narrows or ends
  the agent's reach immediately, part-way through whatever it was doing.

The effect is an intersection: an agent's real permission is never wider than
the row you are reading, and is usually far narrower. Some actions narrow
further still — they stop and wait for a person to confirm them before they take
effect, and a few are closed to agents outright.

### Sharing one record with one person

Row scope is not the last word on which records somebody sees: an individual
record can also be shared with an individual user. That widens *which* records
they reach, never *what* they may do with them — sharing a deal achieves
nothing for a role whose deal cell reads ----.

### Hiding individual fields

The permission document has a slot for masking single fields from a role. No
seeded role uses it and the server does not act on it, so nothing on this page
says "this role sees the record but not the amount on it".
`
