// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

// Package snapshot carries the committed AI-certification readiness table into
// the running product.
//
// It is a LEAF on purpose. Package aicert imports compose (judge.go,
// promptversion.go, runner.go), so compose cannot import aicert — and the
// settings surface that answers "is the model serving this job certified?" lives
// in compose. This package imports neither, so both the generator that writes
// the file and the handler that reads it can depend on one description of its
// shape.
//
// The file is generated by `make gen` from the records and the corpus, and
// committed. Generated rather than computed at request time because deciding
// whether a record still describes what this build sends means driving every
// scenario's own request builder (aicert.ScenarioStamps) — developer-lane work,
// not something an HTTP handler does per page load.
package snapshot

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"strings"
)

// The four states a shipped site's certification can be in, mirroring the words
// the readiness report prints. They are separate because they are separate
// claims: current describes what this build sends, partial is current about
// everything it measured and has not seen the cases added since, stale describes
// prompts no longer sent, and absent describes nothing.
const (
	StatusCurrent = "current"
	StatusPartial = "partial"
	StatusStale   = "stale"
	StatusAbsent  = "absent"
)

//go:embed certification.json
var embedded []byte

// Row is one shipped invocation site's certification standing.
//
// The site is the unit, not the task: a task can ship several sites — cold_start
// ships four — and they routinely disagree, so folding them here would throw
// away the only evidence a reader has for WHICH part of a job is weak.
type Row struct {
	Task     string `json:"task"`
	Site     string `json:"site"`
	Provider string `json:"provider"`
	// Model is the model the record names as having served the runs.
	Model    string `json:"model"`
	EnvClass string `json:"env_class"`
	Status   string `json:"status"`
	// Band is the verdict this site's own runs folded to, empty on an absent row.
	// Empty rather than a zero word because "not_supported" is a measurement and
	// "never measured" is not.
	Band string `json:"band,omitempty"`
	// Scope is how much of the site the runs actually covered — a case that
	// grades one reply of a multi-turn path certifies less than the path.
	Scope string `json:"scope,omitempty"`
	// Runs and Passed are counts of runs on THIS site, not the task's pool.
	Runs   int `json:"runs"`
	Passed int `json:"passed"`
	// Measured and Pending count this site's current scenarios: how many the
	// record scored and still describes, and how many it has never seen. Pending
	// above zero on a non-stale record is what makes it partial.
	Measured int `json:"measured_scenarios"`
	Pending  int `json:"pending_scenarios"`
	// RanAt is the record's own RFC 3339 stamp, empty on an absent row.
	RanAt string `json:"ran_at,omitempty"`
}

// Snapshot is the whole committed table.
type Snapshot struct {
	// GeneratedFrom names the records directory the rows were read from, so a
	// reader of the committed file can tell which tree produced it.
	GeneratedFrom string `json:"generated_from"`
	Rows          []Row  `json:"rows"`

	// byKey is built on Load. Absent from the JSON: it is an index, not content.
	byKey map[string]Row
}

// keySeparator cannot appear in any of the five fields it joins — task and site
// come from the task contract's identifiers, provider and env class from fixed
// vocabularies, and a model id is a vendor path. Load rejects a row that
// contains it rather than letting two different rows collide into one key.
const keySeparator = "\x1f"

// Load decodes the committed snapshot.
func Load() (Snapshot, error) {
	return decode(embedded)
}

// FromRows indexes rows that did not arrive as a file.
//
// It exists so a caller building a snapshot in a test goes through the same
// indexing and the same duplicate refusal the product does. A test that assembled
// the map itself would prove nothing about the lookup the binary performs.
func FromRows(rows []Row) (Snapshot, error) {
	return index(Snapshot{Rows: rows})
}

func decode(raw []byte) (Snapshot, error) {
	var snap Snapshot
	if err := json.Unmarshal(raw, &snap); err != nil {
		return Snapshot{}, fmt.Errorf("decoding the certification snapshot: %w", err)
	}
	return index(snap)
}

func index(snap Snapshot) (Snapshot, error) {
	snap.byKey = make(map[string]Row, len(snap.Rows))
	for _, row := range snap.Rows {
		key, err := row.key()
		if err != nil {
			return Snapshot{}, err
		}
		if _, duplicate := snap.byKey[key]; duplicate {
			return Snapshot{}, fmt.Errorf(
				"the certification snapshot carries two rows for %s/%s on %s:%s under %s; "+
					"the key admits one measurement, so regenerate it with `make gen`",
				row.Task, row.Site, row.Provider, row.Model, row.EnvClass,
			)
		}
		snap.byKey[key] = row
	}
	return snap, nil
}

func (r Row) key() (string, error) {
	fields := []string{r.Task, r.Site, r.Provider, r.Model, r.EnvClass}
	for _, field := range fields {
		if strings.Contains(field, keySeparator) {
			return "", fmt.Errorf("certification row field %q contains the key separator, so it cannot be indexed", field)
		}
	}
	return strings.Join(fields, keySeparator), nil
}

// For finds the row measuring one site on one binding, in one environment class.
//
// The environment class is part of the key and not a detail: a cloud_frontier
// measurement says nothing about the same model under eu_hosted, and a lookup
// that ignored it would let evidence from one hosting posture certify another.
func (s Snapshot) For(task, site, provider, model, envClass string) (Row, bool) {
	key, err := (Row{Task: task, Site: site, Provider: provider, Model: model, EnvClass: envClass}).key()
	if err != nil {
		return Row{}, false
	}
	// Rows is exported and the index is not, so a caller can decode JSON straight
	// into a Snapshot and hold every row with no index at all. Left alone that
	// reads the nil map and answers "not measured" about a table which has the
	// answer — the one failure of this type that looks like data rather than a
	// bug.
	//
	// A caller bug, then, not an input to report gracefully: aicert.Verdict
	// panics on an even run count for the same reason, and the same reasoning
	// applies here. Indexing lazily instead would have to swallow the duplicate
	// refusal index performs, which is the one thing this type exists to enforce.
	if s.byKey == nil && len(s.Rows) > 0 {
		panic("aicert/snapshot: For on a Snapshot that was never indexed — build one with " +
			"Load or FromRows rather than decoding JSON straight into the struct, or the " +
			"duplicate-row refusal never runs")
	}
	row, found := s.byKey[key]
	return row, found
}

// MeasuredElsewhere says whether some row measures this site on this binding
// under a DIFFERENT environment class.
//
// It exists so a screen can distinguish "we have never measured this" from "we
// have measured it, on another hosting posture, and that does not carry over".
// The second is evidence a reader can go and look at; reporting it as the first
// throws that away.
func (s Snapshot) MeasuredElsewhere(task, site, provider, model, envClass string) bool {
	for _, row := range s.Rows {
		if row.Task == task && row.Site == site &&
			row.Provider == provider && row.Model == model &&
			row.EnvClass != envClass && row.Status != StatusAbsent {
			return true
		}
	}
	return false
}
