// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/mod/modfile"

	"github.com/margince/margince/backend/pkg/extension"
)

// compositionModule is the constant import path the role binaries wire
// (backend/go.mod resolves it to the committed vanilla stub; the
// generated go.work overrides it with build/composition/backend).
const compositionModule = "github.com/margince/margince/composition"

// extensionsGenHeader is shared by the vanilla stub and every composed
// output — the vanilla body below it must stay byte-identical to
// composition/extensions_gen.go (held by `-verify` via stubMatchesVanilla).
const extensionsGenHeader = `// Code generated by gen-composition from the enabled set under extensions/; DO NOT EDIT.
// Regenerate: make gen (tools/gen-composition). Bare go builds resolve this module's
// committed vanilla stub (composition/ at the repo root) via backend/go.mod's replace;
// composed builds use the generated module under build/composition/ via its go.work.

package composition

import (
`

// extensionsGenSurfaceImport is the one import every lane needs; the
// encoding/json line above it is emitted only when a verb actually carries a
// schema, because an unused import does not compile and the vanilla lane has
// none.
const extensionsGenSurfaceImport = "\t\"github.com/margince/margince/backend/pkg/extension\"\n"

const extensionsGenDoc = `
// Extensions returns the composed extension set for this installation;
// vanilla (an empty extensions/ tree) composes none.
func Extensions() []extension.Extension {
`

// extensionsGenVerbsDoc introduces the contract-derived half of the wiring.
// The literals below it are why the boot needs no file I/O: every refusal in
// compose/extensiontools.go reads a field of one of these values.
const extensionsGenVerbsDoc = `
// Verbs returns every governed operation the enabled units' contract
// fragments declare, read out of the merged contracts at generation time and
// re-emitted here as literals — so a bare role binary, which ships no
// repository, still knows each operation's route, risk tier, requested scope
// and selection prose.
func Verbs() []extension.Verb {
`

// extensionsGenJobsDoc introduces the scheduled-job half of the wiring, on
// exactly the terms the verb literals are emitted on: compose/extjobs.go's two
// boot refusals read Tier and RequestedScope, and a bare role binary ships no
// repository to read the merged contract back from.
const extensionsGenJobsDoc = `
// Jobs returns every scheduled job the enabled units' jobs.yaml fragments
// declare, read out of the merged contract at generation time and re-emitted
// here as literals — so a bare role binary knows each job's cadence, wall
// clocks, queue, attempt cap, risk tier and requested scope.
func Jobs() []extension.JobDeclaration {
`

// extensionsGenDurationHelper is emitted beside the job literals, and only when
// there are any. A duration has no Go literal a reviewer can read — the value
// IS a nanosecond count — so emitting 21600000000000 would put the one number
// in this file nobody can check by eye into the field an operator most wants to
// check. The contract's own spelling goes in instead, parsed back at the one
// place it is used.
//
// It panics on a malformed string, which cannot happen: the generator parsed
// the same string through the same function before emitting it. Same posture as
// mustBe below, and for the same reason — a generated invariant that is somehow
// false must stop the boot, not be worked around.
const extensionsGenDurationHelper = `
func mustDuration(s string) time.Duration {
	d, err := time.ParseDuration(s)
	if err != nil {
		panic("composition: generated duration " + s + " does not parse: " + err.Error())
	}
	return d
}
`

const frontendGenHeader = `// Code generated by gen-composition from the enabled set under extensions/; DO NOT EDIT.
// Regenerate: make gen (backend/tools/gen-composition). The DEFAULT (vanilla) lane
// resolves the committed empty-tree copy of this file, at
// frontend/src/composition/extensions.gen.ts, through tsconfig's
// "@composition/extensions" alias; a composed lane repoints that alias at
// build/composition/frontend/ — the TypeScript mirror of what GOWORK does for
// the Go lane.
//
// Descriptors only. A unit ships no TSX: what an installation composes into the
// SPA is the set of governed operations its contract fragments publish, read out
// of the MERGED contracts at generation time — the same source the routes, the
// agent tools and the unit manifests derive from, so a screen cannot advertise an
// operation the server does not serve.

/** One governed operation an enabled unit's contract fragment publishes. */
export type ExtensionVerbDescriptor = {
  readonly operationId: string;
  readonly route: string;
  readonly method: string;
  readonly title: string;
  readonly version: string;
  /**
   * The RBAC object the operation gates on, or "" when it gates on none.
   *
   * A plain string, not a union: this file is generated, and the generator
   * cannot enumerate what a unit will declare. app/extensions.ts narrows it
   * into the capability vocabulary, which is where the ext_ grammar is
   * checked once.
   */
  readonly rbacObject: string;
};

/** One enabled extension unit, as the composed installation publishes it. */
export type ExtensionDescriptor = {
  readonly name: string;
  readonly verbs: readonly ExtensionVerbDescriptor[];
  /**
   * The scope the unit's declared secrets ask for, or "" when it declares
   * none. A unit spanning both scopes is refused at generation time, so this
   * answers for every secret the unit has rather than for one of them.
   *
   * It is what decides where the unit is offered in Settings: "user" is one
   * member's own credential and belongs on their Connections page, "workspace"
   * is the installation's and belongs under Integrations, and "" is a unit
   * with nothing for either page to manage. A plain string union rather than a
   * derived flag, because the two values are the two the manifest already
   * publishes and the SPA should be reading the same vocabulary an operator
   * reads.
   */
  readonly secretScope: "user" | "workspace" | "";
};

export const extensions: readonly ExtensionDescriptor[] = `

// composition is everything one read of the enabled set produces: the
// deterministic output files, the governance the merged contracts publish, and
// each unit's derived manifest. They travel together because they are one
// derivation — a lane that re-read any of them separately would be reading the
// same declarations a second time, which is how two artifacts of one tree come
// to disagree.
type composition struct {
	// Files is every deterministic output (everything except go.work.sum,
	// which only the go command writes), keyed by path relative to
	// build/composition/.
	Files     map[string][]byte
	Verbs     []declaredVerb
	Jobs      []extension.JobDeclaration
	Manifests []derivedManifest
}

// composedFiles builds the composition from the enabled set under extensions/.
func composedFiles(root string) (composition, error) {
	units, err := scanExtensions(root)
	if err != nil {
		return composition{}, err
	}
	work, goVersion, err := composedWork(root, units)
	if err != nil {
		return composition{}, err
	}
	contracts, err := composedContracts(root, units)
	if err != nil {
		return composition{}, err
	}
	// Read back OUT of the merged contracts, not out of the fragments: the
	// governance the composed program serves is derived from the document a
	// client is handed. See extverbs.go.
	verbs, err := extensionVerbs(units, contracts)
	if err != nil {
		return composition{}, err
	}
	// The same read, on the jobs contract: a scheduled job's mechanics are
	// declared in the merged document and nowhere in Go.
	jobDecls, err := extensionJobs(units, contracts)
	if err != nil {
		return composition{}, err
	}
	// The declarations themselves, which the manifests and the SPA registry
	// below are both a projection of. Derived here, after the verbs a unit's
	// tools are validated against, and read exactly once.
	manifests, err := deriveUnitManifests(root, units, verbs, jobDecls)
	if err != nil {
		return composition{}, err
	}
	// Every unit's copy, merged into one overlay per locale. Collected here
	// rather than in scanUnit because the collision rule is cross-unit: no
	// single unit can see another's keys.
	var locales []unitLocale
	for _, u := range units {
		supplied, err := collectUnitLocales(u.Name, u.Dir)
		if err != nil {
			return composition{}, err
		}
		locales = append(locales, supplied...)
	}
	mergedCopy, err := mergeUnitLocales(locales)
	if err != nil {
		return composition{}, err
	}
	wiring, err := canonicalGoSource("backend/extensions_gen.go", extensionsGen(units, verbs, jobDecls))
	if err != nil {
		return composition{}, err
	}
	files := map[string][]byte{
		goWorkFile:                   work,
		"backend/go.mod":             composedGoMod(goVersion),
		"backend/extensions_gen.go":  wiring,
		"frontend/extensions.gen.ts": frontendGen(manifests, verbs),
		"frontend/extscreens.gen.ts": extScreensGen(units),
		"frontend/extlocales.gen.ts": extLocalesGen(mergedCopy),
	}
	// The effective contracts: base + every enabled unit's fragments. With
	// no fragments each one is its base, byte-identical — see mergeContract.
	for base, content := range contracts {
		files["api/"+base] = content
	}
	return composition{Files: files, Verbs: verbs, Jobs: jobDecls, Manifests: manifests}, nil
}

// canonicalGoSource parses emitted Go source and requires it to already
// be canonical gofmt: a template bug surfaces at gen time under this
// name instead of at the next go build, and a formatting drift is an
// error rather than silently adopted — the byte-identity gates (stub ==
// vanilla output, regeneration == recorded hashes) depend on the emitter
// producing canonical bytes itself.
func canonicalGoSource(name string, src []byte) ([]byte, error) {
	formatted, err := format.Source(src)
	if err != nil {
		return nil, fmt.Errorf("%s: generated source does not parse: %w", name, err)
	}
	if !bytes.Equal(formatted, src) {
		return nil, fmt.Errorf("%s: generated source is not canonical gofmt — fix the emitter, not the output", name)
	}
	return src, nil
}

// composedWork emits the composed workspace: the root go.work members
// (the single source of truth for the core set), the generated
// composition module, and each enabled extension module — sorted, paths
// relative to build/composition/go.work.
func composedWork(root string, units []extensionUnit) ([]byte, string, error) {
	raw, err := os.ReadFile(filepath.Join(root, goWorkFile)) // #nosec G304 -- reads the repo's own go.work at a computed path
	if err != nil {
		return nil, "", err
	}
	rootWork, err := modfile.ParseWork(goWorkFile, raw, nil)
	if err != nil {
		return nil, "", fmt.Errorf("root go.work: %w", err)
	}
	if rootWork.Go == nil {
		return nil, "", fmt.Errorf("root go.work carries no go directive")
	}
	// Only go + use are carried over; silently dropping a replace,
	// toolchain or godebug directive would make the composed lane resolve
	// differently from the bare one. Support arrives when a directive is
	// actually needed — until then, refuse loudly.
	if len(rootWork.Replace) > 0 || rootWork.Toolchain != nil || len(rootWork.Godebug) > 0 {
		return nil, "", fmt.Errorf("root go.work carries replace/toolchain/godebug directives gen-composition does not compose yet — extend composedWork before using them")
	}
	goVersion := rootWork.Go.Version

	members := []string{"./backend"}
	for _, use := range rootWork.Use {
		members = append(members, path.Join("../..", use.Path))
	}
	for _, u := range units {
		members = append(members, "../../extensions/"+u.Name)
	}
	sort.Strings(members)

	var b strings.Builder
	b.WriteString("// Code generated by gen-composition; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "go %s\n\nuse (\n", goVersion)
	for _, m := range members {
		// AutoQuote: a member path needing quoting (spaces) must stay a
		// valid use directive, not a broken raw token.
		fmt.Fprintf(&b, "\t%s\n", modfile.AutoQuote(m))
	}
	b.WriteString(")\n")
	return []byte(b.String()), goVersion, nil
}

// composedGoMod declares the generated composition module: module + go
// line only — the workspace resolves the backend and extension modules,
// no require/replace needed.
func composedGoMod(goVersion string) []byte {
	return []byte(fmt.Sprintf("// Code generated by gen-composition; DO NOT EDIT.\n\nmodule %s\n\ngo %s\n", compositionModule, goVersion))
}

// extensionsGen emits the composition wiring. The empty set reproduces
// the committed vanilla stub byte-for-byte; a non-empty set constructs
// each unit in sorted-name order under positional import aliases
// (deterministic, collision-free regardless of module path shape), each
// pinned to its extensions/<name> directory — composition.json and the
// boot inventory attribute the unit by that name, so a declaration
// disagreeing with it must not compose under a different identity.
func extensionsGen(units []extensionUnit, verbs []declaredVerb, jobDecls []extension.JobDeclaration) []byte {
	var b strings.Builder
	b.WriteString(extensionsGenHeader)
	if anySchema(verbs) {
		b.WriteString("\t\"encoding/json\"\n")
	}
	if len(jobDecls) > 0 {
		b.WriteString("\t\"time\"\n")
	}
	if anySchema(verbs) || len(jobDecls) > 0 {
		b.WriteString("\n")
	}
	b.WriteString(extensionsGenSurfaceImport)
	if len(units) > 0 {
		b.WriteString("\n")
		// TWO orders, and they are not the same one. The alias index is the
		// unit's position in the enabled set (unit-name order), because that
		// is the order Extensions() wires the units in and the two must agree.
		// gofmt, however, sorts an import group by PATH — and a unit's module
		// path is its own to choose, so the two orders coincide only while
		// every unit sits under the repo's module prefix. One unit published
		// from another domain (a fixture at example.margince.dev, a real
		// third-party unit) sorts ahead of them all, and emitting the lines in
		// alias order would then produce a group gofmt would reorder, which
		// canonicalGoSource refuses. Sorting the LINES by path leaves the
		// aliases attached to their units and makes the block canonical for
		// any set of module paths.
		order := make([]int, len(units))
		for i := range order {
			order[i] = i
		}
		sort.SliceStable(order, func(a, b int) bool {
			return units[order[a]].ModulePath < units[order[b]].ModulePath
		})
		for _, i := range order {
			fmt.Fprintf(&b, "\text%d %q\n", i, units[i].ModulePath)
		}
	}
	b.WriteString(")\n")
	b.WriteString(extensionsGenDoc)
	if len(units) == 0 {
		b.WriteString("\treturn nil\n}\n")
		b.WriteString(extensionsGenVerbsDoc)
		b.WriteString("\treturn nil\n}\n")
		b.WriteString(extensionsGenJobsDoc)
		b.WriteString("\treturn nil\n}\n")
		return []byte(b.String())
	}
	b.WriteString("\treturn []extension.Extension{\n")
	for i, u := range units {
		fmt.Fprintf(&b, "\t\tmustBe(%q, ext%d.New()),\n", u.Name, i)
	}
	b.WriteString("\t}\n}\n")
	b.WriteString(extensionsGenVerbsDoc)
	writeVerbLiterals(&b, verbs)
	b.WriteString(extensionsGenJobsDoc)
	writeJobLiterals(&b, jobDecls)
	if len(jobDecls) > 0 {
		b.WriteString(extensionsGenDurationHelper)
	}
	b.WriteString(`
// mustBe pins a unit to its extensions/<name> directory: a declaration
// whose Name disagrees with the directory it shipped in is a wiring
// defect and aborts the boot.
func mustBe(dir string, e extension.Extension) extension.Extension {
	if string(e.Name) != dir {
		panic("composition: extensions/" + dir + " declares Name \"" + string(e.Name) + "\" — the unit name is its directory name")
	}
	return e
}
`)
	return []byte(b.String())
}

// tsString renders a Go string as a TypeScript string literal through
// encoding/json rather than strconv.Quote: JSON's escaping is a strict subset
// of what a TS double-quoted literal accepts (and it escapes <, > and & as
// \uXXXX), whereas Go's own quoting has forms — raw non-ASCII runes carried
// through verbatim — that would put a unit author's prose into the emitted
// source unescaped. A string that cannot be marshalled does not exist: every
// input here has already round-tripped through the merged YAML document.
func tsString(s string) string {
	encoded, err := json.Marshal(s)
	if err != nil {
		panic("gen-composition: a string from the merged contract is not JSON-encodable: " + err.Error())
	}
	return string(encoded)
}

// writeVerbLiterals emits the composed verb set as a Go slice literal. Fields
// are written unconditionally rather than omitted when zero: the emitted
// source is what a reviewer reads to see what an installation publishes, and a
// missing line would have to be read as "absent" or as "the zero value" with
// nothing on the page to say which.
func writeVerbLiterals(b *strings.Builder, verbs []declaredVerb) {
	if len(verbs) == 0 {
		b.WriteString("\treturn nil\n}\n")
		return
	}
	b.WriteString("\treturn []extension.Verb{\n")
	for _, d := range verbs {
		v := d.verb
		b.WriteString("\t\t{\n")
		fmt.Fprintf(b, "\t\t\tUnit:           %q,\n", string(v.Unit))
		fmt.Fprintf(b, "\t\t\tContract:       %q,\n", v.Contract)
		fmt.Fprintf(b, "\t\t\tOperationID:    %q,\n", v.OperationID)
		fmt.Fprintf(b, "\t\t\tRoute:          %q,\n", v.Route)
		fmt.Fprintf(b, "\t\t\tMethod:         %q,\n", v.Method)
		fmt.Fprintf(b, "\t\t\tTool:           %q,\n", v.Tool)
		fmt.Fprintf(b, "\t\t\tTitle:          %q,\n", v.Title)
		fmt.Fprintf(b, "\t\t\tDescription:    %q,\n", v.Description)
		fmt.Fprintf(b, "\t\t\tVersion:        %q,\n", v.Version)
		fmt.Fprintf(b, "\t\t\tTier:           %q,\n", string(v.Tier))
		fmt.Fprintf(b, "\t\t\tRequestedScope: %q,\n", string(v.RequestedScope))
		writeSchemaLiteral(b, "InputSchema", v.InputSchema)
		writeSchemaLiteral(b, "OutputSchema", v.OutputSchema)
		fmt.Fprintf(b, "\t\t\tRbacObject:     %q,\n", v.RbacObject)
		if !v.Subject.IsZero() {
			// Emitted only when declared, so the generated literal reads the
			// way the fragment does: a tier that never stages carries no
			// subject, and a zero struct written out would look like one that
			// was declared empty.
			fmt.Fprintf(b, "\t\t\tSubject:        extension.Subject{Arg: %q, Table: %q},\n", v.Subject.Arg, v.Subject.Table)
		}
		fmt.Fprintf(b, "\t\t\tRbacAction:     %q,\n", string(v.RbacAction))
		b.WriteString("\t\t},\n")
	}
	b.WriteString("\t}\n}\n")
}

// writeSchemaLiteral emits a json.RawMessage field. A nil schema is emitted as
// `nil`, not as an empty literal: the served adapter defaults a missing input
// schema to `{"type":"object"}`, and `json.RawMessage("")` is not that — it is
// a value every JSON decoder rejects.
func writeSchemaLiteral(b *strings.Builder, field string, raw json.RawMessage) {
	if raw == nil {
		fmt.Fprintf(b, "\t\t\t%s:%s nil,\n", field, strings.Repeat(" ", len("RequestedScope")-len(field)))
		return
	}
	fmt.Fprintf(b, "\t\t\t%s:%s json.RawMessage(%q),\n", field, strings.Repeat(" ", len("RequestedScope")-len(field)), string(raw))
}

// writeJobLiterals emits the composed job set as a Go slice literal.
//
// Durations go through mustDuration carrying the contract's own spelling, so
// the emitted file reads `mustDuration("6h0m0s")` rather than a nanosecond
// count. See extensionsGenDurationHelper.
//
// Fields are written unconditionally rather than omitted when zero, for the
// reason the verb literals are: the emitted source is what a reviewer reads to
// see what an installation schedules, and a missing line would have to be read
// as "absent" or as "the zero value" with nothing on the page to say which.
func writeJobLiterals(b *strings.Builder, decls []extension.JobDeclaration) {
	if len(decls) == 0 {
		b.WriteString("\treturn nil\n}\n")
		return
	}
	b.WriteString("\treturn []extension.JobDeclaration{\n")
	for _, d := range decls {
		b.WriteString("\t\t{\n")
		fmt.Fprintf(b, "\t\t\tUnit:              %q,\n", string(d.Unit))
		fmt.Fprintf(b, "\t\t\tJob:               %q,\n", d.Job)
		fmt.Fprintf(b, "\t\t\tQueue:             %q,\n", d.Queue)
		fmt.Fprintf(b, "\t\t\tCadence:           mustDuration(%q),\n", d.Cadence.String())
		fmt.Fprintf(b, "\t\t\tDispatcherTimeout: mustDuration(%q),\n", d.DispatcherTimeout.String())
		fmt.Fprintf(b, "\t\t\tTimeout:           mustDuration(%q),\n", d.Timeout.String())
		fmt.Fprintf(b, "\t\t\tMaxAttempts:       %d,\n", d.MaxAttempts)
		fmt.Fprintf(b, "\t\t\tTier:              %q,\n", string(d.Tier))
		fmt.Fprintf(b, "\t\t\tRequestedScope:    %q,\n", string(d.RequestedScope))
		b.WriteString("\t\t},\n")
	}
	b.WriteString("\t}\n}\n")
}

// anySchema reports whether the emitted literals will mention
// json.RawMessage, which decides whether the generated file imports
// encoding/json at all.
func anySchema(verbs []declaredVerb) bool {
	for _, d := range verbs {
		if d.verb.InputSchema != nil || d.verb.OutputSchema != nil {
			return true
		}
	}
	return false
}
