// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package main

// The SPA's three composed artifacts: the descriptor registry, the screen
// registry and the copy overlay. Split out of emit.go, which emits the Go
// wiring and the workspace — one file per side of the composition, because the
// frontend's rules are its own (every artifact here must be import-free, so the
// two locations it is written to can stay byte-identical).

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/margince/margince/backend/pkg/extension"
)

// frontendGenHeader is shared by the committed vanilla stub and every composed
// output — the vanilla body below it must stay byte-identical to
// frontend/src/composition/extensions.gen.ts (held by `-verify` via
// stubMatchesVanilla), so the SPA's two lanes differ only in the registry they
// resolve.
//
// Written to be Biome-clean as committed: the vanilla copy lives under
// frontend/src, which `pnpm lint` formats-checks, so a template change that
// drifts from Biome's style breaks the frontend gate rather than the
// composition one.
// extScreensGenHeader is the screen registry's preamble, and it carries the
// same Biome-clean discipline the descriptor header does: its vanilla copy
// lives under frontend/src, which `pnpm lint` formats-checks, so a template
// that drifts from Biome's style breaks the frontend gate.
//
// It imports NOTHING, and that is a hard requirement rather than a style: this
// file is written to two locations at different depths — frontend/src/composition/
// and build/composition/frontend/ — and stubMatchesVanilla requires the two to
// be byte-identical, so any relative specifier would have to differ between
// them and could not. A bare specifier is no better: `react` does not resolve
// from build/composition/, which is outside every node_modules on the path.
//
// So the registry is emitted UNTYPED and App.tsx applies ExtensionScreenRegistry
// at the import site. The check is not lost, only moved: a unit whose default
// export is not a component fails that assignment, in core, in the composed
// lane. The descriptor registry solves the same problem the other way, by
// declaring its type inline — which works there because a descriptor is plain
// data and does not need React's types.
const extScreensGenHeader = `// Code generated by gen-composition from the enabled set under extensions/; DO NOT EDIT.
// Regenerate: make gen (backend/tools/gen-composition). The DEFAULT (vanilla) lane
// resolves the committed empty-tree copy of this file, at
// frontend/src/composition/extscreens.gen.ts, through tsconfig's
// "@composition/screens" alias; a composed lane repoints that alias at
// build/composition/frontend/.
//
// Which unit package renders which unit. A unit ships its screen in its own
// frontend/ layer — a pnpm workspace package named @margince-ext/<unit> — and
// this registry is the only place the SPA learns it exists. A composed unit
// absent from this map is not an error: App.tsx falls through to the generic
// published-operations card, which is what a unit with no bespoke screen gets.
`

// extLocalesGenHeader is the copy overlay's preamble. Import-free for the same
// reason extScreensGenHeader is.
const extLocalesGenHeader = `// Code generated by gen-composition from the enabled set under extensions/; DO NOT EDIT.
// Regenerate: make gen (backend/tools/gen-composition). The DEFAULT (vanilla) lane
// resolves the committed empty-tree copy of this file, at
// frontend/src/composition/extlocales.gen.ts, through tsconfig's
// "@composition/copy" alias; a composed lane repoints that alias at
// build/composition/frontend/.
//
// Every enabled unit's own copy, per locale. A unit ships extensions/<name>/
// frontend/i18n/<locale>.json and this merges them, so there is still ONE
// catalogue, one lookup and one missing-key gate — and the strings travel with
// the unit rather than staying behind when it is removed. Core keys win on a
// collision, and a unit's keys are namespaced to the unit, so a unit cannot
// rewrite core copy even if that ordering were ever loosened.
`

// frontendGen emits the SPA's composed registry. The empty set reproduces
// the committed vanilla stub byte-for-byte (held by stubMatchesVanilla), which
// is what makes the two frontend lanes provably the same program over a
// different registry rather than two programs.
//
// DESCRIPTORS, which is a different artifact from the screens: this registry is
// what App.tsx falls back to for a unit with no bespoke screen, and it composes
// for every unit whether or not one exists. The screens are extScreensGen's.
// What composes here is the set of governed operations the unit's contract
// fragments publish, read back out of the MERGED contracts by
// extensionVerbs: the same source the routes, the tools and the manifests
// derive from, so a screen cannot advertise an operation the server does not
// serve.
// It takes the DERIVED MANIFESTS rather than the scanned units, because one of
// the fields it emits — the secret scope the SPA places the unit's settings
// entry by — lives in the declaration and not on disk beside it. Reading it
// from a second parse of the same Go would let the registry and the unit's own
// manifest.generated.json disagree about a unit while both looked derived.
func frontendGen(manifests []derivedManifest, verbs []declaredVerb) []byte {
	var b strings.Builder
	b.WriteString(frontendGenHeader)
	if len(manifests) == 0 {
		b.WriteString("[];\n")
		return []byte(b.String())
	}
	b.WriteString("[\n")
	for _, m := range manifests {
		name := m.Unit.Name
		fmt.Fprintf(&b, "  {\n    name: %s,\n    secretScope: %s,\n    verbs: [\n", tsString(name), tsString(unitSecretScope(m.Manifest)))
		for _, d := range verbs {
			if string(d.verb.Unit) != name {
				continue
			}
			writeVerbDescriptor(&b, d.verb)
		}
		b.WriteString("    ],\n  },\n")
	}
	b.WriteString("];\n")
	return []byte(b.String())
}

// extScreensGen emits the SPA's composed SCREEN registry: which unit package
// renders which unit. The empty set reproduces the committed vanilla stub
// byte-for-byte (held by stubMatchesVanilla), like every other artifact here.
//
// It is separate from frontendGen because the two answer different questions
// and a unit may have either without the other: the descriptor registry says
// what a unit PUBLISHES and exists for every unit, while this says what RENDERS
// it and exists only for a unit that ships a frontend package. A unit with none
// falls through to the generic published-operations card, which is what de
// and crm-hello do.
//
// Import order follows unit order, which scanExtensions has already sorted by
// name, so this file is a function of the enabled set rather than of the order
// the filesystem happened to hand directories over.
func extScreensGen(units []extensionUnit) []byte {
	var imports, entries strings.Builder
	for _, u := range units {
		if u.Frontend == nil {
			continue
		}
		ident := screenIdent(u.Name)
		fmt.Fprintf(&imports, "import %s from %s;\n", ident, tsString(u.Frontend.Export))
		fmt.Fprintf(&entries, "  %s: %s,\n", tsString(u.Name), ident)
	}
	var b strings.Builder
	b.WriteString(extScreensGenHeader)
	b.WriteString(imports.String())
	if entries.Len() == 0 {
		b.WriteString("\nexport const extensionScreens = {};\n")
		return []byte(b.String())
	}
	b.WriteString("\nexport const extensionScreens = {\n")
	b.WriteString(entries.String())
	b.WriteString("};\n")
	return []byte(b.String())
}

// extLocalesGen emits the merged copy overlay: every enabled unit's strings,
// per locale, in one object the catalogue spreads over its own.
//
// Emitted UNTYPED and import-free for the reason extScreensGen is: this file is
// written to two locations at different depths and stubMatchesVanilla requires
// them byte-identical, so it can carry no relative specifier. The catalogue
// applies the type where it consumes it.
//
// Locales and keys are both emitted in sorted order, so the file is a function
// of the enabled set rather than of map iteration.
func extLocalesGen(merged map[string]map[string]string) []byte {
	var b strings.Builder
	b.WriteString(extLocalesGenHeader)
	if len(merged) == 0 {
		b.WriteString("\nexport const extensionCopy = {};\n")
		return []byte(b.String())
	}
	b.WriteString("\nexport const extensionCopy = {\n")
	locales := make([]string, 0, len(merged))
	for locale := range merged {
		locales = append(locales, locale)
	}
	sort.Strings(locales)
	for _, locale := range locales {
		fmt.Fprintf(&b, "  %s: {\n", tsString(locale))
		for _, key := range sortedKeys(merged[locale]) {
			fmt.Fprintf(&b, "    %s: %s,\n", tsString(key), tsString(merged[locale][key]))
		}
		b.WriteString("  },\n")
	}
	b.WriteString("};\n")
	return []byte(b.String())
}

// writeVerbDescriptor emits one operation. Fields are written unconditionally,
// for the same reason the Go literals are: the emitted file is what a reviewer
// reads to see what an installation publishes to its own UI, and a missing
// line would have to be read as "absent" or as "the empty string" with nothing
// on the page to say which.
func writeVerbDescriptor(b *strings.Builder, v extension.Verb) {
	b.WriteString("      {\n")
	fmt.Fprintf(b, "        operationId: %s,\n", tsString(v.OperationID))
	fmt.Fprintf(b, "        route: %s,\n", tsString(v.Route))
	fmt.Fprintf(b, "        method: %s,\n", tsString(v.Method))
	fmt.Fprintf(b, "        title: %s,\n", tsString(v.Title))
	fmt.Fprintf(b, "        version: %s,\n", tsString(v.Version))
	fmt.Fprintf(b, "        rbacObject: %s,\n", tsString(v.RbacObject))
	b.WriteString("      },\n")
}

// composedFrontendWorkspaceDir is the second composition root, and it is
// deliberately OUTSIDE build/composition/.
//
// verifyNoExtraFiles (main.go) walks build/composition/ and rejects every file
// the Go generator did not write, non-regular files included. A pnpm install
// inside that tree writes node_modules — a directory pnpm builds out of
// symlinks — plus a lockfile, so putting a workspace there would make
// `make check-composition` fail on the install rather than on a real drift.
// build/composition-frontend/ already exists for exactly this reason: it holds
// what a NODE tool produces, verified by the frontend lane that can reproduce
// it rather than by this one.
const composedFrontendWorkspaceDir = "build/composition-frontend/workspace"

// The host SPA is deliberately NOT a member of this workspace, and the reason is
// mechanical: pnpm writes node_modules BESIDE each member, wherever the member
// lives. A workspace naming ../../../frontend would install into
// frontend/node_modules — the same directory the ROOT workspace owns and
// installs with --frozen-lockfile — so the two would resolve independently and
// prune each other's trees on alternate runs.
//
// A unit declares "@margince/frontend": "workspace:*", and pnpm refuses that
// specifier outright when no member answers to the name
// (ERR_PNPM_WORKSPACE_PKG_NOT_FOUND). So the root manifest overrides it to
// `link:` the host directory: a link RESOLVES the dependency and installs
// nothing, which is exactly the distinction — the unit gets its declaration
// satisfied, and frontend/node_modules stays the root workspace's to own.
//
// At build time a unit reaches the host through vite.config.ts's aliases on the
// three subpaths frontend/package.json's "exports" map publishes, with matching
// paths entries in tsconfig.composed.json. That half was measured to work on its
// own; what it could not do is resolve a unit's OWN dependencies, which is what
// this workspace is for.
//
// THE HOSTED PACKAGES ARE LINKED FOR THE SAME REASON, and it is the same rule
// resolve.dedupe and gen-composition's hostedFrameworkDeps state: exactly one
// copy of anything holding state the host owns. Installed rather than linked,
// a unit gets its own @types/react, and tsc then reports "Two different types
// with this name exist, but they are unrelated" against the host's design
// system — measured, and the reason these four entries exist. The runtime three
// carry the same hazard for the same reason (one hook dispatcher, one
// QueryClient context); a unit's test-only dev deps are its own, because
// resolve.dedupe pins the render tree at run time.
//
// The link targets are inside frontend/node_modules, so the ROOT install must
// have run first. The make lanes order it that way, and a dangling link here
// fails loudly at the next resolve rather than silently resolving twice.

// emitComposedFrontendWorkspace writes a pnpm workspace whose members are the
// host SPA and each enabled unit's frontend layer.
//
// WHY THIS EXISTS. A unit's frontend/ used to be a member of the ROOT workspace
// (pnpm-workspace.yaml's `extensions/*/frontend` glob), which meant an
// installation that enabled a frontend-bearing unit of its own could not install
// without rewriting the tracked root pnpm-lock.yaml — an upstream-owned file.
// Measured, not assumed: `pnpm install --frozen-lockfile` with such a unit
// present fails ERR_PNPM_OUTDATED_LOCKFILE naming the unit's manifest.
//
// Membership cannot simply be dropped. It is also what installs and resolves a
// unit's OWN dependencies from inside the unit's directory: without it the
// composed typecheck lane cannot resolve a unit's peers or its dev deps, and a
// tsconfig `paths` mapping is no substitute — a path mapping is project-wide and
// hijacks the host's own resolution. So membership moves rather than goes: the
// members live in a generated workspace under ignored build output, whose
// lockfile nobody tracks and whose install cannot touch the root's.
//
// The file set is REPLACED on every call, so a unit removed from extensions/
// stops being a member. An accumulating list would leave the next install
// resolving a member that is not there.
func emitComposedFrontendWorkspace(dir string, units []string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil { // #nosec G301 -- build output stays readable to another UID
		return err
	}
	// A root that is private and owns no dependencies. It exists to BE a
	// workspace root: anything it depended on would be a second copy of what the
	// host already owns, which is the hazard resolve.dedupe exists to prevent.
	manifest := []byte(`{
  "name": "@margince/composed-workspace",
  "private": true,
  "version": "0.0.0",
  "//": "GENERATED by tools/gen-composition. The composed frontend workspace root: its members are every enabled unit's frontend layer. Do not edit; do not commit (build/ is ignored). The overrides this workspace needs live in pnpm-workspace.yaml, NOT here: pnpm 11 stopped reading the \"pnpm\" field of package.json."
}
`)
	if err := os.WriteFile(filepath.Join(dir, "package.json"), manifest, 0o644); err != nil { // #nosec G306 -- generated build artifact
		return err
	}

	// Sorted, for the same reason go.work's members are: the emitted bytes must
	// not depend on the order the tree was walked in.
	members := make([]string, len(units))
	copy(members, units)
	sort.Strings(members)

	var b strings.Builder
	b.WriteString("# GENERATED by tools/gen-composition. Do not edit.\n")
	b.WriteString("#\n")
	b.WriteString("# The composed frontend workspace: every enabled unit's frontend layer, and\n")
	b.WriteString("# only those. Members are reached by relative path out of this generated\n")
	b.WriteString("# directory rather than copied, so an edit in extensions/<unit>/frontend/ is\n")
	b.WriteString("# what the next install resolves. The host SPA is not a member — see above.\n")
	b.WriteString("packages:\n")
	for _, unit := range members {
		fmt.Fprintf(&b, "  - ../../../extensions/%s/frontend\n", unit)
	}
	// esbuild ships a platform binary and needs its install script to run — the
	// same carve-out the root workspace states, for the same reason.
	b.WriteString("\nallowBuilds:\n  esbuild: true\n")

	// The overrides live HERE and not in the root package.json's "pnpm" field,
	// and the difference is not cosmetic: pnpm 11 ignores that field outright
	// ("The \"pnpm\" field in package.json is no longer read by pnpm"), so the
	// overrides silently stopped applying and the install failed on the
	// workspace:* specifier again. pnpm 10 and 11 both read them from here.
	//
	// A unit declares "@margince/frontend": "workspace:*", which pnpm refuses
	// when no member answers to the name (ERR_PNPM_WORKSPACE_PKG_NOT_FOUND). The
	// override resolves it to a `link:`, which satisfies the declaration and
	// installs nothing — so frontend/node_modules stays the root workspace's to
	// own. The other four are the packages whose state the host owns: installed
	// rather than linked, a unit gets its own @types/react and tsc reports two
	// unrelated types of the same name against the host's design system.
	b.WriteString("\noverrides:\n")
	for _, override := range [][2]string{
		{"@margince/frontend", "link:../../../frontend"},
		{"react", "link:../../../frontend/node_modules/react"},
		{"react-dom", "link:../../../frontend/node_modules/react-dom"},
		{"@tanstack/react-query", "link:../../../frontend/node_modules/@tanstack/react-query"},
		{"@types/react", "link:../../../frontend/node_modules/@types/react"},
	} {
		fmt.Fprintf(&b, "  %q: %q\n", override[0], override[1])
	}
	return os.WriteFile(filepath.Join(dir, "pnpm-workspace.yaml"), []byte(b.String()), 0o644) // #nosec G306 -- generated build artifact
}
